

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LightSwitchApplication
{
    #region Entities
    
    /// <summary>
    /// No Modeled Description Available
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.1.0.0")]
    public sealed partial class Nasoka : global::Microsoft.LightSwitch.Framework.Base.EntityObject<global::LightSwitchApplication.Nasoka, global::LightSwitchApplication.Nasoka.DetailsClass>
    {
        #region Constructors
    
        /// <summary>
        /// Initializes a new instance of the Nasoka entity.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.1.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public Nasoka()
            : this(null)
        {
        }
    
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.1.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public Nasoka(global::Microsoft.LightSwitch.Framework.EntitySet<global::LightSwitchApplication.Nasoka> entitySet)
            : base(entitySet)
        {
            global::LightSwitchApplication.Nasoka.DetailsClass.Initialize(this);
        }
    
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Nasoka_Created();
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Nasoka_AllowSaveWithErrors(ref bool result);
    
        #endregion
    
        #region Private Properties
        
        /// <summary>
        /// Gets the Application object for this application.  The Application object provides access to active screens, methods to open screens and access to the current user.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.1.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::Microsoft.LightSwitch.IApplication<global::LightSwitchApplication.DataWorkspace> Application
        {
            get
            {
                return (global::Microsoft.LightSwitch.IApplication<global::LightSwitchApplication.DataWorkspace>)global::LightSwitchApplication.Application.Current;
            }
        }
        
        /// <summary>
        /// Gets the containing data workspace.  The data workspace provides access to all data sources in the application.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.1.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::LightSwitchApplication.DataWorkspace DataWorkspace
        {
            get
            {
                return (global::LightSwitchApplication.DataWorkspace)this.Details.EntitySet.Details.DataService.Details.DataWorkspace;
            }
        }
        
        #endregion
    
        #region Public Properties
    
        /// <summary>
        /// No Modeled Description Available
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.1.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public int ID_Nasoka
        {
            get
            {
                return global::LightSwitchApplication.Nasoka.DetailsClass.GetValue(this, global::LightSwitchApplication.Nasoka.DetailsClass.PropertySetProperties.ID_Nasoka);
            }
        }
        
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void ID_Nasoka_IsReadOnly(ref bool result);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void ID_Nasoka_Validate(global::Microsoft.LightSwitch.EntityValidationResultsBuilder results);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void ID_Nasoka_Changed();

        /// <summary>
        /// No Modeled Description Available
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.1.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public string Nasok
        {
            get
            {
                return global::LightSwitchApplication.Nasoka.DetailsClass.GetValue(this, global::LightSwitchApplication.Nasoka.DetailsClass.PropertySetProperties.Nasok);
            }
            set
            {
                global::LightSwitchApplication.Nasoka.DetailsClass.SetValue(this, global::LightSwitchApplication.Nasoka.DetailsClass.PropertySetProperties.Nasok, value);
            }
        }
        
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Nasok_IsReadOnly(ref bool result);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Nasok_Validate(global::Microsoft.LightSwitch.EntityValidationResultsBuilder results);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Nasok_Changed();

        /// <summary>
        /// No Modeled Description Available
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.1.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::Microsoft.LightSwitch.Framework.EntityCollection<global::LightSwitchApplication.Predmet> Predmets
        {
            get
            {
                return global::LightSwitchApplication.Nasoka.DetailsClass.GetValue(this, global::LightSwitchApplication.Nasoka.DetailsClass.PropertySetProperties.Predmets);
            }
        }
        
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.1.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public Microsoft.LightSwitch.IDataServiceQueryable<global::LightSwitchApplication.Predmet> PredmetsQuery
        {
            get
            {
                return global::LightSwitchApplication.Nasoka.DetailsClass.GetQuery(this, global::LightSwitchApplication.Nasoka.DetailsClass.PropertySetProperties.Predmets);
            }
        }

        /// <summary>
        /// No Modeled Description Available
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.1.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::Microsoft.LightSwitch.Framework.EntityCollection<global::LightSwitchApplication.Student> Students
        {
            get
            {
                return global::LightSwitchApplication.Nasoka.DetailsClass.GetValue(this, global::LightSwitchApplication.Nasoka.DetailsClass.PropertySetProperties.Students);
            }
        }
        
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.1.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public Microsoft.LightSwitch.IDataServiceQueryable<global::LightSwitchApplication.Student> StudentsQuery
        {
            get
            {
                return global::LightSwitchApplication.Nasoka.DetailsClass.GetQuery(this, global::LightSwitchApplication.Nasoka.DetailsClass.PropertySetProperties.Students);
            }
        }

        #endregion
    
        #region Details Class
    
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        [global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1034:NestedTypesShouldNotBeVisible")]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.1.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public sealed class DetailsClass : global::Microsoft.LightSwitch.Details.Framework.Base.EntityDetails<
                global::LightSwitchApplication.Nasoka,
                global::LightSwitchApplication.Nasoka.DetailsClass,
                global::LightSwitchApplication.Nasoka.DetailsClass.IImplementation,
                global::LightSwitchApplication.Nasoka.DetailsClass.PropertySet,
                global::Microsoft.LightSwitch.Details.Framework.EntityCommandSet<global::LightSwitchApplication.Nasoka, global::LightSwitchApplication.Nasoka.DetailsClass>,
                global::Microsoft.LightSwitch.Details.Framework.EntityMethodSet<global::LightSwitchApplication.Nasoka, global::LightSwitchApplication.Nasoka.DetailsClass>>
        {
    
            static DetailsClass()
            {
                var initializeEntry = global::LightSwitchApplication.Nasoka.DetailsClass.PropertySetProperties.ID_Nasoka;
            }
    
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private static readonly global::Microsoft.LightSwitch.Details.Framework.Base.EntityDetails<global::LightSwitchApplication.Nasoka, global::LightSwitchApplication.Nasoka.DetailsClass>.Entry
                __NasokaEntry = new global::Microsoft.LightSwitch.Details.Framework.Base.EntityDetails<global::LightSwitchApplication.Nasoka, global::LightSwitchApplication.Nasoka.DetailsClass>.Entry(
                    global::LightSwitchApplication.Nasoka.DetailsClass.__Nasoka_CreateNew,
                    global::LightSwitchApplication.Nasoka.DetailsClass.__Nasoka_Created,
                    global::LightSwitchApplication.Nasoka.DetailsClass.__Nasoka_AllowSaveWithErrors);
            private static global::LightSwitchApplication.Nasoka __Nasoka_CreateNew(global::Microsoft.LightSwitch.Framework.EntitySet<global::LightSwitchApplication.Nasoka> es)
            {
                return new global::LightSwitchApplication.Nasoka(es);
            }
            private static void __Nasoka_Created(global::LightSwitchApplication.Nasoka e)
            {
                e.Nasoka_Created();
            }
            private static bool __Nasoka_AllowSaveWithErrors(global::LightSwitchApplication.Nasoka e)
            {
                bool result = false;
                e.Nasoka_AllowSaveWithErrors(ref result);
                return result;
            }
    
            public DetailsClass() : base()
            {
            }
    
            public new global::Microsoft.LightSwitch.Details.Framework.EntityCommandSet<global::LightSwitchApplication.Nasoka, global::LightSwitchApplication.Nasoka.DetailsClass> Commands
            {
                get
                {
                    return base.Commands;
                }
            }
    
            public new global::Microsoft.LightSwitch.Details.Framework.EntityMethodSet<global::LightSwitchApplication.Nasoka, global::LightSwitchApplication.Nasoka.DetailsClass> Methods
            {
                get
                {
                    return base.Methods;
                }
            }
    
            public new global::LightSwitchApplication.Nasoka.DetailsClass.PropertySet Properties
            {
                get
                {
                    return base.Properties;
                }
            }
    
            [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
            [global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1034:NestedTypesShouldNotBeVisible")]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.1.0.0")]
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public sealed class PropertySet : global::Microsoft.LightSwitch.Details.Framework.Base.EntityPropertySet<global::LightSwitchApplication.Nasoka, global::LightSwitchApplication.Nasoka.DetailsClass>
            {
    
                public PropertySet() : base()
                {
                }
    
                public global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Nasoka, global::LightSwitchApplication.Nasoka.DetailsClass, int> ID_Nasoka
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.Nasoka.DetailsClass.PropertySetProperties.ID_Nasoka) as global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Nasoka, global::LightSwitchApplication.Nasoka.DetailsClass, int>;
                    }
                }
                
                public global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Nasoka, global::LightSwitchApplication.Nasoka.DetailsClass, string> Nasok
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.Nasoka.DetailsClass.PropertySetProperties.Nasok) as global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Nasoka, global::LightSwitchApplication.Nasoka.DetailsClass, string>;
                    }
                }
                
                public global::Microsoft.LightSwitch.Details.Framework.EntityCollectionProperty<global::LightSwitchApplication.Nasoka, global::LightSwitchApplication.Nasoka.DetailsClass, global::LightSwitchApplication.Predmet> Predmets
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.Nasoka.DetailsClass.PropertySetProperties.Predmets) as global::Microsoft.LightSwitch.Details.Framework.EntityCollectionProperty<global::LightSwitchApplication.Nasoka, global::LightSwitchApplication.Nasoka.DetailsClass, global::LightSwitchApplication.Predmet>;
                    }
                }
                
                public global::Microsoft.LightSwitch.Details.Framework.EntityCollectionProperty<global::LightSwitchApplication.Nasoka, global::LightSwitchApplication.Nasoka.DetailsClass, global::LightSwitchApplication.Student> Students
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.Nasoka.DetailsClass.PropertySetProperties.Students) as global::Microsoft.LightSwitch.Details.Framework.EntityCollectionProperty<global::LightSwitchApplication.Nasoka, global::LightSwitchApplication.Nasoka.DetailsClass, global::LightSwitchApplication.Student>;
                    }
                }
                
            }
    
            #pragma warning disable 109
            [global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1034:NestedTypesShouldNotBeVisible")]
            public interface IImplementation : global::Microsoft.LightSwitch.Internal.IEntityImplementation
            {
                new int ID_Nasoka { get; }
                new string Nasok { get; set; }
                new global::System.Collections.IEnumerable Predmets { get; }
                new global::System.Collections.IEnumerable Students { get; }
            }
            #pragma warning restore 109
    
            [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.1.0.0")]
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            internal class PropertySetProperties
            {
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Nasoka, global::LightSwitchApplication.Nasoka.DetailsClass, int>.Entry
                    ID_Nasoka = new global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Nasoka, global::LightSwitchApplication.Nasoka.DetailsClass, int>.Entry(
                        "ID_Nasoka",
                        global::LightSwitchApplication.Nasoka.DetailsClass.PropertySetProperties._ID_Nasoka_Stub,
                        global::LightSwitchApplication.Nasoka.DetailsClass.PropertySetProperties._ID_Nasoka_ComputeIsReadOnly,
                        global::LightSwitchApplication.Nasoka.DetailsClass.PropertySetProperties._ID_Nasoka_Validate,
                        global::LightSwitchApplication.Nasoka.DetailsClass.PropertySetProperties._ID_Nasoka_GetImplementationValue,
                        null,
                        global::LightSwitchApplication.Nasoka.DetailsClass.PropertySetProperties._ID_Nasoka_OnValueChanged);
                private static void _ID_Nasoka_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.Nasoka.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Nasoka, global::LightSwitchApplication.Nasoka.DetailsClass, int>.Data> c, global::LightSwitchApplication.Nasoka.DetailsClass d, object sf)
                {
                    c(d, ref d._ID_Nasoka, sf);
                }
                private static bool _ID_Nasoka_ComputeIsReadOnly(global::LightSwitchApplication.Nasoka e)
                {
                    bool result = false;
                    e.ID_Nasoka_IsReadOnly(ref result);
                    return result;
                }
                private static void _ID_Nasoka_Validate(global::LightSwitchApplication.Nasoka e, global::Microsoft.LightSwitch.EntityValidationResultsBuilder r)
                {
                    e.ID_Nasoka_Validate(r);
                }
                private static int _ID_Nasoka_GetImplementationValue(global::LightSwitchApplication.Nasoka.DetailsClass d)
                {
                    return d.ImplementationEntity.ID_Nasoka;
                }
                private static void _ID_Nasoka_OnValueChanged(global::LightSwitchApplication.Nasoka e)
                {
                    e.ID_Nasoka_Changed();
                }
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Nasoka, global::LightSwitchApplication.Nasoka.DetailsClass, string>.Entry
                    Nasok = new global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Nasoka, global::LightSwitchApplication.Nasoka.DetailsClass, string>.Entry(
                        "Nasok",
                        global::LightSwitchApplication.Nasoka.DetailsClass.PropertySetProperties._Nasok_Stub,
                        global::LightSwitchApplication.Nasoka.DetailsClass.PropertySetProperties._Nasok_ComputeIsReadOnly,
                        global::LightSwitchApplication.Nasoka.DetailsClass.PropertySetProperties._Nasok_Validate,
                        global::LightSwitchApplication.Nasoka.DetailsClass.PropertySetProperties._Nasok_GetImplementationValue,
                        global::LightSwitchApplication.Nasoka.DetailsClass.PropertySetProperties._Nasok_SetImplementationValue,
                        global::LightSwitchApplication.Nasoka.DetailsClass.PropertySetProperties._Nasok_OnValueChanged);
                private static void _Nasok_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.Nasoka.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Nasoka, global::LightSwitchApplication.Nasoka.DetailsClass, string>.Data> c, global::LightSwitchApplication.Nasoka.DetailsClass d, object sf)
                {
                    c(d, ref d._Nasok, sf);
                }
                private static bool _Nasok_ComputeIsReadOnly(global::LightSwitchApplication.Nasoka e)
                {
                    bool result = false;
                    e.Nasok_IsReadOnly(ref result);
                    return result;
                }
                private static void _Nasok_Validate(global::LightSwitchApplication.Nasoka e, global::Microsoft.LightSwitch.EntityValidationResultsBuilder r)
                {
                    e.Nasok_Validate(r);
                }
                private static string _Nasok_GetImplementationValue(global::LightSwitchApplication.Nasoka.DetailsClass d)
                {
                    return d.ImplementationEntity.Nasok;
                }
                private static void _Nasok_SetImplementationValue(global::LightSwitchApplication.Nasoka.DetailsClass d, string v)
                {
                    d.ImplementationEntity.Nasok = v;
                }
                private static void _Nasok_OnValueChanged(global::LightSwitchApplication.Nasoka e)
                {
                    e.Nasok_Changed();
                }
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityCollectionProperty<global::LightSwitchApplication.Nasoka, global::LightSwitchApplication.Nasoka.DetailsClass, global::LightSwitchApplication.Predmet>.Entry
                    Predmets = new global::Microsoft.LightSwitch.Details.Framework.EntityCollectionProperty<global::LightSwitchApplication.Nasoka, global::LightSwitchApplication.Nasoka.DetailsClass, global::LightSwitchApplication.Predmet>.Entry(
                        "Predmets",
                        global::LightSwitchApplication.Nasoka.DetailsClass.PropertySetProperties._Predmets_Stub,
                        global::LightSwitchApplication.Nasoka.DetailsClass.PropertySetProperties._Predmets_GetReferencedEntities,
                        global::LightSwitchApplication.Nasoka.DetailsClass.PropertySetProperties._Predmets_GetEntityCollection);
                private static void _Predmets_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.Nasoka.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityCollectionProperty<global::LightSwitchApplication.Nasoka, global::LightSwitchApplication.Nasoka.DetailsClass, global::LightSwitchApplication.Predmet>.Data> c, global::LightSwitchApplication.Nasoka.DetailsClass d, object sf)
                {
                    c(d, ref d._Predmets, sf);
                }
                private static global::System.Collections.Generic.IEnumerable<global::LightSwitchApplication.Predmet> _Predmets_GetReferencedEntities(global::LightSwitchApplication.Nasoka.DetailsClass d)
                {
                    return d.GetReferencedEntities<global::LightSwitchApplication.Predmet, global::LightSwitchApplication.Predmet.DetailsClass>(global::LightSwitchApplication.Nasoka.DetailsClass.PropertySetProperties.Predmets, ref d._Predmets);
                }
                private static global::System.Collections.IEnumerable _Predmets_GetEntityCollection(global::LightSwitchApplication.Nasoka.DetailsClass d)
                {
                    return d.ImplementationEntity.Predmets;
                }
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityCollectionProperty<global::LightSwitchApplication.Nasoka, global::LightSwitchApplication.Nasoka.DetailsClass, global::LightSwitchApplication.Student>.Entry
                    Students = new global::Microsoft.LightSwitch.Details.Framework.EntityCollectionProperty<global::LightSwitchApplication.Nasoka, global::LightSwitchApplication.Nasoka.DetailsClass, global::LightSwitchApplication.Student>.Entry(
                        "Students",
                        global::LightSwitchApplication.Nasoka.DetailsClass.PropertySetProperties._Students_Stub,
                        global::LightSwitchApplication.Nasoka.DetailsClass.PropertySetProperties._Students_GetReferencedEntities,
                        global::LightSwitchApplication.Nasoka.DetailsClass.PropertySetProperties._Students_GetEntityCollection);
                private static void _Students_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.Nasoka.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityCollectionProperty<global::LightSwitchApplication.Nasoka, global::LightSwitchApplication.Nasoka.DetailsClass, global::LightSwitchApplication.Student>.Data> c, global::LightSwitchApplication.Nasoka.DetailsClass d, object sf)
                {
                    c(d, ref d._Students, sf);
                }
                private static global::System.Collections.Generic.IEnumerable<global::LightSwitchApplication.Student> _Students_GetReferencedEntities(global::LightSwitchApplication.Nasoka.DetailsClass d)
                {
                    return d.GetReferencedEntities<global::LightSwitchApplication.Student, global::LightSwitchApplication.Student.DetailsClass>(global::LightSwitchApplication.Nasoka.DetailsClass.PropertySetProperties.Students, ref d._Students);
                }
                private static global::System.Collections.IEnumerable _Students_GetEntityCollection(global::LightSwitchApplication.Nasoka.DetailsClass d)
                {
                    return d.ImplementationEntity.Students;
                }
    
            }
    
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Nasoka, global::LightSwitchApplication.Nasoka.DetailsClass, int>.Data _ID_Nasoka;
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Nasoka, global::LightSwitchApplication.Nasoka.DetailsClass, string>.Data _Nasok;
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityCollectionProperty<global::LightSwitchApplication.Nasoka, global::LightSwitchApplication.Nasoka.DetailsClass, global::LightSwitchApplication.Predmet>.Data _Predmets;
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityCollectionProperty<global::LightSwitchApplication.Nasoka, global::LightSwitchApplication.Nasoka.DetailsClass, global::LightSwitchApplication.Student>.Data _Students;
            
        }
    
        #endregion
    }
    
    #endregion
}
