

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LightSwitchApplication
{
    #region Entities
    
    /// <summary>
    /// No Modeled Description Available
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.1.0.0")]
    public sealed partial class TipNaAktivnost : global::Microsoft.LightSwitch.Framework.Base.EntityObject<global::LightSwitchApplication.TipNaAktivnost, global::LightSwitchApplication.TipNaAktivnost.DetailsClass>
    {
        #region Constructors
    
        /// <summary>
        /// Initializes a new instance of the TipNaAktivnost entity.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.1.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public TipNaAktivnost()
            : this(null)
        {
        }
    
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.1.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public TipNaAktivnost(global::Microsoft.LightSwitch.Framework.EntitySet<global::LightSwitchApplication.TipNaAktivnost> entitySet)
            : base(entitySet)
        {
            global::LightSwitchApplication.TipNaAktivnost.DetailsClass.Initialize(this);
        }
    
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void TipNaAktivnost_Created();
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void TipNaAktivnost_AllowSaveWithErrors(ref bool result);
    
        #endregion
    
        #region Private Properties
        
        /// <summary>
        /// Gets the Application object for this application.  The Application object provides access to active screens, methods to open screens and access to the current user.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.1.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::Microsoft.LightSwitch.IApplication<global::LightSwitchApplication.DataWorkspace> Application
        {
            get
            {
                return (global::Microsoft.LightSwitch.IApplication<global::LightSwitchApplication.DataWorkspace>)global::LightSwitchApplication.Application.Current;
            }
        }
        
        /// <summary>
        /// Gets the containing data workspace.  The data workspace provides access to all data sources in the application.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.1.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::LightSwitchApplication.DataWorkspace DataWorkspace
        {
            get
            {
                return (global::LightSwitchApplication.DataWorkspace)this.Details.EntitySet.Details.DataService.Details.DataWorkspace;
            }
        }
        
        #endregion
    
        #region Public Properties
    
        /// <summary>
        /// No Modeled Description Available
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.1.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public string Ime
        {
            get
            {
                return global::LightSwitchApplication.TipNaAktivnost.DetailsClass.GetValue(this, global::LightSwitchApplication.TipNaAktivnost.DetailsClass.PropertySetProperties.Ime);
            }
            set
            {
                global::LightSwitchApplication.TipNaAktivnost.DetailsClass.SetValue(this, global::LightSwitchApplication.TipNaAktivnost.DetailsClass.PropertySetProperties.Ime, value);
            }
        }
        
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Ime_IsReadOnly(ref bool result);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Ime_Validate(global::Microsoft.LightSwitch.EntityValidationResultsBuilder results);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Ime_Changed();

        /// <summary>
        /// No Modeled Description Available
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.1.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public int ID_tipNaAktivnost
        {
            get
            {
                return global::LightSwitchApplication.TipNaAktivnost.DetailsClass.GetValue(this, global::LightSwitchApplication.TipNaAktivnost.DetailsClass.PropertySetProperties.ID_tipNaAktivnost);
            }
        }
        
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void ID_tipNaAktivnost_IsReadOnly(ref bool result);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void ID_tipNaAktivnost_Validate(global::Microsoft.LightSwitch.EntityValidationResultsBuilder results);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void ID_tipNaAktivnost_Changed();

        /// <summary>
        /// No Modeled Description Available
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.1.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::Microsoft.LightSwitch.Framework.EntityCollection<global::LightSwitchApplication.Aktivnost> Aktivnosts
        {
            get
            {
                return global::LightSwitchApplication.TipNaAktivnost.DetailsClass.GetValue(this, global::LightSwitchApplication.TipNaAktivnost.DetailsClass.PropertySetProperties.Aktivnosts);
            }
        }
        
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.1.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public Microsoft.LightSwitch.IDataServiceQueryable<global::LightSwitchApplication.Aktivnost> AktivnostsQuery
        {
            get
            {
                return global::LightSwitchApplication.TipNaAktivnost.DetailsClass.GetQuery(this, global::LightSwitchApplication.TipNaAktivnost.DetailsClass.PropertySetProperties.Aktivnosts);
            }
        }

        #endregion
    
        #region Details Class
    
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        [global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1034:NestedTypesShouldNotBeVisible")]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.1.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public sealed class DetailsClass : global::Microsoft.LightSwitch.Details.Framework.Base.EntityDetails<
                global::LightSwitchApplication.TipNaAktivnost,
                global::LightSwitchApplication.TipNaAktivnost.DetailsClass,
                global::LightSwitchApplication.TipNaAktivnost.DetailsClass.IImplementation,
                global::LightSwitchApplication.TipNaAktivnost.DetailsClass.PropertySet,
                global::Microsoft.LightSwitch.Details.Framework.EntityCommandSet<global::LightSwitchApplication.TipNaAktivnost, global::LightSwitchApplication.TipNaAktivnost.DetailsClass>,
                global::Microsoft.LightSwitch.Details.Framework.EntityMethodSet<global::LightSwitchApplication.TipNaAktivnost, global::LightSwitchApplication.TipNaAktivnost.DetailsClass>>
        {
    
            static DetailsClass()
            {
                var initializeEntry = global::LightSwitchApplication.TipNaAktivnost.DetailsClass.PropertySetProperties.Ime;
            }
    
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private static readonly global::Microsoft.LightSwitch.Details.Framework.Base.EntityDetails<global::LightSwitchApplication.TipNaAktivnost, global::LightSwitchApplication.TipNaAktivnost.DetailsClass>.Entry
                __TipNaAktivnostEntry = new global::Microsoft.LightSwitch.Details.Framework.Base.EntityDetails<global::LightSwitchApplication.TipNaAktivnost, global::LightSwitchApplication.TipNaAktivnost.DetailsClass>.Entry(
                    global::LightSwitchApplication.TipNaAktivnost.DetailsClass.__TipNaAktivnost_CreateNew,
                    global::LightSwitchApplication.TipNaAktivnost.DetailsClass.__TipNaAktivnost_Created,
                    global::LightSwitchApplication.TipNaAktivnost.DetailsClass.__TipNaAktivnost_AllowSaveWithErrors);
            private static global::LightSwitchApplication.TipNaAktivnost __TipNaAktivnost_CreateNew(global::Microsoft.LightSwitch.Framework.EntitySet<global::LightSwitchApplication.TipNaAktivnost> es)
            {
                return new global::LightSwitchApplication.TipNaAktivnost(es);
            }
            private static void __TipNaAktivnost_Created(global::LightSwitchApplication.TipNaAktivnost e)
            {
                e.TipNaAktivnost_Created();
            }
            private static bool __TipNaAktivnost_AllowSaveWithErrors(global::LightSwitchApplication.TipNaAktivnost e)
            {
                bool result = false;
                e.TipNaAktivnost_AllowSaveWithErrors(ref result);
                return result;
            }
    
            public DetailsClass() : base()
            {
            }
    
            public new global::Microsoft.LightSwitch.Details.Framework.EntityCommandSet<global::LightSwitchApplication.TipNaAktivnost, global::LightSwitchApplication.TipNaAktivnost.DetailsClass> Commands
            {
                get
                {
                    return base.Commands;
                }
            }
    
            public new global::Microsoft.LightSwitch.Details.Framework.EntityMethodSet<global::LightSwitchApplication.TipNaAktivnost, global::LightSwitchApplication.TipNaAktivnost.DetailsClass> Methods
            {
                get
                {
                    return base.Methods;
                }
            }
    
            public new global::LightSwitchApplication.TipNaAktivnost.DetailsClass.PropertySet Properties
            {
                get
                {
                    return base.Properties;
                }
            }
    
            [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
            [global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1034:NestedTypesShouldNotBeVisible")]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.1.0.0")]
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public sealed class PropertySet : global::Microsoft.LightSwitch.Details.Framework.Base.EntityPropertySet<global::LightSwitchApplication.TipNaAktivnost, global::LightSwitchApplication.TipNaAktivnost.DetailsClass>
            {
    
                public PropertySet() : base()
                {
                }
    
                public global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.TipNaAktivnost, global::LightSwitchApplication.TipNaAktivnost.DetailsClass, string> Ime
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.TipNaAktivnost.DetailsClass.PropertySetProperties.Ime) as global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.TipNaAktivnost, global::LightSwitchApplication.TipNaAktivnost.DetailsClass, string>;
                    }
                }
                
                public global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.TipNaAktivnost, global::LightSwitchApplication.TipNaAktivnost.DetailsClass, int> ID_tipNaAktivnost
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.TipNaAktivnost.DetailsClass.PropertySetProperties.ID_tipNaAktivnost) as global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.TipNaAktivnost, global::LightSwitchApplication.TipNaAktivnost.DetailsClass, int>;
                    }
                }
                
                public global::Microsoft.LightSwitch.Details.Framework.EntityCollectionProperty<global::LightSwitchApplication.TipNaAktivnost, global::LightSwitchApplication.TipNaAktivnost.DetailsClass, global::LightSwitchApplication.Aktivnost> Aktivnosts
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.TipNaAktivnost.DetailsClass.PropertySetProperties.Aktivnosts) as global::Microsoft.LightSwitch.Details.Framework.EntityCollectionProperty<global::LightSwitchApplication.TipNaAktivnost, global::LightSwitchApplication.TipNaAktivnost.DetailsClass, global::LightSwitchApplication.Aktivnost>;
                    }
                }
                
            }
    
            #pragma warning disable 109
            [global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1034:NestedTypesShouldNotBeVisible")]
            public interface IImplementation : global::Microsoft.LightSwitch.Internal.IEntityImplementation
            {
                new string Ime { get; set; }
                new int ID_tipNaAktivnost { get; }
                new global::System.Collections.IEnumerable Aktivnosts { get; }
            }
            #pragma warning restore 109
    
            [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.1.0.0")]
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            internal class PropertySetProperties
            {
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.TipNaAktivnost, global::LightSwitchApplication.TipNaAktivnost.DetailsClass, string>.Entry
                    Ime = new global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.TipNaAktivnost, global::LightSwitchApplication.TipNaAktivnost.DetailsClass, string>.Entry(
                        "Ime",
                        global::LightSwitchApplication.TipNaAktivnost.DetailsClass.PropertySetProperties._Ime_Stub,
                        global::LightSwitchApplication.TipNaAktivnost.DetailsClass.PropertySetProperties._Ime_ComputeIsReadOnly,
                        global::LightSwitchApplication.TipNaAktivnost.DetailsClass.PropertySetProperties._Ime_Validate,
                        global::LightSwitchApplication.TipNaAktivnost.DetailsClass.PropertySetProperties._Ime_GetImplementationValue,
                        global::LightSwitchApplication.TipNaAktivnost.DetailsClass.PropertySetProperties._Ime_SetImplementationValue,
                        global::LightSwitchApplication.TipNaAktivnost.DetailsClass.PropertySetProperties._Ime_OnValueChanged);
                private static void _Ime_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.TipNaAktivnost.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.TipNaAktivnost, global::LightSwitchApplication.TipNaAktivnost.DetailsClass, string>.Data> c, global::LightSwitchApplication.TipNaAktivnost.DetailsClass d, object sf)
                {
                    c(d, ref d._Ime, sf);
                }
                private static bool _Ime_ComputeIsReadOnly(global::LightSwitchApplication.TipNaAktivnost e)
                {
                    bool result = false;
                    e.Ime_IsReadOnly(ref result);
                    return result;
                }
                private static void _Ime_Validate(global::LightSwitchApplication.TipNaAktivnost e, global::Microsoft.LightSwitch.EntityValidationResultsBuilder r)
                {
                    e.Ime_Validate(r);
                }
                private static string _Ime_GetImplementationValue(global::LightSwitchApplication.TipNaAktivnost.DetailsClass d)
                {
                    return d.ImplementationEntity.Ime;
                }
                private static void _Ime_SetImplementationValue(global::LightSwitchApplication.TipNaAktivnost.DetailsClass d, string v)
                {
                    d.ImplementationEntity.Ime = v;
                }
                private static void _Ime_OnValueChanged(global::LightSwitchApplication.TipNaAktivnost e)
                {
                    e.Ime_Changed();
                }
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.TipNaAktivnost, global::LightSwitchApplication.TipNaAktivnost.DetailsClass, int>.Entry
                    ID_tipNaAktivnost = new global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.TipNaAktivnost, global::LightSwitchApplication.TipNaAktivnost.DetailsClass, int>.Entry(
                        "ID_tipNaAktivnost",
                        global::LightSwitchApplication.TipNaAktivnost.DetailsClass.PropertySetProperties._ID_tipNaAktivnost_Stub,
                        global::LightSwitchApplication.TipNaAktivnost.DetailsClass.PropertySetProperties._ID_tipNaAktivnost_ComputeIsReadOnly,
                        global::LightSwitchApplication.TipNaAktivnost.DetailsClass.PropertySetProperties._ID_tipNaAktivnost_Validate,
                        global::LightSwitchApplication.TipNaAktivnost.DetailsClass.PropertySetProperties._ID_tipNaAktivnost_GetImplementationValue,
                        null,
                        global::LightSwitchApplication.TipNaAktivnost.DetailsClass.PropertySetProperties._ID_tipNaAktivnost_OnValueChanged);
                private static void _ID_tipNaAktivnost_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.TipNaAktivnost.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.TipNaAktivnost, global::LightSwitchApplication.TipNaAktivnost.DetailsClass, int>.Data> c, global::LightSwitchApplication.TipNaAktivnost.DetailsClass d, object sf)
                {
                    c(d, ref d._ID_tipNaAktivnost, sf);
                }
                private static bool _ID_tipNaAktivnost_ComputeIsReadOnly(global::LightSwitchApplication.TipNaAktivnost e)
                {
                    bool result = false;
                    e.ID_tipNaAktivnost_IsReadOnly(ref result);
                    return result;
                }
                private static void _ID_tipNaAktivnost_Validate(global::LightSwitchApplication.TipNaAktivnost e, global::Microsoft.LightSwitch.EntityValidationResultsBuilder r)
                {
                    e.ID_tipNaAktivnost_Validate(r);
                }
                private static int _ID_tipNaAktivnost_GetImplementationValue(global::LightSwitchApplication.TipNaAktivnost.DetailsClass d)
                {
                    return d.ImplementationEntity.ID_tipNaAktivnost;
                }
                private static void _ID_tipNaAktivnost_OnValueChanged(global::LightSwitchApplication.TipNaAktivnost e)
                {
                    e.ID_tipNaAktivnost_Changed();
                }
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityCollectionProperty<global::LightSwitchApplication.TipNaAktivnost, global::LightSwitchApplication.TipNaAktivnost.DetailsClass, global::LightSwitchApplication.Aktivnost>.Entry
                    Aktivnosts = new global::Microsoft.LightSwitch.Details.Framework.EntityCollectionProperty<global::LightSwitchApplication.TipNaAktivnost, global::LightSwitchApplication.TipNaAktivnost.DetailsClass, global::LightSwitchApplication.Aktivnost>.Entry(
                        "Aktivnosts",
                        global::LightSwitchApplication.TipNaAktivnost.DetailsClass.PropertySetProperties._Aktivnosts_Stub,
                        global::LightSwitchApplication.TipNaAktivnost.DetailsClass.PropertySetProperties._Aktivnosts_GetReferencedEntities,
                        global::LightSwitchApplication.TipNaAktivnost.DetailsClass.PropertySetProperties._Aktivnosts_GetEntityCollection);
                private static void _Aktivnosts_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.TipNaAktivnost.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityCollectionProperty<global::LightSwitchApplication.TipNaAktivnost, global::LightSwitchApplication.TipNaAktivnost.DetailsClass, global::LightSwitchApplication.Aktivnost>.Data> c, global::LightSwitchApplication.TipNaAktivnost.DetailsClass d, object sf)
                {
                    c(d, ref d._Aktivnosts, sf);
                }
                private static global::System.Collections.Generic.IEnumerable<global::LightSwitchApplication.Aktivnost> _Aktivnosts_GetReferencedEntities(global::LightSwitchApplication.TipNaAktivnost.DetailsClass d)
                {
                    return d.GetReferencedEntities<global::LightSwitchApplication.Aktivnost, global::LightSwitchApplication.Aktivnost.DetailsClass>(global::LightSwitchApplication.TipNaAktivnost.DetailsClass.PropertySetProperties.Aktivnosts, ref d._Aktivnosts);
                }
                private static global::System.Collections.IEnumerable _Aktivnosts_GetEntityCollection(global::LightSwitchApplication.TipNaAktivnost.DetailsClass d)
                {
                    return d.ImplementationEntity.Aktivnosts;
                }
    
            }
    
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.TipNaAktivnost, global::LightSwitchApplication.TipNaAktivnost.DetailsClass, string>.Data _Ime;
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.TipNaAktivnost, global::LightSwitchApplication.TipNaAktivnost.DetailsClass, int>.Data _ID_tipNaAktivnost;
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityCollectionProperty<global::LightSwitchApplication.TipNaAktivnost, global::LightSwitchApplication.TipNaAktivnost.DetailsClass, global::LightSwitchApplication.Aktivnost>.Data _Aktivnosts;
            
        }
    
        #endregion
    }
    
    #endregion
}
