

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LightSwitchApplication
{
    #region Entities
    
    /// <summary>
    /// No Modeled Description Available
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.1.0.0")]
    public sealed partial class Student : global::Microsoft.LightSwitch.Framework.Base.EntityObject<global::LightSwitchApplication.Student, global::LightSwitchApplication.Student.DetailsClass>
    {
        #region Constructors
    
        /// <summary>
        /// Initializes a new instance of the Student entity.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.1.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public Student()
            : this(null)
        {
        }
    
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.1.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public Student(global::Microsoft.LightSwitch.Framework.EntitySet<global::LightSwitchApplication.Student> entitySet)
            : base(entitySet)
        {
            global::LightSwitchApplication.Student.DetailsClass.Initialize(this);
        }
    
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Student_Created();
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Student_AllowSaveWithErrors(ref bool result);
    
        #endregion
    
        #region Private Properties
        
        /// <summary>
        /// Gets the Application object for this application.  The Application object provides access to active screens, methods to open screens and access to the current user.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.1.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::Microsoft.LightSwitch.IApplication<global::LightSwitchApplication.DataWorkspace> Application
        {
            get
            {
                return (global::Microsoft.LightSwitch.IApplication<global::LightSwitchApplication.DataWorkspace>)global::LightSwitchApplication.Application.Current;
            }
        }
        
        /// <summary>
        /// Gets the containing data workspace.  The data workspace provides access to all data sources in the application.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.1.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::LightSwitchApplication.DataWorkspace DataWorkspace
        {
            get
            {
                return (global::LightSwitchApplication.DataWorkspace)this.Details.EntitySet.Details.DataService.Details.DataWorkspace;
            }
        }
        
        #endregion
    
        #region Public Properties
    
        /// <summary>
        /// No Modeled Description Available
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.1.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public string Br_indeks
        {
            get
            {
                return global::LightSwitchApplication.Student.DetailsClass.GetValue(this, global::LightSwitchApplication.Student.DetailsClass.PropertySetProperties.Br_indeks);
            }
            set
            {
                global::LightSwitchApplication.Student.DetailsClass.SetValue(this, global::LightSwitchApplication.Student.DetailsClass.PropertySetProperties.Br_indeks, value);
            }
        }
        
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Br_indeks_IsReadOnly(ref bool result);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Br_indeks_Validate(global::Microsoft.LightSwitch.EntityValidationResultsBuilder results);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Br_indeks_Changed();

        /// <summary>
        /// No Modeled Description Available
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.1.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public string Ime
        {
            get
            {
                return global::LightSwitchApplication.Student.DetailsClass.GetValue(this, global::LightSwitchApplication.Student.DetailsClass.PropertySetProperties.Ime);
            }
            set
            {
                global::LightSwitchApplication.Student.DetailsClass.SetValue(this, global::LightSwitchApplication.Student.DetailsClass.PropertySetProperties.Ime, value);
            }
        }
        
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Ime_IsReadOnly(ref bool result);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Ime_Validate(global::Microsoft.LightSwitch.EntityValidationResultsBuilder results);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Ime_Changed();

        /// <summary>
        /// No Modeled Description Available
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.1.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public string Prezime
        {
            get
            {
                return global::LightSwitchApplication.Student.DetailsClass.GetValue(this, global::LightSwitchApplication.Student.DetailsClass.PropertySetProperties.Prezime);
            }
            set
            {
                global::LightSwitchApplication.Student.DetailsClass.SetValue(this, global::LightSwitchApplication.Student.DetailsClass.PropertySetProperties.Prezime, value);
            }
        }
        
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Prezime_IsReadOnly(ref bool result);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Prezime_Validate(global::Microsoft.LightSwitch.EntityValidationResultsBuilder results);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Prezime_Changed();

        /// <summary>
        /// No Modeled Description Available
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.1.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public string Nasoka
        {
            get
            {
                return global::LightSwitchApplication.Student.DetailsClass.GetValue(this, global::LightSwitchApplication.Student.DetailsClass.PropertySetProperties.Nasoka);
            }
            set
            {
                global::LightSwitchApplication.Student.DetailsClass.SetValue(this, global::LightSwitchApplication.Student.DetailsClass.PropertySetProperties.Nasoka, value);
            }
        }
        
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Nasoka_IsReadOnly(ref bool result);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Nasoka_Validate(global::Microsoft.LightSwitch.EntityValidationResultsBuilder results);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Nasoka_Changed();

        /// <summary>
        /// No Modeled Description Available
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.1.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public string Email
        {
            get
            {
                return global::LightSwitchApplication.Student.DetailsClass.GetValue(this, global::LightSwitchApplication.Student.DetailsClass.PropertySetProperties.Email);
            }
            set
            {
                global::LightSwitchApplication.Student.DetailsClass.SetValue(this, global::LightSwitchApplication.Student.DetailsClass.PropertySetProperties.Email, value);
            }
        }
        
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Email_IsReadOnly(ref bool result);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Email_Validate(global::Microsoft.LightSwitch.EntityValidationResultsBuilder results);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Email_Changed();

        /// <summary>
        /// No Modeled Description Available
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.1.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public string Lozinka
        {
            get
            {
                return global::LightSwitchApplication.Student.DetailsClass.GetValue(this, global::LightSwitchApplication.Student.DetailsClass.PropertySetProperties.Lozinka);
            }
            set
            {
                global::LightSwitchApplication.Student.DetailsClass.SetValue(this, global::LightSwitchApplication.Student.DetailsClass.PropertySetProperties.Lozinka, value);
            }
        }
        
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Lozinka_IsReadOnly(ref bool result);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Lozinka_Validate(global::Microsoft.LightSwitch.EntityValidationResultsBuilder results);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Lozinka_Changed();

        /// <summary>
        /// No Modeled Description Available
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.1.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.Nullable<bool> ActiveStudent
        {
            get
            {
                return global::LightSwitchApplication.Student.DetailsClass.GetValue(this, global::LightSwitchApplication.Student.DetailsClass.PropertySetProperties.ActiveStudent);
            }
            set
            {
                global::LightSwitchApplication.Student.DetailsClass.SetValue(this, global::LightSwitchApplication.Student.DetailsClass.PropertySetProperties.ActiveStudent, value);
            }
        }
        
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void ActiveStudent_IsReadOnly(ref bool result);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void ActiveStudent_Validate(global::Microsoft.LightSwitch.EntityValidationResultsBuilder results);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void ActiveStudent_Changed();

        /// <summary>
        /// No Modeled Description Available
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.1.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::Microsoft.LightSwitch.Framework.EntityCollection<global::LightSwitchApplication.Izbrani_predmeti> Izbrani_predmetis
        {
            get
            {
                return global::LightSwitchApplication.Student.DetailsClass.GetValue(this, global::LightSwitchApplication.Student.DetailsClass.PropertySetProperties.Izbrani_predmetis);
            }
        }
        
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.1.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public Microsoft.LightSwitch.IDataServiceQueryable<global::LightSwitchApplication.Izbrani_predmeti> Izbrani_predmetisQuery
        {
            get
            {
                return global::LightSwitchApplication.Student.DetailsClass.GetQuery(this, global::LightSwitchApplication.Student.DetailsClass.PropertySetProperties.Izbrani_predmetis);
            }
        }

        /// <summary>
        /// No Modeled Description Available
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.1.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::LightSwitchApplication.Semestar Semestar
        {
            get
            {
                return global::LightSwitchApplication.Student.DetailsClass.GetValue(this, global::LightSwitchApplication.Student.DetailsClass.PropertySetProperties.Semestar);
            }
            set
            {
                global::LightSwitchApplication.Student.DetailsClass.SetValue(this, global::LightSwitchApplication.Student.DetailsClass.PropertySetProperties.Semestar, value);
            }
        }
        
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Semestar_IsReadOnly(ref bool result);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Semestar_Validate(global::Microsoft.LightSwitch.EntityValidationResultsBuilder results);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Semestar_Changed();

        #endregion
    
        #region Details Class
    
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        [global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1034:NestedTypesShouldNotBeVisible")]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.1.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public sealed class DetailsClass : global::Microsoft.LightSwitch.Details.Framework.Base.EntityDetails<
                global::LightSwitchApplication.Student,
                global::LightSwitchApplication.Student.DetailsClass,
                global::LightSwitchApplication.Student.DetailsClass.IImplementation,
                global::LightSwitchApplication.Student.DetailsClass.PropertySet,
                global::Microsoft.LightSwitch.Details.Framework.EntityCommandSet<global::LightSwitchApplication.Student, global::LightSwitchApplication.Student.DetailsClass>,
                global::Microsoft.LightSwitch.Details.Framework.EntityMethodSet<global::LightSwitchApplication.Student, global::LightSwitchApplication.Student.DetailsClass>>
        {
    
            static DetailsClass()
            {
                var initializeEntry = global::LightSwitchApplication.Student.DetailsClass.PropertySetProperties.Br_indeks;
            }
    
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private static readonly global::Microsoft.LightSwitch.Details.Framework.Base.EntityDetails<global::LightSwitchApplication.Student, global::LightSwitchApplication.Student.DetailsClass>.Entry
                __StudentEntry = new global::Microsoft.LightSwitch.Details.Framework.Base.EntityDetails<global::LightSwitchApplication.Student, global::LightSwitchApplication.Student.DetailsClass>.Entry(
                    global::LightSwitchApplication.Student.DetailsClass.__Student_CreateNew,
                    global::LightSwitchApplication.Student.DetailsClass.__Student_Created,
                    global::LightSwitchApplication.Student.DetailsClass.__Student_AllowSaveWithErrors);
            private static global::LightSwitchApplication.Student __Student_CreateNew(global::Microsoft.LightSwitch.Framework.EntitySet<global::LightSwitchApplication.Student> es)
            {
                return new global::LightSwitchApplication.Student(es);
            }
            private static void __Student_Created(global::LightSwitchApplication.Student e)
            {
                e.Student_Created();
            }
            private static bool __Student_AllowSaveWithErrors(global::LightSwitchApplication.Student e)
            {
                bool result = false;
                e.Student_AllowSaveWithErrors(ref result);
                return result;
            }
    
            public DetailsClass() : base()
            {
            }
    
            public new global::Microsoft.LightSwitch.Details.Framework.EntityCommandSet<global::LightSwitchApplication.Student, global::LightSwitchApplication.Student.DetailsClass> Commands
            {
                get
                {
                    return base.Commands;
                }
            }
    
            public new global::Microsoft.LightSwitch.Details.Framework.EntityMethodSet<global::LightSwitchApplication.Student, global::LightSwitchApplication.Student.DetailsClass> Methods
            {
                get
                {
                    return base.Methods;
                }
            }
    
            public new global::LightSwitchApplication.Student.DetailsClass.PropertySet Properties
            {
                get
                {
                    return base.Properties;
                }
            }
    
            [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
            [global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1034:NestedTypesShouldNotBeVisible")]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.1.0.0")]
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public sealed class PropertySet : global::Microsoft.LightSwitch.Details.Framework.Base.EntityPropertySet<global::LightSwitchApplication.Student, global::LightSwitchApplication.Student.DetailsClass>
            {
    
                public PropertySet() : base()
                {
                }
    
                public global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Student, global::LightSwitchApplication.Student.DetailsClass, string> Br_indeks
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.Student.DetailsClass.PropertySetProperties.Br_indeks) as global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Student, global::LightSwitchApplication.Student.DetailsClass, string>;
                    }
                }
                
                public global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Student, global::LightSwitchApplication.Student.DetailsClass, string> Ime
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.Student.DetailsClass.PropertySetProperties.Ime) as global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Student, global::LightSwitchApplication.Student.DetailsClass, string>;
                    }
                }
                
                public global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Student, global::LightSwitchApplication.Student.DetailsClass, string> Prezime
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.Student.DetailsClass.PropertySetProperties.Prezime) as global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Student, global::LightSwitchApplication.Student.DetailsClass, string>;
                    }
                }
                
                public global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Student, global::LightSwitchApplication.Student.DetailsClass, string> Nasoka
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.Student.DetailsClass.PropertySetProperties.Nasoka) as global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Student, global::LightSwitchApplication.Student.DetailsClass, string>;
                    }
                }
                
                public global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Student, global::LightSwitchApplication.Student.DetailsClass, string> Email
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.Student.DetailsClass.PropertySetProperties.Email) as global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Student, global::LightSwitchApplication.Student.DetailsClass, string>;
                    }
                }
                
                public global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Student, global::LightSwitchApplication.Student.DetailsClass, string> Lozinka
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.Student.DetailsClass.PropertySetProperties.Lozinka) as global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Student, global::LightSwitchApplication.Student.DetailsClass, string>;
                    }
                }
                
                public global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Student, global::LightSwitchApplication.Student.DetailsClass, global::System.Nullable<bool>> ActiveStudent
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.Student.DetailsClass.PropertySetProperties.ActiveStudent) as global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Student, global::LightSwitchApplication.Student.DetailsClass, global::System.Nullable<bool>>;
                    }
                }
                
                public global::Microsoft.LightSwitch.Details.Framework.EntityCollectionProperty<global::LightSwitchApplication.Student, global::LightSwitchApplication.Student.DetailsClass, global::LightSwitchApplication.Izbrani_predmeti> Izbrani_predmetis
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.Student.DetailsClass.PropertySetProperties.Izbrani_predmetis) as global::Microsoft.LightSwitch.Details.Framework.EntityCollectionProperty<global::LightSwitchApplication.Student, global::LightSwitchApplication.Student.DetailsClass, global::LightSwitchApplication.Izbrani_predmeti>;
                    }
                }
                
                public global::Microsoft.LightSwitch.Details.Framework.EntityReferenceProperty<global::LightSwitchApplication.Student, global::LightSwitchApplication.Student.DetailsClass, global::LightSwitchApplication.Semestar> Semestar
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.Student.DetailsClass.PropertySetProperties.Semestar) as global::Microsoft.LightSwitch.Details.Framework.EntityReferenceProperty<global::LightSwitchApplication.Student, global::LightSwitchApplication.Student.DetailsClass, global::LightSwitchApplication.Semestar>;
                    }
                }
                
            }
    
            #pragma warning disable 109
            [global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1034:NestedTypesShouldNotBeVisible")]
            public interface IImplementation : global::Microsoft.LightSwitch.Internal.IEntityImplementation
            {
                new string Br_indeks { get; set; }
                new string Ime { get; set; }
                new string Prezime { get; set; }
                new string Nasoka { get; set; }
                new string Email { get; set; }
                new string Lozinka { get; set; }
                new global::System.Nullable<bool> ActiveStudent { get; set; }
                new global::System.Collections.IEnumerable Izbrani_predmetis { get; }
                new global::Microsoft.LightSwitch.Internal.IEntityImplementation Semestar { get; set; }
            }
            #pragma warning restore 109
    
            [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.1.0.0")]
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            internal class PropertySetProperties
            {
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Student, global::LightSwitchApplication.Student.DetailsClass, string>.Entry
                    Br_indeks = new global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Student, global::LightSwitchApplication.Student.DetailsClass, string>.Entry(
                        "Br_indeks",
                        global::LightSwitchApplication.Student.DetailsClass.PropertySetProperties._Br_indeks_Stub,
                        global::LightSwitchApplication.Student.DetailsClass.PropertySetProperties._Br_indeks_ComputeIsReadOnly,
                        global::LightSwitchApplication.Student.DetailsClass.PropertySetProperties._Br_indeks_Validate,
                        global::LightSwitchApplication.Student.DetailsClass.PropertySetProperties._Br_indeks_GetImplementationValue,
                        global::LightSwitchApplication.Student.DetailsClass.PropertySetProperties._Br_indeks_SetImplementationValue,
                        global::LightSwitchApplication.Student.DetailsClass.PropertySetProperties._Br_indeks_OnValueChanged);
                private static void _Br_indeks_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.Student.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Student, global::LightSwitchApplication.Student.DetailsClass, string>.Data> c, global::LightSwitchApplication.Student.DetailsClass d, object sf)
                {
                    c(d, ref d._Br_indeks, sf);
                }
                private static bool _Br_indeks_ComputeIsReadOnly(global::LightSwitchApplication.Student e)
                {
                    bool result = false;
                    e.Br_indeks_IsReadOnly(ref result);
                    return result;
                }
                private static void _Br_indeks_Validate(global::LightSwitchApplication.Student e, global::Microsoft.LightSwitch.EntityValidationResultsBuilder r)
                {
                    e.Br_indeks_Validate(r);
                }
                private static string _Br_indeks_GetImplementationValue(global::LightSwitchApplication.Student.DetailsClass d)
                {
                    return d.ImplementationEntity.Br_indeks;
                }
                private static void _Br_indeks_SetImplementationValue(global::LightSwitchApplication.Student.DetailsClass d, string v)
                {
                    d.ImplementationEntity.Br_indeks = v;
                }
                private static void _Br_indeks_OnValueChanged(global::LightSwitchApplication.Student e)
                {
                    e.Br_indeks_Changed();
                }
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Student, global::LightSwitchApplication.Student.DetailsClass, string>.Entry
                    Ime = new global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Student, global::LightSwitchApplication.Student.DetailsClass, string>.Entry(
                        "Ime",
                        global::LightSwitchApplication.Student.DetailsClass.PropertySetProperties._Ime_Stub,
                        global::LightSwitchApplication.Student.DetailsClass.PropertySetProperties._Ime_ComputeIsReadOnly,
                        global::LightSwitchApplication.Student.DetailsClass.PropertySetProperties._Ime_Validate,
                        global::LightSwitchApplication.Student.DetailsClass.PropertySetProperties._Ime_GetImplementationValue,
                        global::LightSwitchApplication.Student.DetailsClass.PropertySetProperties._Ime_SetImplementationValue,
                        global::LightSwitchApplication.Student.DetailsClass.PropertySetProperties._Ime_OnValueChanged);
                private static void _Ime_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.Student.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Student, global::LightSwitchApplication.Student.DetailsClass, string>.Data> c, global::LightSwitchApplication.Student.DetailsClass d, object sf)
                {
                    c(d, ref d._Ime, sf);
                }
                private static bool _Ime_ComputeIsReadOnly(global::LightSwitchApplication.Student e)
                {
                    bool result = false;
                    e.Ime_IsReadOnly(ref result);
                    return result;
                }
                private static void _Ime_Validate(global::LightSwitchApplication.Student e, global::Microsoft.LightSwitch.EntityValidationResultsBuilder r)
                {
                    e.Ime_Validate(r);
                }
                private static string _Ime_GetImplementationValue(global::LightSwitchApplication.Student.DetailsClass d)
                {
                    return d.ImplementationEntity.Ime;
                }
                private static void _Ime_SetImplementationValue(global::LightSwitchApplication.Student.DetailsClass d, string v)
                {
                    d.ImplementationEntity.Ime = v;
                }
                private static void _Ime_OnValueChanged(global::LightSwitchApplication.Student e)
                {
                    e.Ime_Changed();
                }
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Student, global::LightSwitchApplication.Student.DetailsClass, string>.Entry
                    Prezime = new global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Student, global::LightSwitchApplication.Student.DetailsClass, string>.Entry(
                        "Prezime",
                        global::LightSwitchApplication.Student.DetailsClass.PropertySetProperties._Prezime_Stub,
                        global::LightSwitchApplication.Student.DetailsClass.PropertySetProperties._Prezime_ComputeIsReadOnly,
                        global::LightSwitchApplication.Student.DetailsClass.PropertySetProperties._Prezime_Validate,
                        global::LightSwitchApplication.Student.DetailsClass.PropertySetProperties._Prezime_GetImplementationValue,
                        global::LightSwitchApplication.Student.DetailsClass.PropertySetProperties._Prezime_SetImplementationValue,
                        global::LightSwitchApplication.Student.DetailsClass.PropertySetProperties._Prezime_OnValueChanged);
                private static void _Prezime_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.Student.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Student, global::LightSwitchApplication.Student.DetailsClass, string>.Data> c, global::LightSwitchApplication.Student.DetailsClass d, object sf)
                {
                    c(d, ref d._Prezime, sf);
                }
                private static bool _Prezime_ComputeIsReadOnly(global::LightSwitchApplication.Student e)
                {
                    bool result = false;
                    e.Prezime_IsReadOnly(ref result);
                    return result;
                }
                private static void _Prezime_Validate(global::LightSwitchApplication.Student e, global::Microsoft.LightSwitch.EntityValidationResultsBuilder r)
                {
                    e.Prezime_Validate(r);
                }
                private static string _Prezime_GetImplementationValue(global::LightSwitchApplication.Student.DetailsClass d)
                {
                    return d.ImplementationEntity.Prezime;
                }
                private static void _Prezime_SetImplementationValue(global::LightSwitchApplication.Student.DetailsClass d, string v)
                {
                    d.ImplementationEntity.Prezime = v;
                }
                private static void _Prezime_OnValueChanged(global::LightSwitchApplication.Student e)
                {
                    e.Prezime_Changed();
                }
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Student, global::LightSwitchApplication.Student.DetailsClass, string>.Entry
                    Nasoka = new global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Student, global::LightSwitchApplication.Student.DetailsClass, string>.Entry(
                        "Nasoka",
                        global::LightSwitchApplication.Student.DetailsClass.PropertySetProperties._Nasoka_Stub,
                        global::LightSwitchApplication.Student.DetailsClass.PropertySetProperties._Nasoka_ComputeIsReadOnly,
                        global::LightSwitchApplication.Student.DetailsClass.PropertySetProperties._Nasoka_Validate,
                        global::LightSwitchApplication.Student.DetailsClass.PropertySetProperties._Nasoka_GetImplementationValue,
                        global::LightSwitchApplication.Student.DetailsClass.PropertySetProperties._Nasoka_SetImplementationValue,
                        global::LightSwitchApplication.Student.DetailsClass.PropertySetProperties._Nasoka_OnValueChanged);
                private static void _Nasoka_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.Student.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Student, global::LightSwitchApplication.Student.DetailsClass, string>.Data> c, global::LightSwitchApplication.Student.DetailsClass d, object sf)
                {
                    c(d, ref d._Nasoka, sf);
                }
                private static bool _Nasoka_ComputeIsReadOnly(global::LightSwitchApplication.Student e)
                {
                    bool result = false;
                    e.Nasoka_IsReadOnly(ref result);
                    return result;
                }
                private static void _Nasoka_Validate(global::LightSwitchApplication.Student e, global::Microsoft.LightSwitch.EntityValidationResultsBuilder r)
                {
                    e.Nasoka_Validate(r);
                }
                private static string _Nasoka_GetImplementationValue(global::LightSwitchApplication.Student.DetailsClass d)
                {
                    return d.ImplementationEntity.Nasoka;
                }
                private static void _Nasoka_SetImplementationValue(global::LightSwitchApplication.Student.DetailsClass d, string v)
                {
                    d.ImplementationEntity.Nasoka = v;
                }
                private static void _Nasoka_OnValueChanged(global::LightSwitchApplication.Student e)
                {
                    e.Nasoka_Changed();
                }
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Student, global::LightSwitchApplication.Student.DetailsClass, string>.Entry
                    Email = new global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Student, global::LightSwitchApplication.Student.DetailsClass, string>.Entry(
                        "Email",
                        global::LightSwitchApplication.Student.DetailsClass.PropertySetProperties._Email_Stub,
                        global::LightSwitchApplication.Student.DetailsClass.PropertySetProperties._Email_ComputeIsReadOnly,
                        global::LightSwitchApplication.Student.DetailsClass.PropertySetProperties._Email_Validate,
                        global::LightSwitchApplication.Student.DetailsClass.PropertySetProperties._Email_GetImplementationValue,
                        global::LightSwitchApplication.Student.DetailsClass.PropertySetProperties._Email_SetImplementationValue,
                        global::LightSwitchApplication.Student.DetailsClass.PropertySetProperties._Email_OnValueChanged);
                private static void _Email_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.Student.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Student, global::LightSwitchApplication.Student.DetailsClass, string>.Data> c, global::LightSwitchApplication.Student.DetailsClass d, object sf)
                {
                    c(d, ref d._Email, sf);
                }
                private static bool _Email_ComputeIsReadOnly(global::LightSwitchApplication.Student e)
                {
                    bool result = false;
                    e.Email_IsReadOnly(ref result);
                    return result;
                }
                private static void _Email_Validate(global::LightSwitchApplication.Student e, global::Microsoft.LightSwitch.EntityValidationResultsBuilder r)
                {
                    e.Email_Validate(r);
                }
                private static string _Email_GetImplementationValue(global::LightSwitchApplication.Student.DetailsClass d)
                {
                    return d.ImplementationEntity.Email;
                }
                private static void _Email_SetImplementationValue(global::LightSwitchApplication.Student.DetailsClass d, string v)
                {
                    d.ImplementationEntity.Email = v;
                }
                private static void _Email_OnValueChanged(global::LightSwitchApplication.Student e)
                {
                    e.Email_Changed();
                }
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Student, global::LightSwitchApplication.Student.DetailsClass, string>.Entry
                    Lozinka = new global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Student, global::LightSwitchApplication.Student.DetailsClass, string>.Entry(
                        "Lozinka",
                        global::LightSwitchApplication.Student.DetailsClass.PropertySetProperties._Lozinka_Stub,
                        global::LightSwitchApplication.Student.DetailsClass.PropertySetProperties._Lozinka_ComputeIsReadOnly,
                        global::LightSwitchApplication.Student.DetailsClass.PropertySetProperties._Lozinka_Validate,
                        global::LightSwitchApplication.Student.DetailsClass.PropertySetProperties._Lozinka_GetImplementationValue,
                        global::LightSwitchApplication.Student.DetailsClass.PropertySetProperties._Lozinka_SetImplementationValue,
                        global::LightSwitchApplication.Student.DetailsClass.PropertySetProperties._Lozinka_OnValueChanged);
                private static void _Lozinka_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.Student.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Student, global::LightSwitchApplication.Student.DetailsClass, string>.Data> c, global::LightSwitchApplication.Student.DetailsClass d, object sf)
                {
                    c(d, ref d._Lozinka, sf);
                }
                private static bool _Lozinka_ComputeIsReadOnly(global::LightSwitchApplication.Student e)
                {
                    bool result = false;
                    e.Lozinka_IsReadOnly(ref result);
                    return result;
                }
                private static void _Lozinka_Validate(global::LightSwitchApplication.Student e, global::Microsoft.LightSwitch.EntityValidationResultsBuilder r)
                {
                    e.Lozinka_Validate(r);
                }
                private static string _Lozinka_GetImplementationValue(global::LightSwitchApplication.Student.DetailsClass d)
                {
                    return d.ImplementationEntity.Lozinka;
                }
                private static void _Lozinka_SetImplementationValue(global::LightSwitchApplication.Student.DetailsClass d, string v)
                {
                    d.ImplementationEntity.Lozinka = v;
                }
                private static void _Lozinka_OnValueChanged(global::LightSwitchApplication.Student e)
                {
                    e.Lozinka_Changed();
                }
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Student, global::LightSwitchApplication.Student.DetailsClass, global::System.Nullable<bool>>.Entry
                    ActiveStudent = new global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Student, global::LightSwitchApplication.Student.DetailsClass, global::System.Nullable<bool>>.Entry(
                        "ActiveStudent",
                        global::LightSwitchApplication.Student.DetailsClass.PropertySetProperties._ActiveStudent_Stub,
                        global::LightSwitchApplication.Student.DetailsClass.PropertySetProperties._ActiveStudent_ComputeIsReadOnly,
                        global::LightSwitchApplication.Student.DetailsClass.PropertySetProperties._ActiveStudent_Validate,
                        global::LightSwitchApplication.Student.DetailsClass.PropertySetProperties._ActiveStudent_GetImplementationValue,
                        global::LightSwitchApplication.Student.DetailsClass.PropertySetProperties._ActiveStudent_SetImplementationValue,
                        global::LightSwitchApplication.Student.DetailsClass.PropertySetProperties._ActiveStudent_OnValueChanged);
                private static void _ActiveStudent_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.Student.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Student, global::LightSwitchApplication.Student.DetailsClass, global::System.Nullable<bool>>.Data> c, global::LightSwitchApplication.Student.DetailsClass d, object sf)
                {
                    c(d, ref d._ActiveStudent, sf);
                }
                private static bool _ActiveStudent_ComputeIsReadOnly(global::LightSwitchApplication.Student e)
                {
                    bool result = false;
                    e.ActiveStudent_IsReadOnly(ref result);
                    return result;
                }
                private static void _ActiveStudent_Validate(global::LightSwitchApplication.Student e, global::Microsoft.LightSwitch.EntityValidationResultsBuilder r)
                {
                    e.ActiveStudent_Validate(r);
                }
                private static global::System.Nullable<bool> _ActiveStudent_GetImplementationValue(global::LightSwitchApplication.Student.DetailsClass d)
                {
                    return d.ImplementationEntity.ActiveStudent;
                }
                private static void _ActiveStudent_SetImplementationValue(global::LightSwitchApplication.Student.DetailsClass d, global::System.Nullable<bool> v)
                {
                    d.ImplementationEntity.ActiveStudent = v;
                }
                private static void _ActiveStudent_OnValueChanged(global::LightSwitchApplication.Student e)
                {
                    e.ActiveStudent_Changed();
                }
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityCollectionProperty<global::LightSwitchApplication.Student, global::LightSwitchApplication.Student.DetailsClass, global::LightSwitchApplication.Izbrani_predmeti>.Entry
                    Izbrani_predmetis = new global::Microsoft.LightSwitch.Details.Framework.EntityCollectionProperty<global::LightSwitchApplication.Student, global::LightSwitchApplication.Student.DetailsClass, global::LightSwitchApplication.Izbrani_predmeti>.Entry(
                        "Izbrani_predmetis",
                        global::LightSwitchApplication.Student.DetailsClass.PropertySetProperties._Izbrani_predmetis_Stub,
                        global::LightSwitchApplication.Student.DetailsClass.PropertySetProperties._Izbrani_predmetis_GetReferencedEntities,
                        global::LightSwitchApplication.Student.DetailsClass.PropertySetProperties._Izbrani_predmetis_GetEntityCollection);
                private static void _Izbrani_predmetis_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.Student.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityCollectionProperty<global::LightSwitchApplication.Student, global::LightSwitchApplication.Student.DetailsClass, global::LightSwitchApplication.Izbrani_predmeti>.Data> c, global::LightSwitchApplication.Student.DetailsClass d, object sf)
                {
                    c(d, ref d._Izbrani_predmetis, sf);
                }
                private static global::System.Collections.Generic.IEnumerable<global::LightSwitchApplication.Izbrani_predmeti> _Izbrani_predmetis_GetReferencedEntities(global::LightSwitchApplication.Student.DetailsClass d)
                {
                    return d.GetReferencedEntities<global::LightSwitchApplication.Izbrani_predmeti, global::LightSwitchApplication.Izbrani_predmeti.DetailsClass>(global::LightSwitchApplication.Student.DetailsClass.PropertySetProperties.Izbrani_predmetis, ref d._Izbrani_predmetis);
                }
                private static global::System.Collections.IEnumerable _Izbrani_predmetis_GetEntityCollection(global::LightSwitchApplication.Student.DetailsClass d)
                {
                    return d.ImplementationEntity.Izbrani_predmetis;
                }
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityReferenceProperty<global::LightSwitchApplication.Student, global::LightSwitchApplication.Student.DetailsClass, global::LightSwitchApplication.Semestar>.Entry
                    Semestar = new global::Microsoft.LightSwitch.Details.Framework.EntityReferenceProperty<global::LightSwitchApplication.Student, global::LightSwitchApplication.Student.DetailsClass, global::LightSwitchApplication.Semestar>.Entry(
                        "Semestar",
                        global::LightSwitchApplication.Student.DetailsClass.PropertySetProperties._Semestar_Stub,
                        global::LightSwitchApplication.Student.DetailsClass.PropertySetProperties._Semestar_ComputeIsReadOnly,
                        global::LightSwitchApplication.Student.DetailsClass.PropertySetProperties._Semestar_Validate,
                        global::LightSwitchApplication.Student.DetailsClass.PropertySetProperties._Semestar_GetCoreImplementationValue,
                        global::LightSwitchApplication.Student.DetailsClass.PropertySetProperties._Semestar_GetImplementationValue,
                        global::LightSwitchApplication.Student.DetailsClass.PropertySetProperties._Semestar_SetImplementationValue,
                        global::LightSwitchApplication.Student.DetailsClass.PropertySetProperties._Semestar_Refresh,
                        global::LightSwitchApplication.Student.DetailsClass.PropertySetProperties._Semestar_OnValueChanged);
                private static void _Semestar_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.Student.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityReferenceProperty<global::LightSwitchApplication.Student, global::LightSwitchApplication.Student.DetailsClass, global::LightSwitchApplication.Semestar>.Data> c, global::LightSwitchApplication.Student.DetailsClass d, object sf)
                {
                    c(d, ref d._Semestar, sf);
                }
                private static bool _Semestar_ComputeIsReadOnly(global::LightSwitchApplication.Student e)
                {
                    bool result = false;
                    e.Semestar_IsReadOnly(ref result);
                    return result;
                }
                private static void _Semestar_Validate(global::LightSwitchApplication.Student e, global::Microsoft.LightSwitch.EntityValidationResultsBuilder r)
                {
                    e.Semestar_Validate(r);
                }
                private static global::Microsoft.LightSwitch.Internal.IEntityImplementation _Semestar_GetCoreImplementationValue(global::LightSwitchApplication.Student.DetailsClass d)
                {
                    return d.ImplementationEntity.Semestar;
                }
                private static global::LightSwitchApplication.Semestar _Semestar_GetImplementationValue(global::LightSwitchApplication.Student.DetailsClass d)
                {
                    return d.GetImplementationValue<global::LightSwitchApplication.Semestar, global::LightSwitchApplication.Semestar.DetailsClass>(global::LightSwitchApplication.Student.DetailsClass.PropertySetProperties.Semestar, ref d._Semestar);
                }
                private static void _Semestar_SetImplementationValue(global::LightSwitchApplication.Student.DetailsClass d, global::LightSwitchApplication.Semestar v)
                {
                    d.SetImplementationValue(global::LightSwitchApplication.Student.DetailsClass.PropertySetProperties.Semestar, ref d._Semestar, (i, ev) => i.Semestar = ev, v);
                }
                private static void _Semestar_Refresh(global::LightSwitchApplication.Student.DetailsClass d)
                {
                    d.RefreshNavigationProperty(global::LightSwitchApplication.Student.DetailsClass.PropertySetProperties.Semestar, ref d._Semestar);
                }
                private static void _Semestar_OnValueChanged(global::LightSwitchApplication.Student e)
                {
                    e.Semestar_Changed();
                }
    
            }
    
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Student, global::LightSwitchApplication.Student.DetailsClass, string>.Data _Br_indeks;
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Student, global::LightSwitchApplication.Student.DetailsClass, string>.Data _Ime;
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Student, global::LightSwitchApplication.Student.DetailsClass, string>.Data _Prezime;
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Student, global::LightSwitchApplication.Student.DetailsClass, string>.Data _Nasoka;
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Student, global::LightSwitchApplication.Student.DetailsClass, string>.Data _Email;
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Student, global::LightSwitchApplication.Student.DetailsClass, string>.Data _Lozinka;
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Student, global::LightSwitchApplication.Student.DetailsClass, global::System.Nullable<bool>>.Data _ActiveStudent;
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityCollectionProperty<global::LightSwitchApplication.Student, global::LightSwitchApplication.Student.DetailsClass, global::LightSwitchApplication.Izbrani_predmeti>.Data _Izbrani_predmetis;
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityReferenceProperty<global::LightSwitchApplication.Student, global::LightSwitchApplication.Student.DetailsClass, global::LightSwitchApplication.Semestar>.Data _Semestar;
            
        }
    
        #endregion
    }
    
    #endregion
}
