

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LightSwitchApplication
{
    #region Entities
    
    /// <summary>
    /// No Modeled Description Available
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.1.0.0")]
    public sealed partial class Izbrani_predmeti : global::Microsoft.LightSwitch.Framework.Base.EntityObject<global::LightSwitchApplication.Izbrani_predmeti, global::LightSwitchApplication.Izbrani_predmeti.DetailsClass>
    {
        #region Constructors
    
        /// <summary>
        /// Initializes a new instance of the Izbrani_predmeti entity.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.1.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public Izbrani_predmeti()
            : this(null)
        {
        }
    
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.1.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public Izbrani_predmeti(global::Microsoft.LightSwitch.Framework.EntitySet<global::LightSwitchApplication.Izbrani_predmeti> entitySet)
            : base(entitySet)
        {
            global::LightSwitchApplication.Izbrani_predmeti.DetailsClass.Initialize(this);
        }
    
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Izbrani_predmeti_Created();
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Izbrani_predmeti_AllowSaveWithErrors(ref bool result);
    
        #endregion
    
        #region Private Properties
        
        /// <summary>
        /// Gets the Application object for this application.  The Application object provides access to active screens, methods to open screens and access to the current user.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.1.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::Microsoft.LightSwitch.IApplication<global::LightSwitchApplication.DataWorkspace> Application
        {
            get
            {
                return (global::Microsoft.LightSwitch.IApplication<global::LightSwitchApplication.DataWorkspace>)global::LightSwitchApplication.Application.Current;
            }
        }
        
        /// <summary>
        /// Gets the containing data workspace.  The data workspace provides access to all data sources in the application.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.1.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::LightSwitchApplication.DataWorkspace DataWorkspace
        {
            get
            {
                return (global::LightSwitchApplication.DataWorkspace)this.Details.EntitySet.Details.DataService.Details.DataWorkspace;
            }
        }
        
        #endregion
    
        #region Public Properties
    
        /// <summary>
        /// No Modeled Description Available
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.1.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public string tekoven_semestar
        {
            get
            {
                return global::LightSwitchApplication.Izbrani_predmeti.DetailsClass.GetValue(this, global::LightSwitchApplication.Izbrani_predmeti.DetailsClass.PropertySetProperties.tekoven_semestar);
            }
            set
            {
                global::LightSwitchApplication.Izbrani_predmeti.DetailsClass.SetValue(this, global::LightSwitchApplication.Izbrani_predmeti.DetailsClass.PropertySetProperties.tekoven_semestar, value);
            }
        }
        
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void tekoven_semestar_IsReadOnly(ref bool result);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void tekoven_semestar_Validate(global::Microsoft.LightSwitch.EntityValidationResultsBuilder results);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void tekoven_semestar_Changed();

        /// <summary>
        /// No Modeled Description Available
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.1.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public int ID_izbraniPredmeti
        {
            get
            {
                return global::LightSwitchApplication.Izbrani_predmeti.DetailsClass.GetValue(this, global::LightSwitchApplication.Izbrani_predmeti.DetailsClass.PropertySetProperties.ID_izbraniPredmeti);
            }
        }
        
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void ID_izbraniPredmeti_IsReadOnly(ref bool result);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void ID_izbraniPredmeti_Validate(global::Microsoft.LightSwitch.EntityValidationResultsBuilder results);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void ID_izbraniPredmeti_Changed();

        /// <summary>
        /// No Modeled Description Available
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.1.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::LightSwitchApplication.Predmet Predmet
        {
            get
            {
                return global::LightSwitchApplication.Izbrani_predmeti.DetailsClass.GetValue(this, global::LightSwitchApplication.Izbrani_predmeti.DetailsClass.PropertySetProperties.Predmet);
            }
            set
            {
                global::LightSwitchApplication.Izbrani_predmeti.DetailsClass.SetValue(this, global::LightSwitchApplication.Izbrani_predmeti.DetailsClass.PropertySetProperties.Predmet, value);
            }
        }
        
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Predmet_IsReadOnly(ref bool result);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Predmet_Validate(global::Microsoft.LightSwitch.EntityValidationResultsBuilder results);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Predmet_Changed();

        /// <summary>
        /// No Modeled Description Available
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.1.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::LightSwitchApplication.Student Student
        {
            get
            {
                return global::LightSwitchApplication.Izbrani_predmeti.DetailsClass.GetValue(this, global::LightSwitchApplication.Izbrani_predmeti.DetailsClass.PropertySetProperties.Student);
            }
            set
            {
                global::LightSwitchApplication.Izbrani_predmeti.DetailsClass.SetValue(this, global::LightSwitchApplication.Izbrani_predmeti.DetailsClass.PropertySetProperties.Student, value);
            }
        }
        
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Student_IsReadOnly(ref bool result);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Student_Validate(global::Microsoft.LightSwitch.EntityValidationResultsBuilder results);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Student_Changed();

        #endregion
    
        #region Details Class
    
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        [global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1034:NestedTypesShouldNotBeVisible")]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.1.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public sealed class DetailsClass : global::Microsoft.LightSwitch.Details.Framework.Base.EntityDetails<
                global::LightSwitchApplication.Izbrani_predmeti,
                global::LightSwitchApplication.Izbrani_predmeti.DetailsClass,
                global::LightSwitchApplication.Izbrani_predmeti.DetailsClass.IImplementation,
                global::LightSwitchApplication.Izbrani_predmeti.DetailsClass.PropertySet,
                global::Microsoft.LightSwitch.Details.Framework.EntityCommandSet<global::LightSwitchApplication.Izbrani_predmeti, global::LightSwitchApplication.Izbrani_predmeti.DetailsClass>,
                global::Microsoft.LightSwitch.Details.Framework.EntityMethodSet<global::LightSwitchApplication.Izbrani_predmeti, global::LightSwitchApplication.Izbrani_predmeti.DetailsClass>>
        {
    
            static DetailsClass()
            {
                var initializeEntry = global::LightSwitchApplication.Izbrani_predmeti.DetailsClass.PropertySetProperties.tekoven_semestar;
            }
    
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private static readonly global::Microsoft.LightSwitch.Details.Framework.Base.EntityDetails<global::LightSwitchApplication.Izbrani_predmeti, global::LightSwitchApplication.Izbrani_predmeti.DetailsClass>.Entry
                __Izbrani_predmetiEntry = new global::Microsoft.LightSwitch.Details.Framework.Base.EntityDetails<global::LightSwitchApplication.Izbrani_predmeti, global::LightSwitchApplication.Izbrani_predmeti.DetailsClass>.Entry(
                    global::LightSwitchApplication.Izbrani_predmeti.DetailsClass.__Izbrani_predmeti_CreateNew,
                    global::LightSwitchApplication.Izbrani_predmeti.DetailsClass.__Izbrani_predmeti_Created,
                    global::LightSwitchApplication.Izbrani_predmeti.DetailsClass.__Izbrani_predmeti_AllowSaveWithErrors);
            private static global::LightSwitchApplication.Izbrani_predmeti __Izbrani_predmeti_CreateNew(global::Microsoft.LightSwitch.Framework.EntitySet<global::LightSwitchApplication.Izbrani_predmeti> es)
            {
                return new global::LightSwitchApplication.Izbrani_predmeti(es);
            }
            private static void __Izbrani_predmeti_Created(global::LightSwitchApplication.Izbrani_predmeti e)
            {
                e.Izbrani_predmeti_Created();
            }
            private static bool __Izbrani_predmeti_AllowSaveWithErrors(global::LightSwitchApplication.Izbrani_predmeti e)
            {
                bool result = false;
                e.Izbrani_predmeti_AllowSaveWithErrors(ref result);
                return result;
            }
    
            public DetailsClass() : base()
            {
            }
    
            public new global::Microsoft.LightSwitch.Details.Framework.EntityCommandSet<global::LightSwitchApplication.Izbrani_predmeti, global::LightSwitchApplication.Izbrani_predmeti.DetailsClass> Commands
            {
                get
                {
                    return base.Commands;
                }
            }
    
            public new global::Microsoft.LightSwitch.Details.Framework.EntityMethodSet<global::LightSwitchApplication.Izbrani_predmeti, global::LightSwitchApplication.Izbrani_predmeti.DetailsClass> Methods
            {
                get
                {
                    return base.Methods;
                }
            }
    
            public new global::LightSwitchApplication.Izbrani_predmeti.DetailsClass.PropertySet Properties
            {
                get
                {
                    return base.Properties;
                }
            }
    
            [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
            [global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1034:NestedTypesShouldNotBeVisible")]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.1.0.0")]
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public sealed class PropertySet : global::Microsoft.LightSwitch.Details.Framework.Base.EntityPropertySet<global::LightSwitchApplication.Izbrani_predmeti, global::LightSwitchApplication.Izbrani_predmeti.DetailsClass>
            {
    
                public PropertySet() : base()
                {
                }
    
                public global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Izbrani_predmeti, global::LightSwitchApplication.Izbrani_predmeti.DetailsClass, string> tekoven_semestar
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.Izbrani_predmeti.DetailsClass.PropertySetProperties.tekoven_semestar) as global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Izbrani_predmeti, global::LightSwitchApplication.Izbrani_predmeti.DetailsClass, string>;
                    }
                }
                
                public global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Izbrani_predmeti, global::LightSwitchApplication.Izbrani_predmeti.DetailsClass, int> ID_izbraniPredmeti
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.Izbrani_predmeti.DetailsClass.PropertySetProperties.ID_izbraniPredmeti) as global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Izbrani_predmeti, global::LightSwitchApplication.Izbrani_predmeti.DetailsClass, int>;
                    }
                }
                
                public global::Microsoft.LightSwitch.Details.Framework.EntityReferenceProperty<global::LightSwitchApplication.Izbrani_predmeti, global::LightSwitchApplication.Izbrani_predmeti.DetailsClass, global::LightSwitchApplication.Predmet> Predmet
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.Izbrani_predmeti.DetailsClass.PropertySetProperties.Predmet) as global::Microsoft.LightSwitch.Details.Framework.EntityReferenceProperty<global::LightSwitchApplication.Izbrani_predmeti, global::LightSwitchApplication.Izbrani_predmeti.DetailsClass, global::LightSwitchApplication.Predmet>;
                    }
                }
                
                public global::Microsoft.LightSwitch.Details.Framework.EntityReferenceProperty<global::LightSwitchApplication.Izbrani_predmeti, global::LightSwitchApplication.Izbrani_predmeti.DetailsClass, global::LightSwitchApplication.Student> Student
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.Izbrani_predmeti.DetailsClass.PropertySetProperties.Student) as global::Microsoft.LightSwitch.Details.Framework.EntityReferenceProperty<global::LightSwitchApplication.Izbrani_predmeti, global::LightSwitchApplication.Izbrani_predmeti.DetailsClass, global::LightSwitchApplication.Student>;
                    }
                }
                
            }
    
            #pragma warning disable 109
            [global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1034:NestedTypesShouldNotBeVisible")]
            public interface IImplementation : global::Microsoft.LightSwitch.Internal.IEntityImplementation
            {
                new string tekoven_semestar { get; set; }
                new int ID_izbraniPredmeti { get; }
                new global::Microsoft.LightSwitch.Internal.IEntityImplementation Predmet { get; set; }
                new global::Microsoft.LightSwitch.Internal.IEntityImplementation Student { get; set; }
            }
            #pragma warning restore 109
    
            [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.1.0.0")]
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            internal class PropertySetProperties
            {
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Izbrani_predmeti, global::LightSwitchApplication.Izbrani_predmeti.DetailsClass, string>.Entry
                    tekoven_semestar = new global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Izbrani_predmeti, global::LightSwitchApplication.Izbrani_predmeti.DetailsClass, string>.Entry(
                        "tekoven_semestar",
                        global::LightSwitchApplication.Izbrani_predmeti.DetailsClass.PropertySetProperties._tekoven_semestar_Stub,
                        global::LightSwitchApplication.Izbrani_predmeti.DetailsClass.PropertySetProperties._tekoven_semestar_ComputeIsReadOnly,
                        global::LightSwitchApplication.Izbrani_predmeti.DetailsClass.PropertySetProperties._tekoven_semestar_Validate,
                        global::LightSwitchApplication.Izbrani_predmeti.DetailsClass.PropertySetProperties._tekoven_semestar_GetImplementationValue,
                        global::LightSwitchApplication.Izbrani_predmeti.DetailsClass.PropertySetProperties._tekoven_semestar_SetImplementationValue,
                        global::LightSwitchApplication.Izbrani_predmeti.DetailsClass.PropertySetProperties._tekoven_semestar_OnValueChanged);
                private static void _tekoven_semestar_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.Izbrani_predmeti.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Izbrani_predmeti, global::LightSwitchApplication.Izbrani_predmeti.DetailsClass, string>.Data> c, global::LightSwitchApplication.Izbrani_predmeti.DetailsClass d, object sf)
                {
                    c(d, ref d._tekoven_semestar, sf);
                }
                private static bool _tekoven_semestar_ComputeIsReadOnly(global::LightSwitchApplication.Izbrani_predmeti e)
                {
                    bool result = false;
                    e.tekoven_semestar_IsReadOnly(ref result);
                    return result;
                }
                private static void _tekoven_semestar_Validate(global::LightSwitchApplication.Izbrani_predmeti e, global::Microsoft.LightSwitch.EntityValidationResultsBuilder r)
                {
                    e.tekoven_semestar_Validate(r);
                }
                private static string _tekoven_semestar_GetImplementationValue(global::LightSwitchApplication.Izbrani_predmeti.DetailsClass d)
                {
                    return d.ImplementationEntity.tekoven_semestar;
                }
                private static void _tekoven_semestar_SetImplementationValue(global::LightSwitchApplication.Izbrani_predmeti.DetailsClass d, string v)
                {
                    d.ImplementationEntity.tekoven_semestar = v;
                }
                private static void _tekoven_semestar_OnValueChanged(global::LightSwitchApplication.Izbrani_predmeti e)
                {
                    e.tekoven_semestar_Changed();
                }
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Izbrani_predmeti, global::LightSwitchApplication.Izbrani_predmeti.DetailsClass, int>.Entry
                    ID_izbraniPredmeti = new global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Izbrani_predmeti, global::LightSwitchApplication.Izbrani_predmeti.DetailsClass, int>.Entry(
                        "ID_izbraniPredmeti",
                        global::LightSwitchApplication.Izbrani_predmeti.DetailsClass.PropertySetProperties._ID_izbraniPredmeti_Stub,
                        global::LightSwitchApplication.Izbrani_predmeti.DetailsClass.PropertySetProperties._ID_izbraniPredmeti_ComputeIsReadOnly,
                        global::LightSwitchApplication.Izbrani_predmeti.DetailsClass.PropertySetProperties._ID_izbraniPredmeti_Validate,
                        global::LightSwitchApplication.Izbrani_predmeti.DetailsClass.PropertySetProperties._ID_izbraniPredmeti_GetImplementationValue,
                        null,
                        global::LightSwitchApplication.Izbrani_predmeti.DetailsClass.PropertySetProperties._ID_izbraniPredmeti_OnValueChanged);
                private static void _ID_izbraniPredmeti_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.Izbrani_predmeti.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Izbrani_predmeti, global::LightSwitchApplication.Izbrani_predmeti.DetailsClass, int>.Data> c, global::LightSwitchApplication.Izbrani_predmeti.DetailsClass d, object sf)
                {
                    c(d, ref d._ID_izbraniPredmeti, sf);
                }
                private static bool _ID_izbraniPredmeti_ComputeIsReadOnly(global::LightSwitchApplication.Izbrani_predmeti e)
                {
                    bool result = false;
                    e.ID_izbraniPredmeti_IsReadOnly(ref result);
                    return result;
                }
                private static void _ID_izbraniPredmeti_Validate(global::LightSwitchApplication.Izbrani_predmeti e, global::Microsoft.LightSwitch.EntityValidationResultsBuilder r)
                {
                    e.ID_izbraniPredmeti_Validate(r);
                }
                private static int _ID_izbraniPredmeti_GetImplementationValue(global::LightSwitchApplication.Izbrani_predmeti.DetailsClass d)
                {
                    return d.ImplementationEntity.ID_izbraniPredmeti;
                }
                private static void _ID_izbraniPredmeti_OnValueChanged(global::LightSwitchApplication.Izbrani_predmeti e)
                {
                    e.ID_izbraniPredmeti_Changed();
                }
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityReferenceProperty<global::LightSwitchApplication.Izbrani_predmeti, global::LightSwitchApplication.Izbrani_predmeti.DetailsClass, global::LightSwitchApplication.Predmet>.Entry
                    Predmet = new global::Microsoft.LightSwitch.Details.Framework.EntityReferenceProperty<global::LightSwitchApplication.Izbrani_predmeti, global::LightSwitchApplication.Izbrani_predmeti.DetailsClass, global::LightSwitchApplication.Predmet>.Entry(
                        "Predmet",
                        global::LightSwitchApplication.Izbrani_predmeti.DetailsClass.PropertySetProperties._Predmet_Stub,
                        global::LightSwitchApplication.Izbrani_predmeti.DetailsClass.PropertySetProperties._Predmet_ComputeIsReadOnly,
                        global::LightSwitchApplication.Izbrani_predmeti.DetailsClass.PropertySetProperties._Predmet_Validate,
                        global::LightSwitchApplication.Izbrani_predmeti.DetailsClass.PropertySetProperties._Predmet_GetCoreImplementationValue,
                        global::LightSwitchApplication.Izbrani_predmeti.DetailsClass.PropertySetProperties._Predmet_GetImplementationValue,
                        global::LightSwitchApplication.Izbrani_predmeti.DetailsClass.PropertySetProperties._Predmet_SetImplementationValue,
                        global::LightSwitchApplication.Izbrani_predmeti.DetailsClass.PropertySetProperties._Predmet_Refresh,
                        global::LightSwitchApplication.Izbrani_predmeti.DetailsClass.PropertySetProperties._Predmet_OnValueChanged);
                private static void _Predmet_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.Izbrani_predmeti.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityReferenceProperty<global::LightSwitchApplication.Izbrani_predmeti, global::LightSwitchApplication.Izbrani_predmeti.DetailsClass, global::LightSwitchApplication.Predmet>.Data> c, global::LightSwitchApplication.Izbrani_predmeti.DetailsClass d, object sf)
                {
                    c(d, ref d._Predmet, sf);
                }
                private static bool _Predmet_ComputeIsReadOnly(global::LightSwitchApplication.Izbrani_predmeti e)
                {
                    bool result = false;
                    e.Predmet_IsReadOnly(ref result);
                    return result;
                }
                private static void _Predmet_Validate(global::LightSwitchApplication.Izbrani_predmeti e, global::Microsoft.LightSwitch.EntityValidationResultsBuilder r)
                {
                    e.Predmet_Validate(r);
                }
                private static global::Microsoft.LightSwitch.Internal.IEntityImplementation _Predmet_GetCoreImplementationValue(global::LightSwitchApplication.Izbrani_predmeti.DetailsClass d)
                {
                    return d.ImplementationEntity.Predmet;
                }
                private static global::LightSwitchApplication.Predmet _Predmet_GetImplementationValue(global::LightSwitchApplication.Izbrani_predmeti.DetailsClass d)
                {
                    return d.GetImplementationValue<global::LightSwitchApplication.Predmet, global::LightSwitchApplication.Predmet.DetailsClass>(global::LightSwitchApplication.Izbrani_predmeti.DetailsClass.PropertySetProperties.Predmet, ref d._Predmet);
                }
                private static void _Predmet_SetImplementationValue(global::LightSwitchApplication.Izbrani_predmeti.DetailsClass d, global::LightSwitchApplication.Predmet v)
                {
                    d.SetImplementationValue(global::LightSwitchApplication.Izbrani_predmeti.DetailsClass.PropertySetProperties.Predmet, ref d._Predmet, (i, ev) => i.Predmet = ev, v);
                }
                private static void _Predmet_Refresh(global::LightSwitchApplication.Izbrani_predmeti.DetailsClass d)
                {
                    d.RefreshNavigationProperty(global::LightSwitchApplication.Izbrani_predmeti.DetailsClass.PropertySetProperties.Predmet, ref d._Predmet);
                }
                private static void _Predmet_OnValueChanged(global::LightSwitchApplication.Izbrani_predmeti e)
                {
                    e.Predmet_Changed();
                }
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityReferenceProperty<global::LightSwitchApplication.Izbrani_predmeti, global::LightSwitchApplication.Izbrani_predmeti.DetailsClass, global::LightSwitchApplication.Student>.Entry
                    Student = new global::Microsoft.LightSwitch.Details.Framework.EntityReferenceProperty<global::LightSwitchApplication.Izbrani_predmeti, global::LightSwitchApplication.Izbrani_predmeti.DetailsClass, global::LightSwitchApplication.Student>.Entry(
                        "Student",
                        global::LightSwitchApplication.Izbrani_predmeti.DetailsClass.PropertySetProperties._Student_Stub,
                        global::LightSwitchApplication.Izbrani_predmeti.DetailsClass.PropertySetProperties._Student_ComputeIsReadOnly,
                        global::LightSwitchApplication.Izbrani_predmeti.DetailsClass.PropertySetProperties._Student_Validate,
                        global::LightSwitchApplication.Izbrani_predmeti.DetailsClass.PropertySetProperties._Student_GetCoreImplementationValue,
                        global::LightSwitchApplication.Izbrani_predmeti.DetailsClass.PropertySetProperties._Student_GetImplementationValue,
                        global::LightSwitchApplication.Izbrani_predmeti.DetailsClass.PropertySetProperties._Student_SetImplementationValue,
                        global::LightSwitchApplication.Izbrani_predmeti.DetailsClass.PropertySetProperties._Student_Refresh,
                        global::LightSwitchApplication.Izbrani_predmeti.DetailsClass.PropertySetProperties._Student_OnValueChanged);
                private static void _Student_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.Izbrani_predmeti.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityReferenceProperty<global::LightSwitchApplication.Izbrani_predmeti, global::LightSwitchApplication.Izbrani_predmeti.DetailsClass, global::LightSwitchApplication.Student>.Data> c, global::LightSwitchApplication.Izbrani_predmeti.DetailsClass d, object sf)
                {
                    c(d, ref d._Student, sf);
                }
                private static bool _Student_ComputeIsReadOnly(global::LightSwitchApplication.Izbrani_predmeti e)
                {
                    bool result = false;
                    e.Student_IsReadOnly(ref result);
                    return result;
                }
                private static void _Student_Validate(global::LightSwitchApplication.Izbrani_predmeti e, global::Microsoft.LightSwitch.EntityValidationResultsBuilder r)
                {
                    e.Student_Validate(r);
                }
                private static global::Microsoft.LightSwitch.Internal.IEntityImplementation _Student_GetCoreImplementationValue(global::LightSwitchApplication.Izbrani_predmeti.DetailsClass d)
                {
                    return d.ImplementationEntity.Student;
                }
                private static global::LightSwitchApplication.Student _Student_GetImplementationValue(global::LightSwitchApplication.Izbrani_predmeti.DetailsClass d)
                {
                    return d.GetImplementationValue<global::LightSwitchApplication.Student, global::LightSwitchApplication.Student.DetailsClass>(global::LightSwitchApplication.Izbrani_predmeti.DetailsClass.PropertySetProperties.Student, ref d._Student);
                }
                private static void _Student_SetImplementationValue(global::LightSwitchApplication.Izbrani_predmeti.DetailsClass d, global::LightSwitchApplication.Student v)
                {
                    d.SetImplementationValue(global::LightSwitchApplication.Izbrani_predmeti.DetailsClass.PropertySetProperties.Student, ref d._Student, (i, ev) => i.Student = ev, v);
                }
                private static void _Student_Refresh(global::LightSwitchApplication.Izbrani_predmeti.DetailsClass d)
                {
                    d.RefreshNavigationProperty(global::LightSwitchApplication.Izbrani_predmeti.DetailsClass.PropertySetProperties.Student, ref d._Student);
                }
                private static void _Student_OnValueChanged(global::LightSwitchApplication.Izbrani_predmeti e)
                {
                    e.Student_Changed();
                }
    
            }
    
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Izbrani_predmeti, global::LightSwitchApplication.Izbrani_predmeti.DetailsClass, string>.Data _tekoven_semestar;
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Izbrani_predmeti, global::LightSwitchApplication.Izbrani_predmeti.DetailsClass, int>.Data _ID_izbraniPredmeti;
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityReferenceProperty<global::LightSwitchApplication.Izbrani_predmeti, global::LightSwitchApplication.Izbrani_predmeti.DetailsClass, global::LightSwitchApplication.Predmet>.Data _Predmet;
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityReferenceProperty<global::LightSwitchApplication.Izbrani_predmeti, global::LightSwitchApplication.Izbrani_predmeti.DetailsClass, global::LightSwitchApplication.Student>.Data _Student;
            
        }
    
        #endregion
    }
    
    #endregion
}
