

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LightSwitchApplication
{
    #region Entities
    
    /// <summary>
    /// No Modeled Description Available
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.1.0.0")]
    public sealed partial class Prostorija : global::Microsoft.LightSwitch.Framework.Base.EntityObject<global::LightSwitchApplication.Prostorija, global::LightSwitchApplication.Prostorija.DetailsClass>
    {
        #region Constructors
    
        /// <summary>
        /// Initializes a new instance of the Prostorija entity.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.1.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public Prostorija()
            : this(null)
        {
        }
    
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.1.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public Prostorija(global::Microsoft.LightSwitch.Framework.EntitySet<global::LightSwitchApplication.Prostorija> entitySet)
            : base(entitySet)
        {
            global::LightSwitchApplication.Prostorija.DetailsClass.Initialize(this);
        }
    
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Prostorija_Created();
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Prostorija_AllowSaveWithErrors(ref bool result);
    
        #endregion
    
        #region Private Properties
        
        /// <summary>
        /// Gets the Application object for this application.  The Application object provides access to active screens, methods to open screens and access to the current user.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.1.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::Microsoft.LightSwitch.IApplication<global::LightSwitchApplication.DataWorkspace> Application
        {
            get
            {
                return (global::Microsoft.LightSwitch.IApplication<global::LightSwitchApplication.DataWorkspace>)global::LightSwitchApplication.Application.Current;
            }
        }
        
        /// <summary>
        /// Gets the containing data workspace.  The data workspace provides access to all data sources in the application.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.1.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::LightSwitchApplication.DataWorkspace DataWorkspace
        {
            get
            {
                return (global::LightSwitchApplication.DataWorkspace)this.Details.EntitySet.Details.DataService.Details.DataWorkspace;
            }
        }
        
        #endregion
    
        #region Public Properties
    
        /// <summary>
        /// No Modeled Description Available
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.1.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.Nullable<int> Br_prostorija
        {
            get
            {
                return global::LightSwitchApplication.Prostorija.DetailsClass.GetValue(this, global::LightSwitchApplication.Prostorija.DetailsClass.PropertySetProperties.Br_prostorija);
            }
            set
            {
                global::LightSwitchApplication.Prostorija.DetailsClass.SetValue(this, global::LightSwitchApplication.Prostorija.DetailsClass.PropertySetProperties.Br_prostorija, value);
            }
        }
        
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Br_prostorija_IsReadOnly(ref bool result);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Br_prostorija_Validate(global::Microsoft.LightSwitch.EntityValidationResultsBuilder results);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Br_prostorija_Changed();

        /// <summary>
        /// No Modeled Description Available
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.1.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public string Opis
        {
            get
            {
                return global::LightSwitchApplication.Prostorija.DetailsClass.GetValue(this, global::LightSwitchApplication.Prostorija.DetailsClass.PropertySetProperties.Opis);
            }
            set
            {
                global::LightSwitchApplication.Prostorija.DetailsClass.SetValue(this, global::LightSwitchApplication.Prostorija.DetailsClass.PropertySetProperties.Opis, value);
            }
        }
        
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Opis_IsReadOnly(ref bool result);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Opis_Validate(global::Microsoft.LightSwitch.EntityValidationResultsBuilder results);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Opis_Changed();

        /// <summary>
        /// No Modeled Description Available
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.1.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public int ID_prostorija
        {
            get
            {
                return global::LightSwitchApplication.Prostorija.DetailsClass.GetValue(this, global::LightSwitchApplication.Prostorija.DetailsClass.PropertySetProperties.ID_prostorija);
            }
        }
        
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void ID_prostorija_IsReadOnly(ref bool result);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void ID_prostorija_Validate(global::Microsoft.LightSwitch.EntityValidationResultsBuilder results);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void ID_prostorija_Changed();

        /// <summary>
        /// No Modeled Description Available
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.1.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::Microsoft.LightSwitch.Framework.EntityCollection<global::LightSwitchApplication.Aktivnost> Aktivnosts
        {
            get
            {
                return global::LightSwitchApplication.Prostorija.DetailsClass.GetValue(this, global::LightSwitchApplication.Prostorija.DetailsClass.PropertySetProperties.Aktivnosts);
            }
        }
        
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.1.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public Microsoft.LightSwitch.IDataServiceQueryable<global::LightSwitchApplication.Aktivnost> AktivnostsQuery
        {
            get
            {
                return global::LightSwitchApplication.Prostorija.DetailsClass.GetQuery(this, global::LightSwitchApplication.Prostorija.DetailsClass.PropertySetProperties.Aktivnosts);
            }
        }

        #endregion
    
        #region Details Class
    
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        [global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1034:NestedTypesShouldNotBeVisible")]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.1.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public sealed class DetailsClass : global::Microsoft.LightSwitch.Details.Framework.Base.EntityDetails<
                global::LightSwitchApplication.Prostorija,
                global::LightSwitchApplication.Prostorija.DetailsClass,
                global::LightSwitchApplication.Prostorija.DetailsClass.IImplementation,
                global::LightSwitchApplication.Prostorija.DetailsClass.PropertySet,
                global::Microsoft.LightSwitch.Details.Framework.EntityCommandSet<global::LightSwitchApplication.Prostorija, global::LightSwitchApplication.Prostorija.DetailsClass>,
                global::Microsoft.LightSwitch.Details.Framework.EntityMethodSet<global::LightSwitchApplication.Prostorija, global::LightSwitchApplication.Prostorija.DetailsClass>>
        {
    
            static DetailsClass()
            {
                var initializeEntry = global::LightSwitchApplication.Prostorija.DetailsClass.PropertySetProperties.Br_prostorija;
            }
    
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private static readonly global::Microsoft.LightSwitch.Details.Framework.Base.EntityDetails<global::LightSwitchApplication.Prostorija, global::LightSwitchApplication.Prostorija.DetailsClass>.Entry
                __ProstorijaEntry = new global::Microsoft.LightSwitch.Details.Framework.Base.EntityDetails<global::LightSwitchApplication.Prostorija, global::LightSwitchApplication.Prostorija.DetailsClass>.Entry(
                    global::LightSwitchApplication.Prostorija.DetailsClass.__Prostorija_CreateNew,
                    global::LightSwitchApplication.Prostorija.DetailsClass.__Prostorija_Created,
                    global::LightSwitchApplication.Prostorija.DetailsClass.__Prostorija_AllowSaveWithErrors);
            private static global::LightSwitchApplication.Prostorija __Prostorija_CreateNew(global::Microsoft.LightSwitch.Framework.EntitySet<global::LightSwitchApplication.Prostorija> es)
            {
                return new global::LightSwitchApplication.Prostorija(es);
            }
            private static void __Prostorija_Created(global::LightSwitchApplication.Prostorija e)
            {
                e.Prostorija_Created();
            }
            private static bool __Prostorija_AllowSaveWithErrors(global::LightSwitchApplication.Prostorija e)
            {
                bool result = false;
                e.Prostorija_AllowSaveWithErrors(ref result);
                return result;
            }
    
            public DetailsClass() : base()
            {
            }
    
            public new global::Microsoft.LightSwitch.Details.Framework.EntityCommandSet<global::LightSwitchApplication.Prostorija, global::LightSwitchApplication.Prostorija.DetailsClass> Commands
            {
                get
                {
                    return base.Commands;
                }
            }
    
            public new global::Microsoft.LightSwitch.Details.Framework.EntityMethodSet<global::LightSwitchApplication.Prostorija, global::LightSwitchApplication.Prostorija.DetailsClass> Methods
            {
                get
                {
                    return base.Methods;
                }
            }
    
            public new global::LightSwitchApplication.Prostorija.DetailsClass.PropertySet Properties
            {
                get
                {
                    return base.Properties;
                }
            }
    
            [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
            [global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1034:NestedTypesShouldNotBeVisible")]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.1.0.0")]
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public sealed class PropertySet : global::Microsoft.LightSwitch.Details.Framework.Base.EntityPropertySet<global::LightSwitchApplication.Prostorija, global::LightSwitchApplication.Prostorija.DetailsClass>
            {
    
                public PropertySet() : base()
                {
                }
    
                public global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Prostorija, global::LightSwitchApplication.Prostorija.DetailsClass, global::System.Nullable<int>> Br_prostorija
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.Prostorija.DetailsClass.PropertySetProperties.Br_prostorija) as global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Prostorija, global::LightSwitchApplication.Prostorija.DetailsClass, global::System.Nullable<int>>;
                    }
                }
                
                public global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Prostorija, global::LightSwitchApplication.Prostorija.DetailsClass, string> Opis
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.Prostorija.DetailsClass.PropertySetProperties.Opis) as global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Prostorija, global::LightSwitchApplication.Prostorija.DetailsClass, string>;
                    }
                }
                
                public global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Prostorija, global::LightSwitchApplication.Prostorija.DetailsClass, int> ID_prostorija
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.Prostorija.DetailsClass.PropertySetProperties.ID_prostorija) as global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Prostorija, global::LightSwitchApplication.Prostorija.DetailsClass, int>;
                    }
                }
                
                public global::Microsoft.LightSwitch.Details.Framework.EntityCollectionProperty<global::LightSwitchApplication.Prostorija, global::LightSwitchApplication.Prostorija.DetailsClass, global::LightSwitchApplication.Aktivnost> Aktivnosts
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.Prostorija.DetailsClass.PropertySetProperties.Aktivnosts) as global::Microsoft.LightSwitch.Details.Framework.EntityCollectionProperty<global::LightSwitchApplication.Prostorija, global::LightSwitchApplication.Prostorija.DetailsClass, global::LightSwitchApplication.Aktivnost>;
                    }
                }
                
            }
    
            #pragma warning disable 109
            [global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1034:NestedTypesShouldNotBeVisible")]
            public interface IImplementation : global::Microsoft.LightSwitch.Internal.IEntityImplementation
            {
                new global::System.Nullable<int> Br_prostorija { get; set; }
                new string Opis { get; set; }
                new int ID_prostorija { get; }
                new global::System.Collections.IEnumerable Aktivnosts { get; }
            }
            #pragma warning restore 109
    
            [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.1.0.0")]
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            internal class PropertySetProperties
            {
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Prostorija, global::LightSwitchApplication.Prostorija.DetailsClass, global::System.Nullable<int>>.Entry
                    Br_prostorija = new global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Prostorija, global::LightSwitchApplication.Prostorija.DetailsClass, global::System.Nullable<int>>.Entry(
                        "Br_prostorija",
                        global::LightSwitchApplication.Prostorija.DetailsClass.PropertySetProperties._Br_prostorija_Stub,
                        global::LightSwitchApplication.Prostorija.DetailsClass.PropertySetProperties._Br_prostorija_ComputeIsReadOnly,
                        global::LightSwitchApplication.Prostorija.DetailsClass.PropertySetProperties._Br_prostorija_Validate,
                        global::LightSwitchApplication.Prostorija.DetailsClass.PropertySetProperties._Br_prostorija_GetImplementationValue,
                        global::LightSwitchApplication.Prostorija.DetailsClass.PropertySetProperties._Br_prostorija_SetImplementationValue,
                        global::LightSwitchApplication.Prostorija.DetailsClass.PropertySetProperties._Br_prostorija_OnValueChanged);
                private static void _Br_prostorija_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.Prostorija.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Prostorija, global::LightSwitchApplication.Prostorija.DetailsClass, global::System.Nullable<int>>.Data> c, global::LightSwitchApplication.Prostorija.DetailsClass d, object sf)
                {
                    c(d, ref d._Br_prostorija, sf);
                }
                private static bool _Br_prostorija_ComputeIsReadOnly(global::LightSwitchApplication.Prostorija e)
                {
                    bool result = false;
                    e.Br_prostorija_IsReadOnly(ref result);
                    return result;
                }
                private static void _Br_prostorija_Validate(global::LightSwitchApplication.Prostorija e, global::Microsoft.LightSwitch.EntityValidationResultsBuilder r)
                {
                    e.Br_prostorija_Validate(r);
                }
                private static global::System.Nullable<int> _Br_prostorija_GetImplementationValue(global::LightSwitchApplication.Prostorija.DetailsClass d)
                {
                    return d.ImplementationEntity.Br_prostorija;
                }
                private static void _Br_prostorija_SetImplementationValue(global::LightSwitchApplication.Prostorija.DetailsClass d, global::System.Nullable<int> v)
                {
                    d.ImplementationEntity.Br_prostorija = v;
                }
                private static void _Br_prostorija_OnValueChanged(global::LightSwitchApplication.Prostorija e)
                {
                    e.Br_prostorija_Changed();
                }
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Prostorija, global::LightSwitchApplication.Prostorija.DetailsClass, string>.Entry
                    Opis = new global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Prostorija, global::LightSwitchApplication.Prostorija.DetailsClass, string>.Entry(
                        "Opis",
                        global::LightSwitchApplication.Prostorija.DetailsClass.PropertySetProperties._Opis_Stub,
                        global::LightSwitchApplication.Prostorija.DetailsClass.PropertySetProperties._Opis_ComputeIsReadOnly,
                        global::LightSwitchApplication.Prostorija.DetailsClass.PropertySetProperties._Opis_Validate,
                        global::LightSwitchApplication.Prostorija.DetailsClass.PropertySetProperties._Opis_GetImplementationValue,
                        global::LightSwitchApplication.Prostorija.DetailsClass.PropertySetProperties._Opis_SetImplementationValue,
                        global::LightSwitchApplication.Prostorija.DetailsClass.PropertySetProperties._Opis_OnValueChanged);
                private static void _Opis_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.Prostorija.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Prostorija, global::LightSwitchApplication.Prostorija.DetailsClass, string>.Data> c, global::LightSwitchApplication.Prostorija.DetailsClass d, object sf)
                {
                    c(d, ref d._Opis, sf);
                }
                private static bool _Opis_ComputeIsReadOnly(global::LightSwitchApplication.Prostorija e)
                {
                    bool result = false;
                    e.Opis_IsReadOnly(ref result);
                    return result;
                }
                private static void _Opis_Validate(global::LightSwitchApplication.Prostorija e, global::Microsoft.LightSwitch.EntityValidationResultsBuilder r)
                {
                    e.Opis_Validate(r);
                }
                private static string _Opis_GetImplementationValue(global::LightSwitchApplication.Prostorija.DetailsClass d)
                {
                    return d.ImplementationEntity.Opis;
                }
                private static void _Opis_SetImplementationValue(global::LightSwitchApplication.Prostorija.DetailsClass d, string v)
                {
                    d.ImplementationEntity.Opis = v;
                }
                private static void _Opis_OnValueChanged(global::LightSwitchApplication.Prostorija e)
                {
                    e.Opis_Changed();
                }
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Prostorija, global::LightSwitchApplication.Prostorija.DetailsClass, int>.Entry
                    ID_prostorija = new global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Prostorija, global::LightSwitchApplication.Prostorija.DetailsClass, int>.Entry(
                        "ID_prostorija",
                        global::LightSwitchApplication.Prostorija.DetailsClass.PropertySetProperties._ID_prostorija_Stub,
                        global::LightSwitchApplication.Prostorija.DetailsClass.PropertySetProperties._ID_prostorija_ComputeIsReadOnly,
                        global::LightSwitchApplication.Prostorija.DetailsClass.PropertySetProperties._ID_prostorija_Validate,
                        global::LightSwitchApplication.Prostorija.DetailsClass.PropertySetProperties._ID_prostorija_GetImplementationValue,
                        null,
                        global::LightSwitchApplication.Prostorija.DetailsClass.PropertySetProperties._ID_prostorija_OnValueChanged);
                private static void _ID_prostorija_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.Prostorija.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Prostorija, global::LightSwitchApplication.Prostorija.DetailsClass, int>.Data> c, global::LightSwitchApplication.Prostorija.DetailsClass d, object sf)
                {
                    c(d, ref d._ID_prostorija, sf);
                }
                private static bool _ID_prostorija_ComputeIsReadOnly(global::LightSwitchApplication.Prostorija e)
                {
                    bool result = false;
                    e.ID_prostorija_IsReadOnly(ref result);
                    return result;
                }
                private static void _ID_prostorija_Validate(global::LightSwitchApplication.Prostorija e, global::Microsoft.LightSwitch.EntityValidationResultsBuilder r)
                {
                    e.ID_prostorija_Validate(r);
                }
                private static int _ID_prostorija_GetImplementationValue(global::LightSwitchApplication.Prostorija.DetailsClass d)
                {
                    return d.ImplementationEntity.ID_prostorija;
                }
                private static void _ID_prostorija_OnValueChanged(global::LightSwitchApplication.Prostorija e)
                {
                    e.ID_prostorija_Changed();
                }
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityCollectionProperty<global::LightSwitchApplication.Prostorija, global::LightSwitchApplication.Prostorija.DetailsClass, global::LightSwitchApplication.Aktivnost>.Entry
                    Aktivnosts = new global::Microsoft.LightSwitch.Details.Framework.EntityCollectionProperty<global::LightSwitchApplication.Prostorija, global::LightSwitchApplication.Prostorija.DetailsClass, global::LightSwitchApplication.Aktivnost>.Entry(
                        "Aktivnosts",
                        global::LightSwitchApplication.Prostorija.DetailsClass.PropertySetProperties._Aktivnosts_Stub,
                        global::LightSwitchApplication.Prostorija.DetailsClass.PropertySetProperties._Aktivnosts_GetReferencedEntities,
                        global::LightSwitchApplication.Prostorija.DetailsClass.PropertySetProperties._Aktivnosts_GetEntityCollection);
                private static void _Aktivnosts_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.Prostorija.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityCollectionProperty<global::LightSwitchApplication.Prostorija, global::LightSwitchApplication.Prostorija.DetailsClass, global::LightSwitchApplication.Aktivnost>.Data> c, global::LightSwitchApplication.Prostorija.DetailsClass d, object sf)
                {
                    c(d, ref d._Aktivnosts, sf);
                }
                private static global::System.Collections.Generic.IEnumerable<global::LightSwitchApplication.Aktivnost> _Aktivnosts_GetReferencedEntities(global::LightSwitchApplication.Prostorija.DetailsClass d)
                {
                    return d.GetReferencedEntities<global::LightSwitchApplication.Aktivnost, global::LightSwitchApplication.Aktivnost.DetailsClass>(global::LightSwitchApplication.Prostorija.DetailsClass.PropertySetProperties.Aktivnosts, ref d._Aktivnosts);
                }
                private static global::System.Collections.IEnumerable _Aktivnosts_GetEntityCollection(global::LightSwitchApplication.Prostorija.DetailsClass d)
                {
                    return d.ImplementationEntity.Aktivnosts;
                }
    
            }
    
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Prostorija, global::LightSwitchApplication.Prostorija.DetailsClass, global::System.Nullable<int>>.Data _Br_prostorija;
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Prostorija, global::LightSwitchApplication.Prostorija.DetailsClass, string>.Data _Opis;
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Prostorija, global::LightSwitchApplication.Prostorija.DetailsClass, int>.Data _ID_prostorija;
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityCollectionProperty<global::LightSwitchApplication.Prostorija, global::LightSwitchApplication.Prostorija.DetailsClass, global::LightSwitchApplication.Aktivnost>.Data _Aktivnosts;
            
        }
    
        #endregion
    }
    
    #endregion
}
