

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LightSwitchApplication
{
    #region Entities
    
    /// <summary>
    /// No Modeled Description Available
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.1.0.0")]
    public sealed partial class vw_Aktivnosti : global::Microsoft.LightSwitch.Framework.Base.EntityObject<global::LightSwitchApplication.vw_Aktivnosti, global::LightSwitchApplication.vw_Aktivnosti.DetailsClass>
    {
        #region Constructors
    
        /// <summary>
        /// Initializes a new instance of the vw_Aktivnosti entity.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.1.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public vw_Aktivnosti()
            : this(null)
        {
        }
    
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.1.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public vw_Aktivnosti(global::Microsoft.LightSwitch.Framework.EntitySet<global::LightSwitchApplication.vw_Aktivnosti> entitySet)
            : base(entitySet)
        {
            global::LightSwitchApplication.vw_Aktivnosti.DetailsClass.Initialize(this);
        }
    
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void vw_Aktivnosti_Created();
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void vw_Aktivnosti_AllowSaveWithErrors(ref bool result);
    
        #endregion
    
        #region Private Properties
        
        /// <summary>
        /// Gets the Application object for this application.  The Application object provides access to active screens, methods to open screens and access to the current user.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.1.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::Microsoft.LightSwitch.IApplication<global::LightSwitchApplication.DataWorkspace> Application
        {
            get
            {
                return (global::Microsoft.LightSwitch.IApplication<global::LightSwitchApplication.DataWorkspace>)global::LightSwitchApplication.Application.Current;
            }
        }
        
        /// <summary>
        /// Gets the containing data workspace.  The data workspace provides access to all data sources in the application.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.1.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::LightSwitchApplication.DataWorkspace DataWorkspace
        {
            get
            {
                return (global::LightSwitchApplication.DataWorkspace)this.Details.EntitySet.Details.DataService.Details.DataWorkspace;
            }
        }
        
        #endregion
    
        #region Public Properties
    
        /// <summary>
        /// No Modeled Description Available
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.1.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public int ID_aktivnost
        {
            get
            {
                return global::LightSwitchApplication.vw_Aktivnosti.DetailsClass.GetValue(this, global::LightSwitchApplication.vw_Aktivnosti.DetailsClass.PropertySetProperties.ID_aktivnost);
            }
            set
            {
                global::LightSwitchApplication.vw_Aktivnosti.DetailsClass.SetValue(this, global::LightSwitchApplication.vw_Aktivnosti.DetailsClass.PropertySetProperties.ID_aktivnost, value);
            }
        }
        
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void ID_aktivnost_IsReadOnly(ref bool result);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void ID_aktivnost_Validate(global::Microsoft.LightSwitch.EntityValidationResultsBuilder results);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void ID_aktivnost_Changed();

        /// <summary>
        /// No Modeled Description Available
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.1.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.Nullable<int> Br_prostorija
        {
            get
            {
                return global::LightSwitchApplication.vw_Aktivnosti.DetailsClass.GetValue(this, global::LightSwitchApplication.vw_Aktivnosti.DetailsClass.PropertySetProperties.Br_prostorija);
            }
            set
            {
                global::LightSwitchApplication.vw_Aktivnosti.DetailsClass.SetValue(this, global::LightSwitchApplication.vw_Aktivnosti.DetailsClass.PropertySetProperties.Br_prostorija, value);
            }
        }
        
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Br_prostorija_IsReadOnly(ref bool result);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Br_prostorija_Validate(global::Microsoft.LightSwitch.EntityValidationResultsBuilder results);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Br_prostorija_Changed();

        /// <summary>
        /// No Modeled Description Available
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.1.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public string Opis
        {
            get
            {
                return global::LightSwitchApplication.vw_Aktivnosti.DetailsClass.GetValue(this, global::LightSwitchApplication.vw_Aktivnosti.DetailsClass.PropertySetProperties.Opis);
            }
            set
            {
                global::LightSwitchApplication.vw_Aktivnosti.DetailsClass.SetValue(this, global::LightSwitchApplication.vw_Aktivnosti.DetailsClass.PropertySetProperties.Opis, value);
            }
        }
        
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Opis_IsReadOnly(ref bool result);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Opis_Validate(global::Microsoft.LightSwitch.EntityValidationResultsBuilder results);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Opis_Changed();

        /// <summary>
        /// No Modeled Description Available
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.1.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public string Ime
        {
            get
            {
                return global::LightSwitchApplication.vw_Aktivnosti.DetailsClass.GetValue(this, global::LightSwitchApplication.vw_Aktivnosti.DetailsClass.PropertySetProperties.Ime);
            }
            set
            {
                global::LightSwitchApplication.vw_Aktivnosti.DetailsClass.SetValue(this, global::LightSwitchApplication.vw_Aktivnosti.DetailsClass.PropertySetProperties.Ime, value);
            }
        }
        
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Ime_IsReadOnly(ref bool result);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Ime_Validate(global::Microsoft.LightSwitch.EntityValidationResultsBuilder results);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Ime_Changed();

        /// <summary>
        /// No Modeled Description Available
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.1.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public string Profesor_Ime
        {
            get
            {
                return global::LightSwitchApplication.vw_Aktivnosti.DetailsClass.GetValue(this, global::LightSwitchApplication.vw_Aktivnosti.DetailsClass.PropertySetProperties.Profesor_Ime);
            }
            set
            {
                global::LightSwitchApplication.vw_Aktivnosti.DetailsClass.SetValue(this, global::LightSwitchApplication.vw_Aktivnosti.DetailsClass.PropertySetProperties.Profesor_Ime, value);
            }
        }
        
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Profesor_Ime_IsReadOnly(ref bool result);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Profesor_Ime_Validate(global::Microsoft.LightSwitch.EntityValidationResultsBuilder results);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Profesor_Ime_Changed();

        /// <summary>
        /// No Modeled Description Available
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.1.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.Nullable<global::System.DateTime> Vreme_pocetok
        {
            get
            {
                return global::LightSwitchApplication.vw_Aktivnosti.DetailsClass.GetValue(this, global::LightSwitchApplication.vw_Aktivnosti.DetailsClass.PropertySetProperties.Vreme_pocetok);
            }
            set
            {
                global::LightSwitchApplication.vw_Aktivnosti.DetailsClass.SetValue(this, global::LightSwitchApplication.vw_Aktivnosti.DetailsClass.PropertySetProperties.Vreme_pocetok, value);
            }
        }
        
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Vreme_pocetok_IsReadOnly(ref bool result);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Vreme_pocetok_Validate(global::Microsoft.LightSwitch.EntityValidationResultsBuilder results);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Vreme_pocetok_Changed();

        /// <summary>
        /// No Modeled Description Available
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.1.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.Nullable<global::System.DateTime> Vreme_kraj
        {
            get
            {
                return global::LightSwitchApplication.vw_Aktivnosti.DetailsClass.GetValue(this, global::LightSwitchApplication.vw_Aktivnosti.DetailsClass.PropertySetProperties.Vreme_kraj);
            }
            set
            {
                global::LightSwitchApplication.vw_Aktivnosti.DetailsClass.SetValue(this, global::LightSwitchApplication.vw_Aktivnosti.DetailsClass.PropertySetProperties.Vreme_kraj, value);
            }
        }
        
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Vreme_kraj_IsReadOnly(ref bool result);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Vreme_kraj_Validate(global::Microsoft.LightSwitch.EntityValidationResultsBuilder results);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Vreme_kraj_Changed();

        /// <summary>
        /// No Modeled Description Available
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.1.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.Nullable<bool> otkazan
        {
            get
            {
                return global::LightSwitchApplication.vw_Aktivnosti.DetailsClass.GetValue(this, global::LightSwitchApplication.vw_Aktivnosti.DetailsClass.PropertySetProperties.otkazan);
            }
            set
            {
                global::LightSwitchApplication.vw_Aktivnosti.DetailsClass.SetValue(this, global::LightSwitchApplication.vw_Aktivnosti.DetailsClass.PropertySetProperties.otkazan, value);
            }
        }
        
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void otkazan_IsReadOnly(ref bool result);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void otkazan_Validate(global::Microsoft.LightSwitch.EntityValidationResultsBuilder results);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void otkazan_Changed();

        /// <summary>
        /// No Modeled Description Available
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.1.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public string Den
        {
            get
            {
                return global::LightSwitchApplication.vw_Aktivnosti.DetailsClass.GetValue(this, global::LightSwitchApplication.vw_Aktivnosti.DetailsClass.PropertySetProperties.Den);
            }
            set
            {
                global::LightSwitchApplication.vw_Aktivnosti.DetailsClass.SetValue(this, global::LightSwitchApplication.vw_Aktivnosti.DetailsClass.PropertySetProperties.Den, value);
            }
        }
        
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Den_IsReadOnly(ref bool result);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Den_Validate(global::Microsoft.LightSwitch.EntityValidationResultsBuilder results);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Den_Changed();

        /// <summary>
        /// No Modeled Description Available
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.1.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.Nullable<bool> Povtoruvacki
        {
            get
            {
                return global::LightSwitchApplication.vw_Aktivnosti.DetailsClass.GetValue(this, global::LightSwitchApplication.vw_Aktivnosti.DetailsClass.PropertySetProperties.Povtoruvacki);
            }
            set
            {
                global::LightSwitchApplication.vw_Aktivnosti.DetailsClass.SetValue(this, global::LightSwitchApplication.vw_Aktivnosti.DetailsClass.PropertySetProperties.Povtoruvacki, value);
            }
        }
        
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Povtoruvacki_IsReadOnly(ref bool result);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Povtoruvacki_Validate(global::Microsoft.LightSwitch.EntityValidationResultsBuilder results);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Povtoruvacki_Changed();

        /// <summary>
        /// No Modeled Description Available
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.1.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public int ID_Den
        {
            get
            {
                return global::LightSwitchApplication.vw_Aktivnosti.DetailsClass.GetValue(this, global::LightSwitchApplication.vw_Aktivnosti.DetailsClass.PropertySetProperties.ID_Den);
            }
            set
            {
                global::LightSwitchApplication.vw_Aktivnosti.DetailsClass.SetValue(this, global::LightSwitchApplication.vw_Aktivnosti.DetailsClass.PropertySetProperties.ID_Den, value);
            }
        }
        
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void ID_Den_IsReadOnly(ref bool result);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void ID_Den_Validate(global::Microsoft.LightSwitch.EntityValidationResultsBuilder results);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void ID_Den_Changed();

        #endregion
    
        #region Details Class
    
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        [global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1034:NestedTypesShouldNotBeVisible")]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.1.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public sealed class DetailsClass : global::Microsoft.LightSwitch.Details.Framework.Base.EntityDetails<
                global::LightSwitchApplication.vw_Aktivnosti,
                global::LightSwitchApplication.vw_Aktivnosti.DetailsClass,
                global::LightSwitchApplication.vw_Aktivnosti.DetailsClass.IImplementation,
                global::LightSwitchApplication.vw_Aktivnosti.DetailsClass.PropertySet,
                global::Microsoft.LightSwitch.Details.Framework.EntityCommandSet<global::LightSwitchApplication.vw_Aktivnosti, global::LightSwitchApplication.vw_Aktivnosti.DetailsClass>,
                global::Microsoft.LightSwitch.Details.Framework.EntityMethodSet<global::LightSwitchApplication.vw_Aktivnosti, global::LightSwitchApplication.vw_Aktivnosti.DetailsClass>>
        {
    
            static DetailsClass()
            {
                var initializeEntry = global::LightSwitchApplication.vw_Aktivnosti.DetailsClass.PropertySetProperties.ID_aktivnost;
            }
    
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private static readonly global::Microsoft.LightSwitch.Details.Framework.Base.EntityDetails<global::LightSwitchApplication.vw_Aktivnosti, global::LightSwitchApplication.vw_Aktivnosti.DetailsClass>.Entry
                __vw_AktivnostiEntry = new global::Microsoft.LightSwitch.Details.Framework.Base.EntityDetails<global::LightSwitchApplication.vw_Aktivnosti, global::LightSwitchApplication.vw_Aktivnosti.DetailsClass>.Entry(
                    global::LightSwitchApplication.vw_Aktivnosti.DetailsClass.__vw_Aktivnosti_CreateNew,
                    global::LightSwitchApplication.vw_Aktivnosti.DetailsClass.__vw_Aktivnosti_Created,
                    global::LightSwitchApplication.vw_Aktivnosti.DetailsClass.__vw_Aktivnosti_AllowSaveWithErrors);
            private static global::LightSwitchApplication.vw_Aktivnosti __vw_Aktivnosti_CreateNew(global::Microsoft.LightSwitch.Framework.EntitySet<global::LightSwitchApplication.vw_Aktivnosti> es)
            {
                return new global::LightSwitchApplication.vw_Aktivnosti(es);
            }
            private static void __vw_Aktivnosti_Created(global::LightSwitchApplication.vw_Aktivnosti e)
            {
                e.vw_Aktivnosti_Created();
            }
            private static bool __vw_Aktivnosti_AllowSaveWithErrors(global::LightSwitchApplication.vw_Aktivnosti e)
            {
                bool result = false;
                e.vw_Aktivnosti_AllowSaveWithErrors(ref result);
                return result;
            }
    
            public DetailsClass() : base()
            {
            }
    
            public new global::Microsoft.LightSwitch.Details.Framework.EntityCommandSet<global::LightSwitchApplication.vw_Aktivnosti, global::LightSwitchApplication.vw_Aktivnosti.DetailsClass> Commands
            {
                get
                {
                    return base.Commands;
                }
            }
    
            public new global::Microsoft.LightSwitch.Details.Framework.EntityMethodSet<global::LightSwitchApplication.vw_Aktivnosti, global::LightSwitchApplication.vw_Aktivnosti.DetailsClass> Methods
            {
                get
                {
                    return base.Methods;
                }
            }
    
            public new global::LightSwitchApplication.vw_Aktivnosti.DetailsClass.PropertySet Properties
            {
                get
                {
                    return base.Properties;
                }
            }
    
            [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
            [global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1034:NestedTypesShouldNotBeVisible")]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.1.0.0")]
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public sealed class PropertySet : global::Microsoft.LightSwitch.Details.Framework.Base.EntityPropertySet<global::LightSwitchApplication.vw_Aktivnosti, global::LightSwitchApplication.vw_Aktivnosti.DetailsClass>
            {
    
                public PropertySet() : base()
                {
                }
    
                public global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.vw_Aktivnosti, global::LightSwitchApplication.vw_Aktivnosti.DetailsClass, int> ID_aktivnost
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.vw_Aktivnosti.DetailsClass.PropertySetProperties.ID_aktivnost) as global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.vw_Aktivnosti, global::LightSwitchApplication.vw_Aktivnosti.DetailsClass, int>;
                    }
                }
                
                public global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.vw_Aktivnosti, global::LightSwitchApplication.vw_Aktivnosti.DetailsClass, global::System.Nullable<int>> Br_prostorija
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.vw_Aktivnosti.DetailsClass.PropertySetProperties.Br_prostorija) as global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.vw_Aktivnosti, global::LightSwitchApplication.vw_Aktivnosti.DetailsClass, global::System.Nullable<int>>;
                    }
                }
                
                public global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.vw_Aktivnosti, global::LightSwitchApplication.vw_Aktivnosti.DetailsClass, string> Opis
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.vw_Aktivnosti.DetailsClass.PropertySetProperties.Opis) as global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.vw_Aktivnosti, global::LightSwitchApplication.vw_Aktivnosti.DetailsClass, string>;
                    }
                }
                
                public global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.vw_Aktivnosti, global::LightSwitchApplication.vw_Aktivnosti.DetailsClass, string> Ime
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.vw_Aktivnosti.DetailsClass.PropertySetProperties.Ime) as global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.vw_Aktivnosti, global::LightSwitchApplication.vw_Aktivnosti.DetailsClass, string>;
                    }
                }
                
                public global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.vw_Aktivnosti, global::LightSwitchApplication.vw_Aktivnosti.DetailsClass, string> Profesor_Ime
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.vw_Aktivnosti.DetailsClass.PropertySetProperties.Profesor_Ime) as global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.vw_Aktivnosti, global::LightSwitchApplication.vw_Aktivnosti.DetailsClass, string>;
                    }
                }
                
                public global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.vw_Aktivnosti, global::LightSwitchApplication.vw_Aktivnosti.DetailsClass, global::System.Nullable<global::System.DateTime>> Vreme_pocetok
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.vw_Aktivnosti.DetailsClass.PropertySetProperties.Vreme_pocetok) as global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.vw_Aktivnosti, global::LightSwitchApplication.vw_Aktivnosti.DetailsClass, global::System.Nullable<global::System.DateTime>>;
                    }
                }
                
                public global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.vw_Aktivnosti, global::LightSwitchApplication.vw_Aktivnosti.DetailsClass, global::System.Nullable<global::System.DateTime>> Vreme_kraj
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.vw_Aktivnosti.DetailsClass.PropertySetProperties.Vreme_kraj) as global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.vw_Aktivnosti, global::LightSwitchApplication.vw_Aktivnosti.DetailsClass, global::System.Nullable<global::System.DateTime>>;
                    }
                }
                
                public global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.vw_Aktivnosti, global::LightSwitchApplication.vw_Aktivnosti.DetailsClass, global::System.Nullable<bool>> otkazan
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.vw_Aktivnosti.DetailsClass.PropertySetProperties.otkazan) as global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.vw_Aktivnosti, global::LightSwitchApplication.vw_Aktivnosti.DetailsClass, global::System.Nullable<bool>>;
                    }
                }
                
                public global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.vw_Aktivnosti, global::LightSwitchApplication.vw_Aktivnosti.DetailsClass, string> Den
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.vw_Aktivnosti.DetailsClass.PropertySetProperties.Den) as global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.vw_Aktivnosti, global::LightSwitchApplication.vw_Aktivnosti.DetailsClass, string>;
                    }
                }
                
                public global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.vw_Aktivnosti, global::LightSwitchApplication.vw_Aktivnosti.DetailsClass, global::System.Nullable<bool>> Povtoruvacki
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.vw_Aktivnosti.DetailsClass.PropertySetProperties.Povtoruvacki) as global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.vw_Aktivnosti, global::LightSwitchApplication.vw_Aktivnosti.DetailsClass, global::System.Nullable<bool>>;
                    }
                }
                
                public global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.vw_Aktivnosti, global::LightSwitchApplication.vw_Aktivnosti.DetailsClass, int> ID_Den
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.vw_Aktivnosti.DetailsClass.PropertySetProperties.ID_Den) as global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.vw_Aktivnosti, global::LightSwitchApplication.vw_Aktivnosti.DetailsClass, int>;
                    }
                }
                
            }
    
            #pragma warning disable 109
            [global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1034:NestedTypesShouldNotBeVisible")]
            public interface IImplementation : global::Microsoft.LightSwitch.Internal.IEntityImplementation
            {
                new int ID_aktivnost { get; set; }
                new global::System.Nullable<int> Br_prostorija { get; set; }
                new string Opis { get; set; }
                new string Ime { get; set; }
                new string Profesor_Ime { get; set; }
                new global::System.Nullable<global::System.DateTime> Vreme_pocetok { get; set; }
                new global::System.Nullable<global::System.DateTime> Vreme_kraj { get; set; }
                new global::System.Nullable<bool> otkazan { get; set; }
                new string Den { get; set; }
                new global::System.Nullable<bool> Povtoruvacki { get; set; }
                new int ID_Den { get; set; }
            }
            #pragma warning restore 109
    
            [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.1.0.0")]
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            internal class PropertySetProperties
            {
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.vw_Aktivnosti, global::LightSwitchApplication.vw_Aktivnosti.DetailsClass, int>.Entry
                    ID_aktivnost = new global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.vw_Aktivnosti, global::LightSwitchApplication.vw_Aktivnosti.DetailsClass, int>.Entry(
                        "ID_aktivnost",
                        global::LightSwitchApplication.vw_Aktivnosti.DetailsClass.PropertySetProperties._ID_aktivnost_Stub,
                        global::LightSwitchApplication.vw_Aktivnosti.DetailsClass.PropertySetProperties._ID_aktivnost_ComputeIsReadOnly,
                        global::LightSwitchApplication.vw_Aktivnosti.DetailsClass.PropertySetProperties._ID_aktivnost_Validate,
                        global::LightSwitchApplication.vw_Aktivnosti.DetailsClass.PropertySetProperties._ID_aktivnost_GetImplementationValue,
                        global::LightSwitchApplication.vw_Aktivnosti.DetailsClass.PropertySetProperties._ID_aktivnost_SetImplementationValue,
                        global::LightSwitchApplication.vw_Aktivnosti.DetailsClass.PropertySetProperties._ID_aktivnost_OnValueChanged);
                private static void _ID_aktivnost_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.vw_Aktivnosti.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.vw_Aktivnosti, global::LightSwitchApplication.vw_Aktivnosti.DetailsClass, int>.Data> c, global::LightSwitchApplication.vw_Aktivnosti.DetailsClass d, object sf)
                {
                    c(d, ref d._ID_aktivnost, sf);
                }
                private static bool _ID_aktivnost_ComputeIsReadOnly(global::LightSwitchApplication.vw_Aktivnosti e)
                {
                    bool result = false;
                    e.ID_aktivnost_IsReadOnly(ref result);
                    return result;
                }
                private static void _ID_aktivnost_Validate(global::LightSwitchApplication.vw_Aktivnosti e, global::Microsoft.LightSwitch.EntityValidationResultsBuilder r)
                {
                    e.ID_aktivnost_Validate(r);
                }
                private static int _ID_aktivnost_GetImplementationValue(global::LightSwitchApplication.vw_Aktivnosti.DetailsClass d)
                {
                    return d.ImplementationEntity.ID_aktivnost;
                }
                private static void _ID_aktivnost_SetImplementationValue(global::LightSwitchApplication.vw_Aktivnosti.DetailsClass d, int v)
                {
                    d.ImplementationEntity.ID_aktivnost = v;
                }
                private static void _ID_aktivnost_OnValueChanged(global::LightSwitchApplication.vw_Aktivnosti e)
                {
                    e.ID_aktivnost_Changed();
                }
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.vw_Aktivnosti, global::LightSwitchApplication.vw_Aktivnosti.DetailsClass, global::System.Nullable<int>>.Entry
                    Br_prostorija = new global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.vw_Aktivnosti, global::LightSwitchApplication.vw_Aktivnosti.DetailsClass, global::System.Nullable<int>>.Entry(
                        "Br_prostorija",
                        global::LightSwitchApplication.vw_Aktivnosti.DetailsClass.PropertySetProperties._Br_prostorija_Stub,
                        global::LightSwitchApplication.vw_Aktivnosti.DetailsClass.PropertySetProperties._Br_prostorija_ComputeIsReadOnly,
                        global::LightSwitchApplication.vw_Aktivnosti.DetailsClass.PropertySetProperties._Br_prostorija_Validate,
                        global::LightSwitchApplication.vw_Aktivnosti.DetailsClass.PropertySetProperties._Br_prostorija_GetImplementationValue,
                        global::LightSwitchApplication.vw_Aktivnosti.DetailsClass.PropertySetProperties._Br_prostorija_SetImplementationValue,
                        global::LightSwitchApplication.vw_Aktivnosti.DetailsClass.PropertySetProperties._Br_prostorija_OnValueChanged);
                private static void _Br_prostorija_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.vw_Aktivnosti.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.vw_Aktivnosti, global::LightSwitchApplication.vw_Aktivnosti.DetailsClass, global::System.Nullable<int>>.Data> c, global::LightSwitchApplication.vw_Aktivnosti.DetailsClass d, object sf)
                {
                    c(d, ref d._Br_prostorija, sf);
                }
                private static bool _Br_prostorija_ComputeIsReadOnly(global::LightSwitchApplication.vw_Aktivnosti e)
                {
                    bool result = false;
                    e.Br_prostorija_IsReadOnly(ref result);
                    return result;
                }
                private static void _Br_prostorija_Validate(global::LightSwitchApplication.vw_Aktivnosti e, global::Microsoft.LightSwitch.EntityValidationResultsBuilder r)
                {
                    e.Br_prostorija_Validate(r);
                }
                private static global::System.Nullable<int> _Br_prostorija_GetImplementationValue(global::LightSwitchApplication.vw_Aktivnosti.DetailsClass d)
                {
                    return d.ImplementationEntity.Br_prostorija;
                }
                private static void _Br_prostorija_SetImplementationValue(global::LightSwitchApplication.vw_Aktivnosti.DetailsClass d, global::System.Nullable<int> v)
                {
                    d.ImplementationEntity.Br_prostorija = v;
                }
                private static void _Br_prostorija_OnValueChanged(global::LightSwitchApplication.vw_Aktivnosti e)
                {
                    e.Br_prostorija_Changed();
                }
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.vw_Aktivnosti, global::LightSwitchApplication.vw_Aktivnosti.DetailsClass, string>.Entry
                    Opis = new global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.vw_Aktivnosti, global::LightSwitchApplication.vw_Aktivnosti.DetailsClass, string>.Entry(
                        "Opis",
                        global::LightSwitchApplication.vw_Aktivnosti.DetailsClass.PropertySetProperties._Opis_Stub,
                        global::LightSwitchApplication.vw_Aktivnosti.DetailsClass.PropertySetProperties._Opis_ComputeIsReadOnly,
                        global::LightSwitchApplication.vw_Aktivnosti.DetailsClass.PropertySetProperties._Opis_Validate,
                        global::LightSwitchApplication.vw_Aktivnosti.DetailsClass.PropertySetProperties._Opis_GetImplementationValue,
                        global::LightSwitchApplication.vw_Aktivnosti.DetailsClass.PropertySetProperties._Opis_SetImplementationValue,
                        global::LightSwitchApplication.vw_Aktivnosti.DetailsClass.PropertySetProperties._Opis_OnValueChanged);
                private static void _Opis_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.vw_Aktivnosti.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.vw_Aktivnosti, global::LightSwitchApplication.vw_Aktivnosti.DetailsClass, string>.Data> c, global::LightSwitchApplication.vw_Aktivnosti.DetailsClass d, object sf)
                {
                    c(d, ref d._Opis, sf);
                }
                private static bool _Opis_ComputeIsReadOnly(global::LightSwitchApplication.vw_Aktivnosti e)
                {
                    bool result = false;
                    e.Opis_IsReadOnly(ref result);
                    return result;
                }
                private static void _Opis_Validate(global::LightSwitchApplication.vw_Aktivnosti e, global::Microsoft.LightSwitch.EntityValidationResultsBuilder r)
                {
                    e.Opis_Validate(r);
                }
                private static string _Opis_GetImplementationValue(global::LightSwitchApplication.vw_Aktivnosti.DetailsClass d)
                {
                    return d.ImplementationEntity.Opis;
                }
                private static void _Opis_SetImplementationValue(global::LightSwitchApplication.vw_Aktivnosti.DetailsClass d, string v)
                {
                    d.ImplementationEntity.Opis = v;
                }
                private static void _Opis_OnValueChanged(global::LightSwitchApplication.vw_Aktivnosti e)
                {
                    e.Opis_Changed();
                }
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.vw_Aktivnosti, global::LightSwitchApplication.vw_Aktivnosti.DetailsClass, string>.Entry
                    Ime = new global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.vw_Aktivnosti, global::LightSwitchApplication.vw_Aktivnosti.DetailsClass, string>.Entry(
                        "Ime",
                        global::LightSwitchApplication.vw_Aktivnosti.DetailsClass.PropertySetProperties._Ime_Stub,
                        global::LightSwitchApplication.vw_Aktivnosti.DetailsClass.PropertySetProperties._Ime_ComputeIsReadOnly,
                        global::LightSwitchApplication.vw_Aktivnosti.DetailsClass.PropertySetProperties._Ime_Validate,
                        global::LightSwitchApplication.vw_Aktivnosti.DetailsClass.PropertySetProperties._Ime_GetImplementationValue,
                        global::LightSwitchApplication.vw_Aktivnosti.DetailsClass.PropertySetProperties._Ime_SetImplementationValue,
                        global::LightSwitchApplication.vw_Aktivnosti.DetailsClass.PropertySetProperties._Ime_OnValueChanged);
                private static void _Ime_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.vw_Aktivnosti.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.vw_Aktivnosti, global::LightSwitchApplication.vw_Aktivnosti.DetailsClass, string>.Data> c, global::LightSwitchApplication.vw_Aktivnosti.DetailsClass d, object sf)
                {
                    c(d, ref d._Ime, sf);
                }
                private static bool _Ime_ComputeIsReadOnly(global::LightSwitchApplication.vw_Aktivnosti e)
                {
                    bool result = false;
                    e.Ime_IsReadOnly(ref result);
                    return result;
                }
                private static void _Ime_Validate(global::LightSwitchApplication.vw_Aktivnosti e, global::Microsoft.LightSwitch.EntityValidationResultsBuilder r)
                {
                    e.Ime_Validate(r);
                }
                private static string _Ime_GetImplementationValue(global::LightSwitchApplication.vw_Aktivnosti.DetailsClass d)
                {
                    return d.ImplementationEntity.Ime;
                }
                private static void _Ime_SetImplementationValue(global::LightSwitchApplication.vw_Aktivnosti.DetailsClass d, string v)
                {
                    d.ImplementationEntity.Ime = v;
                }
                private static void _Ime_OnValueChanged(global::LightSwitchApplication.vw_Aktivnosti e)
                {
                    e.Ime_Changed();
                }
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.vw_Aktivnosti, global::LightSwitchApplication.vw_Aktivnosti.DetailsClass, string>.Entry
                    Profesor_Ime = new global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.vw_Aktivnosti, global::LightSwitchApplication.vw_Aktivnosti.DetailsClass, string>.Entry(
                        "Profesor_Ime",
                        global::LightSwitchApplication.vw_Aktivnosti.DetailsClass.PropertySetProperties._Profesor_Ime_Stub,
                        global::LightSwitchApplication.vw_Aktivnosti.DetailsClass.PropertySetProperties._Profesor_Ime_ComputeIsReadOnly,
                        global::LightSwitchApplication.vw_Aktivnosti.DetailsClass.PropertySetProperties._Profesor_Ime_Validate,
                        global::LightSwitchApplication.vw_Aktivnosti.DetailsClass.PropertySetProperties._Profesor_Ime_GetImplementationValue,
                        global::LightSwitchApplication.vw_Aktivnosti.DetailsClass.PropertySetProperties._Profesor_Ime_SetImplementationValue,
                        global::LightSwitchApplication.vw_Aktivnosti.DetailsClass.PropertySetProperties._Profesor_Ime_OnValueChanged);
                private static void _Profesor_Ime_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.vw_Aktivnosti.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.vw_Aktivnosti, global::LightSwitchApplication.vw_Aktivnosti.DetailsClass, string>.Data> c, global::LightSwitchApplication.vw_Aktivnosti.DetailsClass d, object sf)
                {
                    c(d, ref d._Profesor_Ime, sf);
                }
                private static bool _Profesor_Ime_ComputeIsReadOnly(global::LightSwitchApplication.vw_Aktivnosti e)
                {
                    bool result = false;
                    e.Profesor_Ime_IsReadOnly(ref result);
                    return result;
                }
                private static void _Profesor_Ime_Validate(global::LightSwitchApplication.vw_Aktivnosti e, global::Microsoft.LightSwitch.EntityValidationResultsBuilder r)
                {
                    e.Profesor_Ime_Validate(r);
                }
                private static string _Profesor_Ime_GetImplementationValue(global::LightSwitchApplication.vw_Aktivnosti.DetailsClass d)
                {
                    return d.ImplementationEntity.Profesor_Ime;
                }
                private static void _Profesor_Ime_SetImplementationValue(global::LightSwitchApplication.vw_Aktivnosti.DetailsClass d, string v)
                {
                    d.ImplementationEntity.Profesor_Ime = v;
                }
                private static void _Profesor_Ime_OnValueChanged(global::LightSwitchApplication.vw_Aktivnosti e)
                {
                    e.Profesor_Ime_Changed();
                }
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.vw_Aktivnosti, global::LightSwitchApplication.vw_Aktivnosti.DetailsClass, global::System.Nullable<global::System.DateTime>>.Entry
                    Vreme_pocetok = new global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.vw_Aktivnosti, global::LightSwitchApplication.vw_Aktivnosti.DetailsClass, global::System.Nullable<global::System.DateTime>>.Entry(
                        "Vreme_pocetok",
                        global::LightSwitchApplication.vw_Aktivnosti.DetailsClass.PropertySetProperties._Vreme_pocetok_Stub,
                        global::LightSwitchApplication.vw_Aktivnosti.DetailsClass.PropertySetProperties._Vreme_pocetok_ComputeIsReadOnly,
                        global::LightSwitchApplication.vw_Aktivnosti.DetailsClass.PropertySetProperties._Vreme_pocetok_Validate,
                        global::LightSwitchApplication.vw_Aktivnosti.DetailsClass.PropertySetProperties._Vreme_pocetok_GetImplementationValue,
                        global::LightSwitchApplication.vw_Aktivnosti.DetailsClass.PropertySetProperties._Vreme_pocetok_SetImplementationValue,
                        global::LightSwitchApplication.vw_Aktivnosti.DetailsClass.PropertySetProperties._Vreme_pocetok_OnValueChanged);
                private static void _Vreme_pocetok_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.vw_Aktivnosti.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.vw_Aktivnosti, global::LightSwitchApplication.vw_Aktivnosti.DetailsClass, global::System.Nullable<global::System.DateTime>>.Data> c, global::LightSwitchApplication.vw_Aktivnosti.DetailsClass d, object sf)
                {
                    c(d, ref d._Vreme_pocetok, sf);
                }
                private static bool _Vreme_pocetok_ComputeIsReadOnly(global::LightSwitchApplication.vw_Aktivnosti e)
                {
                    bool result = false;
                    e.Vreme_pocetok_IsReadOnly(ref result);
                    return result;
                }
                private static void _Vreme_pocetok_Validate(global::LightSwitchApplication.vw_Aktivnosti e, global::Microsoft.LightSwitch.EntityValidationResultsBuilder r)
                {
                    e.Vreme_pocetok_Validate(r);
                }
                private static global::System.Nullable<global::System.DateTime> _Vreme_pocetok_GetImplementationValue(global::LightSwitchApplication.vw_Aktivnosti.DetailsClass d)
                {
                    return d.ImplementationEntity.Vreme_pocetok;
                }
                private static void _Vreme_pocetok_SetImplementationValue(global::LightSwitchApplication.vw_Aktivnosti.DetailsClass d, global::System.Nullable<global::System.DateTime> v)
                {
                    d.ImplementationEntity.Vreme_pocetok = global::LightSwitchApplication.vw_Aktivnosti.DetailsClass.ClearDateTimeKind(v);
                }
                private static void _Vreme_pocetok_OnValueChanged(global::LightSwitchApplication.vw_Aktivnosti e)
                {
                    e.Vreme_pocetok_Changed();
                }
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.vw_Aktivnosti, global::LightSwitchApplication.vw_Aktivnosti.DetailsClass, global::System.Nullable<global::System.DateTime>>.Entry
                    Vreme_kraj = new global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.vw_Aktivnosti, global::LightSwitchApplication.vw_Aktivnosti.DetailsClass, global::System.Nullable<global::System.DateTime>>.Entry(
                        "Vreme_kraj",
                        global::LightSwitchApplication.vw_Aktivnosti.DetailsClass.PropertySetProperties._Vreme_kraj_Stub,
                        global::LightSwitchApplication.vw_Aktivnosti.DetailsClass.PropertySetProperties._Vreme_kraj_ComputeIsReadOnly,
                        global::LightSwitchApplication.vw_Aktivnosti.DetailsClass.PropertySetProperties._Vreme_kraj_Validate,
                        global::LightSwitchApplication.vw_Aktivnosti.DetailsClass.PropertySetProperties._Vreme_kraj_GetImplementationValue,
                        global::LightSwitchApplication.vw_Aktivnosti.DetailsClass.PropertySetProperties._Vreme_kraj_SetImplementationValue,
                        global::LightSwitchApplication.vw_Aktivnosti.DetailsClass.PropertySetProperties._Vreme_kraj_OnValueChanged);
                private static void _Vreme_kraj_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.vw_Aktivnosti.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.vw_Aktivnosti, global::LightSwitchApplication.vw_Aktivnosti.DetailsClass, global::System.Nullable<global::System.DateTime>>.Data> c, global::LightSwitchApplication.vw_Aktivnosti.DetailsClass d, object sf)
                {
                    c(d, ref d._Vreme_kraj, sf);
                }
                private static bool _Vreme_kraj_ComputeIsReadOnly(global::LightSwitchApplication.vw_Aktivnosti e)
                {
                    bool result = false;
                    e.Vreme_kraj_IsReadOnly(ref result);
                    return result;
                }
                private static void _Vreme_kraj_Validate(global::LightSwitchApplication.vw_Aktivnosti e, global::Microsoft.LightSwitch.EntityValidationResultsBuilder r)
                {
                    e.Vreme_kraj_Validate(r);
                }
                private static global::System.Nullable<global::System.DateTime> _Vreme_kraj_GetImplementationValue(global::LightSwitchApplication.vw_Aktivnosti.DetailsClass d)
                {
                    return d.ImplementationEntity.Vreme_kraj;
                }
                private static void _Vreme_kraj_SetImplementationValue(global::LightSwitchApplication.vw_Aktivnosti.DetailsClass d, global::System.Nullable<global::System.DateTime> v)
                {
                    d.ImplementationEntity.Vreme_kraj = global::LightSwitchApplication.vw_Aktivnosti.DetailsClass.ClearDateTimeKind(v);
                }
                private static void _Vreme_kraj_OnValueChanged(global::LightSwitchApplication.vw_Aktivnosti e)
                {
                    e.Vreme_kraj_Changed();
                }
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.vw_Aktivnosti, global::LightSwitchApplication.vw_Aktivnosti.DetailsClass, global::System.Nullable<bool>>.Entry
                    otkazan = new global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.vw_Aktivnosti, global::LightSwitchApplication.vw_Aktivnosti.DetailsClass, global::System.Nullable<bool>>.Entry(
                        "otkazan",
                        global::LightSwitchApplication.vw_Aktivnosti.DetailsClass.PropertySetProperties._otkazan_Stub,
                        global::LightSwitchApplication.vw_Aktivnosti.DetailsClass.PropertySetProperties._otkazan_ComputeIsReadOnly,
                        global::LightSwitchApplication.vw_Aktivnosti.DetailsClass.PropertySetProperties._otkazan_Validate,
                        global::LightSwitchApplication.vw_Aktivnosti.DetailsClass.PropertySetProperties._otkazan_GetImplementationValue,
                        global::LightSwitchApplication.vw_Aktivnosti.DetailsClass.PropertySetProperties._otkazan_SetImplementationValue,
                        global::LightSwitchApplication.vw_Aktivnosti.DetailsClass.PropertySetProperties._otkazan_OnValueChanged);
                private static void _otkazan_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.vw_Aktivnosti.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.vw_Aktivnosti, global::LightSwitchApplication.vw_Aktivnosti.DetailsClass, global::System.Nullable<bool>>.Data> c, global::LightSwitchApplication.vw_Aktivnosti.DetailsClass d, object sf)
                {
                    c(d, ref d._otkazan, sf);
                }
                private static bool _otkazan_ComputeIsReadOnly(global::LightSwitchApplication.vw_Aktivnosti e)
                {
                    bool result = false;
                    e.otkazan_IsReadOnly(ref result);
                    return result;
                }
                private static void _otkazan_Validate(global::LightSwitchApplication.vw_Aktivnosti e, global::Microsoft.LightSwitch.EntityValidationResultsBuilder r)
                {
                    e.otkazan_Validate(r);
                }
                private static global::System.Nullable<bool> _otkazan_GetImplementationValue(global::LightSwitchApplication.vw_Aktivnosti.DetailsClass d)
                {
                    return d.ImplementationEntity.otkazan;
                }
                private static void _otkazan_SetImplementationValue(global::LightSwitchApplication.vw_Aktivnosti.DetailsClass d, global::System.Nullable<bool> v)
                {
                    d.ImplementationEntity.otkazan = v;
                }
                private static void _otkazan_OnValueChanged(global::LightSwitchApplication.vw_Aktivnosti e)
                {
                    e.otkazan_Changed();
                }
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.vw_Aktivnosti, global::LightSwitchApplication.vw_Aktivnosti.DetailsClass, string>.Entry
                    Den = new global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.vw_Aktivnosti, global::LightSwitchApplication.vw_Aktivnosti.DetailsClass, string>.Entry(
                        "Den",
                        global::LightSwitchApplication.vw_Aktivnosti.DetailsClass.PropertySetProperties._Den_Stub,
                        global::LightSwitchApplication.vw_Aktivnosti.DetailsClass.PropertySetProperties._Den_ComputeIsReadOnly,
                        global::LightSwitchApplication.vw_Aktivnosti.DetailsClass.PropertySetProperties._Den_Validate,
                        global::LightSwitchApplication.vw_Aktivnosti.DetailsClass.PropertySetProperties._Den_GetImplementationValue,
                        global::LightSwitchApplication.vw_Aktivnosti.DetailsClass.PropertySetProperties._Den_SetImplementationValue,
                        global::LightSwitchApplication.vw_Aktivnosti.DetailsClass.PropertySetProperties._Den_OnValueChanged);
                private static void _Den_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.vw_Aktivnosti.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.vw_Aktivnosti, global::LightSwitchApplication.vw_Aktivnosti.DetailsClass, string>.Data> c, global::LightSwitchApplication.vw_Aktivnosti.DetailsClass d, object sf)
                {
                    c(d, ref d._Den, sf);
                }
                private static bool _Den_ComputeIsReadOnly(global::LightSwitchApplication.vw_Aktivnosti e)
                {
                    bool result = false;
                    e.Den_IsReadOnly(ref result);
                    return result;
                }
                private static void _Den_Validate(global::LightSwitchApplication.vw_Aktivnosti e, global::Microsoft.LightSwitch.EntityValidationResultsBuilder r)
                {
                    e.Den_Validate(r);
                }
                private static string _Den_GetImplementationValue(global::LightSwitchApplication.vw_Aktivnosti.DetailsClass d)
                {
                    return d.ImplementationEntity.Den;
                }
                private static void _Den_SetImplementationValue(global::LightSwitchApplication.vw_Aktivnosti.DetailsClass d, string v)
                {
                    d.ImplementationEntity.Den = v;
                }
                private static void _Den_OnValueChanged(global::LightSwitchApplication.vw_Aktivnosti e)
                {
                    e.Den_Changed();
                }
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.vw_Aktivnosti, global::LightSwitchApplication.vw_Aktivnosti.DetailsClass, global::System.Nullable<bool>>.Entry
                    Povtoruvacki = new global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.vw_Aktivnosti, global::LightSwitchApplication.vw_Aktivnosti.DetailsClass, global::System.Nullable<bool>>.Entry(
                        "Povtoruvacki",
                        global::LightSwitchApplication.vw_Aktivnosti.DetailsClass.PropertySetProperties._Povtoruvacki_Stub,
                        global::LightSwitchApplication.vw_Aktivnosti.DetailsClass.PropertySetProperties._Povtoruvacki_ComputeIsReadOnly,
                        global::LightSwitchApplication.vw_Aktivnosti.DetailsClass.PropertySetProperties._Povtoruvacki_Validate,
                        global::LightSwitchApplication.vw_Aktivnosti.DetailsClass.PropertySetProperties._Povtoruvacki_GetImplementationValue,
                        global::LightSwitchApplication.vw_Aktivnosti.DetailsClass.PropertySetProperties._Povtoruvacki_SetImplementationValue,
                        global::LightSwitchApplication.vw_Aktivnosti.DetailsClass.PropertySetProperties._Povtoruvacki_OnValueChanged);
                private static void _Povtoruvacki_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.vw_Aktivnosti.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.vw_Aktivnosti, global::LightSwitchApplication.vw_Aktivnosti.DetailsClass, global::System.Nullable<bool>>.Data> c, global::LightSwitchApplication.vw_Aktivnosti.DetailsClass d, object sf)
                {
                    c(d, ref d._Povtoruvacki, sf);
                }
                private static bool _Povtoruvacki_ComputeIsReadOnly(global::LightSwitchApplication.vw_Aktivnosti e)
                {
                    bool result = false;
                    e.Povtoruvacki_IsReadOnly(ref result);
                    return result;
                }
                private static void _Povtoruvacki_Validate(global::LightSwitchApplication.vw_Aktivnosti e, global::Microsoft.LightSwitch.EntityValidationResultsBuilder r)
                {
                    e.Povtoruvacki_Validate(r);
                }
                private static global::System.Nullable<bool> _Povtoruvacki_GetImplementationValue(global::LightSwitchApplication.vw_Aktivnosti.DetailsClass d)
                {
                    return d.ImplementationEntity.Povtoruvacki;
                }
                private static void _Povtoruvacki_SetImplementationValue(global::LightSwitchApplication.vw_Aktivnosti.DetailsClass d, global::System.Nullable<bool> v)
                {
                    d.ImplementationEntity.Povtoruvacki = v;
                }
                private static void _Povtoruvacki_OnValueChanged(global::LightSwitchApplication.vw_Aktivnosti e)
                {
                    e.Povtoruvacki_Changed();
                }
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.vw_Aktivnosti, global::LightSwitchApplication.vw_Aktivnosti.DetailsClass, int>.Entry
                    ID_Den = new global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.vw_Aktivnosti, global::LightSwitchApplication.vw_Aktivnosti.DetailsClass, int>.Entry(
                        "ID_Den",
                        global::LightSwitchApplication.vw_Aktivnosti.DetailsClass.PropertySetProperties._ID_Den_Stub,
                        global::LightSwitchApplication.vw_Aktivnosti.DetailsClass.PropertySetProperties._ID_Den_ComputeIsReadOnly,
                        global::LightSwitchApplication.vw_Aktivnosti.DetailsClass.PropertySetProperties._ID_Den_Validate,
                        global::LightSwitchApplication.vw_Aktivnosti.DetailsClass.PropertySetProperties._ID_Den_GetImplementationValue,
                        global::LightSwitchApplication.vw_Aktivnosti.DetailsClass.PropertySetProperties._ID_Den_SetImplementationValue,
                        global::LightSwitchApplication.vw_Aktivnosti.DetailsClass.PropertySetProperties._ID_Den_OnValueChanged);
                private static void _ID_Den_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.vw_Aktivnosti.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.vw_Aktivnosti, global::LightSwitchApplication.vw_Aktivnosti.DetailsClass, int>.Data> c, global::LightSwitchApplication.vw_Aktivnosti.DetailsClass d, object sf)
                {
                    c(d, ref d._ID_Den, sf);
                }
                private static bool _ID_Den_ComputeIsReadOnly(global::LightSwitchApplication.vw_Aktivnosti e)
                {
                    bool result = false;
                    e.ID_Den_IsReadOnly(ref result);
                    return result;
                }
                private static void _ID_Den_Validate(global::LightSwitchApplication.vw_Aktivnosti e, global::Microsoft.LightSwitch.EntityValidationResultsBuilder r)
                {
                    e.ID_Den_Validate(r);
                }
                private static int _ID_Den_GetImplementationValue(global::LightSwitchApplication.vw_Aktivnosti.DetailsClass d)
                {
                    return d.ImplementationEntity.ID_Den;
                }
                private static void _ID_Den_SetImplementationValue(global::LightSwitchApplication.vw_Aktivnosti.DetailsClass d, int v)
                {
                    d.ImplementationEntity.ID_Den = v;
                }
                private static void _ID_Den_OnValueChanged(global::LightSwitchApplication.vw_Aktivnosti e)
                {
                    e.ID_Den_Changed();
                }
    
            }
    
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.vw_Aktivnosti, global::LightSwitchApplication.vw_Aktivnosti.DetailsClass, int>.Data _ID_aktivnost;
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.vw_Aktivnosti, global::LightSwitchApplication.vw_Aktivnosti.DetailsClass, global::System.Nullable<int>>.Data _Br_prostorija;
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.vw_Aktivnosti, global::LightSwitchApplication.vw_Aktivnosti.DetailsClass, string>.Data _Opis;
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.vw_Aktivnosti, global::LightSwitchApplication.vw_Aktivnosti.DetailsClass, string>.Data _Ime;
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.vw_Aktivnosti, global::LightSwitchApplication.vw_Aktivnosti.DetailsClass, string>.Data _Profesor_Ime;
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.vw_Aktivnosti, global::LightSwitchApplication.vw_Aktivnosti.DetailsClass, global::System.Nullable<global::System.DateTime>>.Data _Vreme_pocetok;
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.vw_Aktivnosti, global::LightSwitchApplication.vw_Aktivnosti.DetailsClass, global::System.Nullable<global::System.DateTime>>.Data _Vreme_kraj;
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.vw_Aktivnosti, global::LightSwitchApplication.vw_Aktivnosti.DetailsClass, global::System.Nullable<bool>>.Data _otkazan;
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.vw_Aktivnosti, global::LightSwitchApplication.vw_Aktivnosti.DetailsClass, string>.Data _Den;
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.vw_Aktivnosti, global::LightSwitchApplication.vw_Aktivnosti.DetailsClass, global::System.Nullable<bool>>.Data _Povtoruvacki;
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.vw_Aktivnosti, global::LightSwitchApplication.vw_Aktivnosti.DetailsClass, int>.Data _ID_Den;
            
        }
    
        #endregion
    }
    
    #endregion
}
