

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LightSwitchApplication
{
    #region Entities
    
    /// <summary>
    /// No Modeled Description Available
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.1.0.0")]
    public sealed partial class Den : global::Microsoft.LightSwitch.Framework.Base.EntityObject<global::LightSwitchApplication.Den, global::LightSwitchApplication.Den.DetailsClass>
    {
        #region Constructors
    
        /// <summary>
        /// Initializes a new instance of the Den entity.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.1.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public Den()
            : this(null)
        {
        }
    
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.1.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public Den(global::Microsoft.LightSwitch.Framework.EntitySet<global::LightSwitchApplication.Den> entitySet)
            : base(entitySet)
        {
            global::LightSwitchApplication.Den.DetailsClass.Initialize(this);
        }
    
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Den_Created();
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Den_AllowSaveWithErrors(ref bool result);
    
        #endregion
    
        #region Private Properties
        
        /// <summary>
        /// Gets the Application object for this application.  The Application object provides access to active screens, methods to open screens and access to the current user.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.1.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::Microsoft.LightSwitch.IApplication<global::LightSwitchApplication.DataWorkspace> Application
        {
            get
            {
                return (global::Microsoft.LightSwitch.IApplication<global::LightSwitchApplication.DataWorkspace>)global::LightSwitchApplication.Application.Current;
            }
        }
        
        /// <summary>
        /// Gets the containing data workspace.  The data workspace provides access to all data sources in the application.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.1.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::LightSwitchApplication.DataWorkspace DataWorkspace
        {
            get
            {
                return (global::LightSwitchApplication.DataWorkspace)this.Details.EntitySet.Details.DataService.Details.DataWorkspace;
            }
        }
        
        #endregion
    
        #region Public Properties
    
        /// <summary>
        /// No Modeled Description Available
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.1.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public int ID_Den
        {
            get
            {
                return global::LightSwitchApplication.Den.DetailsClass.GetValue(this, global::LightSwitchApplication.Den.DetailsClass.PropertySetProperties.ID_Den);
            }
        }
        
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void ID_Den_IsReadOnly(ref bool result);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void ID_Den_Validate(global::Microsoft.LightSwitch.EntityValidationResultsBuilder results);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void ID_Den_Changed();

        /// <summary>
        /// No Modeled Description Available
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.1.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public string Den1
        {
            get
            {
                return global::LightSwitchApplication.Den.DetailsClass.GetValue(this, global::LightSwitchApplication.Den.DetailsClass.PropertySetProperties.Den1);
            }
            set
            {
                global::LightSwitchApplication.Den.DetailsClass.SetValue(this, global::LightSwitchApplication.Den.DetailsClass.PropertySetProperties.Den1, value);
            }
        }
        
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Den1_IsReadOnly(ref bool result);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Den1_Validate(global::Microsoft.LightSwitch.EntityValidationResultsBuilder results);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Den1_Changed();

        /// <summary>
        /// No Modeled Description Available
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.1.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::Microsoft.LightSwitch.Framework.EntityCollection<global::LightSwitchApplication.Aktivnost> Aktivnosts
        {
            get
            {
                return global::LightSwitchApplication.Den.DetailsClass.GetValue(this, global::LightSwitchApplication.Den.DetailsClass.PropertySetProperties.Aktivnosts);
            }
        }
        
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.1.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public Microsoft.LightSwitch.IDataServiceQueryable<global::LightSwitchApplication.Aktivnost> AktivnostsQuery
        {
            get
            {
                return global::LightSwitchApplication.Den.DetailsClass.GetQuery(this, global::LightSwitchApplication.Den.DetailsClass.PropertySetProperties.Aktivnosts);
            }
        }

        #endregion
    
        #region Details Class
    
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        [global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1034:NestedTypesShouldNotBeVisible")]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.1.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public sealed class DetailsClass : global::Microsoft.LightSwitch.Details.Framework.Base.EntityDetails<
                global::LightSwitchApplication.Den,
                global::LightSwitchApplication.Den.DetailsClass,
                global::LightSwitchApplication.Den.DetailsClass.IImplementation,
                global::LightSwitchApplication.Den.DetailsClass.PropertySet,
                global::Microsoft.LightSwitch.Details.Framework.EntityCommandSet<global::LightSwitchApplication.Den, global::LightSwitchApplication.Den.DetailsClass>,
                global::Microsoft.LightSwitch.Details.Framework.EntityMethodSet<global::LightSwitchApplication.Den, global::LightSwitchApplication.Den.DetailsClass>>
        {
    
            static DetailsClass()
            {
                var initializeEntry = global::LightSwitchApplication.Den.DetailsClass.PropertySetProperties.ID_Den;
            }
    
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private static readonly global::Microsoft.LightSwitch.Details.Framework.Base.EntityDetails<global::LightSwitchApplication.Den, global::LightSwitchApplication.Den.DetailsClass>.Entry
                __DenEntry = new global::Microsoft.LightSwitch.Details.Framework.Base.EntityDetails<global::LightSwitchApplication.Den, global::LightSwitchApplication.Den.DetailsClass>.Entry(
                    global::LightSwitchApplication.Den.DetailsClass.__Den_CreateNew,
                    global::LightSwitchApplication.Den.DetailsClass.__Den_Created,
                    global::LightSwitchApplication.Den.DetailsClass.__Den_AllowSaveWithErrors);
            private static global::LightSwitchApplication.Den __Den_CreateNew(global::Microsoft.LightSwitch.Framework.EntitySet<global::LightSwitchApplication.Den> es)
            {
                return new global::LightSwitchApplication.Den(es);
            }
            private static void __Den_Created(global::LightSwitchApplication.Den e)
            {
                e.Den_Created();
            }
            private static bool __Den_AllowSaveWithErrors(global::LightSwitchApplication.Den e)
            {
                bool result = false;
                e.Den_AllowSaveWithErrors(ref result);
                return result;
            }
    
            public DetailsClass() : base()
            {
            }
    
            public new global::Microsoft.LightSwitch.Details.Framework.EntityCommandSet<global::LightSwitchApplication.Den, global::LightSwitchApplication.Den.DetailsClass> Commands
            {
                get
                {
                    return base.Commands;
                }
            }
    
            public new global::Microsoft.LightSwitch.Details.Framework.EntityMethodSet<global::LightSwitchApplication.Den, global::LightSwitchApplication.Den.DetailsClass> Methods
            {
                get
                {
                    return base.Methods;
                }
            }
    
            public new global::LightSwitchApplication.Den.DetailsClass.PropertySet Properties
            {
                get
                {
                    return base.Properties;
                }
            }
    
            [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
            [global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1034:NestedTypesShouldNotBeVisible")]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.1.0.0")]
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public sealed class PropertySet : global::Microsoft.LightSwitch.Details.Framework.Base.EntityPropertySet<global::LightSwitchApplication.Den, global::LightSwitchApplication.Den.DetailsClass>
            {
    
                public PropertySet() : base()
                {
                }
    
                public global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Den, global::LightSwitchApplication.Den.DetailsClass, int> ID_Den
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.Den.DetailsClass.PropertySetProperties.ID_Den) as global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Den, global::LightSwitchApplication.Den.DetailsClass, int>;
                    }
                }
                
                public global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Den, global::LightSwitchApplication.Den.DetailsClass, string> Den1
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.Den.DetailsClass.PropertySetProperties.Den1) as global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Den, global::LightSwitchApplication.Den.DetailsClass, string>;
                    }
                }
                
                public global::Microsoft.LightSwitch.Details.Framework.EntityCollectionProperty<global::LightSwitchApplication.Den, global::LightSwitchApplication.Den.DetailsClass, global::LightSwitchApplication.Aktivnost> Aktivnosts
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.Den.DetailsClass.PropertySetProperties.Aktivnosts) as global::Microsoft.LightSwitch.Details.Framework.EntityCollectionProperty<global::LightSwitchApplication.Den, global::LightSwitchApplication.Den.DetailsClass, global::LightSwitchApplication.Aktivnost>;
                    }
                }
                
            }
    
            #pragma warning disable 109
            [global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1034:NestedTypesShouldNotBeVisible")]
            public interface IImplementation : global::Microsoft.LightSwitch.Internal.IEntityImplementation
            {
                new int ID_Den { get; }
                new string Den1 { get; set; }
                new global::System.Collections.IEnumerable Aktivnosts { get; }
            }
            #pragma warning restore 109
    
            [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.1.0.0")]
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            internal class PropertySetProperties
            {
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Den, global::LightSwitchApplication.Den.DetailsClass, int>.Entry
                    ID_Den = new global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Den, global::LightSwitchApplication.Den.DetailsClass, int>.Entry(
                        "ID_Den",
                        global::LightSwitchApplication.Den.DetailsClass.PropertySetProperties._ID_Den_Stub,
                        global::LightSwitchApplication.Den.DetailsClass.PropertySetProperties._ID_Den_ComputeIsReadOnly,
                        global::LightSwitchApplication.Den.DetailsClass.PropertySetProperties._ID_Den_Validate,
                        global::LightSwitchApplication.Den.DetailsClass.PropertySetProperties._ID_Den_GetImplementationValue,
                        null,
                        global::LightSwitchApplication.Den.DetailsClass.PropertySetProperties._ID_Den_OnValueChanged);
                private static void _ID_Den_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.Den.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Den, global::LightSwitchApplication.Den.DetailsClass, int>.Data> c, global::LightSwitchApplication.Den.DetailsClass d, object sf)
                {
                    c(d, ref d._ID_Den, sf);
                }
                private static bool _ID_Den_ComputeIsReadOnly(global::LightSwitchApplication.Den e)
                {
                    bool result = false;
                    e.ID_Den_IsReadOnly(ref result);
                    return result;
                }
                private static void _ID_Den_Validate(global::LightSwitchApplication.Den e, global::Microsoft.LightSwitch.EntityValidationResultsBuilder r)
                {
                    e.ID_Den_Validate(r);
                }
                private static int _ID_Den_GetImplementationValue(global::LightSwitchApplication.Den.DetailsClass d)
                {
                    return d.ImplementationEntity.ID_Den;
                }
                private static void _ID_Den_OnValueChanged(global::LightSwitchApplication.Den e)
                {
                    e.ID_Den_Changed();
                }
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Den, global::LightSwitchApplication.Den.DetailsClass, string>.Entry
                    Den1 = new global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Den, global::LightSwitchApplication.Den.DetailsClass, string>.Entry(
                        "Den1",
                        global::LightSwitchApplication.Den.DetailsClass.PropertySetProperties._Den1_Stub,
                        global::LightSwitchApplication.Den.DetailsClass.PropertySetProperties._Den1_ComputeIsReadOnly,
                        global::LightSwitchApplication.Den.DetailsClass.PropertySetProperties._Den1_Validate,
                        global::LightSwitchApplication.Den.DetailsClass.PropertySetProperties._Den1_GetImplementationValue,
                        global::LightSwitchApplication.Den.DetailsClass.PropertySetProperties._Den1_SetImplementationValue,
                        global::LightSwitchApplication.Den.DetailsClass.PropertySetProperties._Den1_OnValueChanged);
                private static void _Den1_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.Den.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Den, global::LightSwitchApplication.Den.DetailsClass, string>.Data> c, global::LightSwitchApplication.Den.DetailsClass d, object sf)
                {
                    c(d, ref d._Den1, sf);
                }
                private static bool _Den1_ComputeIsReadOnly(global::LightSwitchApplication.Den e)
                {
                    bool result = false;
                    e.Den1_IsReadOnly(ref result);
                    return result;
                }
                private static void _Den1_Validate(global::LightSwitchApplication.Den e, global::Microsoft.LightSwitch.EntityValidationResultsBuilder r)
                {
                    e.Den1_Validate(r);
                }
                private static string _Den1_GetImplementationValue(global::LightSwitchApplication.Den.DetailsClass d)
                {
                    return d.ImplementationEntity.Den1;
                }
                private static void _Den1_SetImplementationValue(global::LightSwitchApplication.Den.DetailsClass d, string v)
                {
                    d.ImplementationEntity.Den1 = v;
                }
                private static void _Den1_OnValueChanged(global::LightSwitchApplication.Den e)
                {
                    e.Den1_Changed();
                }
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityCollectionProperty<global::LightSwitchApplication.Den, global::LightSwitchApplication.Den.DetailsClass, global::LightSwitchApplication.Aktivnost>.Entry
                    Aktivnosts = new global::Microsoft.LightSwitch.Details.Framework.EntityCollectionProperty<global::LightSwitchApplication.Den, global::LightSwitchApplication.Den.DetailsClass, global::LightSwitchApplication.Aktivnost>.Entry(
                        "Aktivnosts",
                        global::LightSwitchApplication.Den.DetailsClass.PropertySetProperties._Aktivnosts_Stub,
                        global::LightSwitchApplication.Den.DetailsClass.PropertySetProperties._Aktivnosts_GetReferencedEntities,
                        global::LightSwitchApplication.Den.DetailsClass.PropertySetProperties._Aktivnosts_GetEntityCollection);
                private static void _Aktivnosts_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.Den.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityCollectionProperty<global::LightSwitchApplication.Den, global::LightSwitchApplication.Den.DetailsClass, global::LightSwitchApplication.Aktivnost>.Data> c, global::LightSwitchApplication.Den.DetailsClass d, object sf)
                {
                    c(d, ref d._Aktivnosts, sf);
                }
                private static global::System.Collections.Generic.IEnumerable<global::LightSwitchApplication.Aktivnost> _Aktivnosts_GetReferencedEntities(global::LightSwitchApplication.Den.DetailsClass d)
                {
                    return d.GetReferencedEntities<global::LightSwitchApplication.Aktivnost, global::LightSwitchApplication.Aktivnost.DetailsClass>(global::LightSwitchApplication.Den.DetailsClass.PropertySetProperties.Aktivnosts, ref d._Aktivnosts);
                }
                private static global::System.Collections.IEnumerable _Aktivnosts_GetEntityCollection(global::LightSwitchApplication.Den.DetailsClass d)
                {
                    return d.ImplementationEntity.Aktivnosts;
                }
    
            }
    
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Den, global::LightSwitchApplication.Den.DetailsClass, int>.Data _ID_Den;
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Den, global::LightSwitchApplication.Den.DetailsClass, string>.Data _Den1;
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityCollectionProperty<global::LightSwitchApplication.Den, global::LightSwitchApplication.Den.DetailsClass, global::LightSwitchApplication.Aktivnost>.Data _Aktivnosts;
            
        }
    
        #endregion
    }
    
    #endregion
}
