//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.ComponentModel;
using System.Data.EntityClient;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Linq;
using System.Runtime.Serialization;
using System.Xml.Serialization;

[assembly: EdmSchemaAttribute()]
#region EDM Relationship Metadata

[assembly: EdmRelationshipAttribute("LightSwitchApplication", "FK_Aktivnost_Predmet", "Predmet", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(LightSwitchApplication.Implementation.Predmet), "Aktivnost", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(LightSwitchApplication.Implementation.Aktivnost), true)]
[assembly: EdmRelationshipAttribute("LightSwitchApplication", "FK_Izbrani_predmeti_Predmet", "Predmet", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(LightSwitchApplication.Implementation.Predmet), "Izbrani_predmeti", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(LightSwitchApplication.Implementation.Izbrani_predmeti), true)]
[assembly: EdmRelationshipAttribute("LightSwitchApplication", "FK_Aktivnost_Profesor", "Profesor", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(LightSwitchApplication.Implementation.Profesor), "Aktivnost", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(LightSwitchApplication.Implementation.Aktivnost), true)]
[assembly: EdmRelationshipAttribute("LightSwitchApplication", "FK_Predmet_Profesor", "Profesor", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(LightSwitchApplication.Implementation.Profesor), "Predmet", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(LightSwitchApplication.Implementation.Predmet), true)]
[assembly: EdmRelationshipAttribute("LightSwitchApplication", "FK_Aktivnost_Prostorija", "Prostorija", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(LightSwitchApplication.Implementation.Prostorija), "Aktivnost", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(LightSwitchApplication.Implementation.Aktivnost), true)]
[assembly: EdmRelationshipAttribute("LightSwitchApplication", "FK_Predmet_Semestar", "Semestar", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(LightSwitchApplication.Implementation.Semestar), "Predmet", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(LightSwitchApplication.Implementation.Predmet), true)]
[assembly: EdmRelationshipAttribute("LightSwitchApplication", "FK_Student_Semestar", "Semestar", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(LightSwitchApplication.Implementation.Semestar), "Student", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(LightSwitchApplication.Implementation.Student), true)]
[assembly: EdmRelationshipAttribute("LightSwitchApplication", "FK_Izbrani_predmeti_Student", "Student", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(LightSwitchApplication.Implementation.Student), "Izbrani_predmeti", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(LightSwitchApplication.Implementation.Izbrani_predmeti), true)]
[assembly: EdmRelationshipAttribute("LightSwitchApplication", "FK_Aktivnost_TipNaAktivnost", "TipNaAktivnost", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(LightSwitchApplication.Implementation.TipNaAktivnost), "Aktivnost", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(LightSwitchApplication.Implementation.Aktivnost), true)]

#endregion

namespace LightSwitchApplication.Implementation
{
    #region Contexts
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    public partial class On_line_rasporedData : ObjectContext
    {
        #region Constructors
    
        /// <summary>
        /// Initializes a new On_line_rasporedData object using the connection string found in the 'On_line_rasporedData' section of the application configuration file.
        /// </summary>
        public On_line_rasporedData() : base("name=On_line_rasporedData", "On_line_rasporedData")
        {
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new On_line_rasporedData object.
        /// </summary>
        public On_line_rasporedData(string connectionString) : base(connectionString, "On_line_rasporedData")
        {
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new On_line_rasporedData object.
        /// </summary>
        public On_line_rasporedData(EntityConnection connection) : base(connection, "On_line_rasporedData")
        {
            OnContextCreated();
        }
    
        #endregion
    
        #region Partial Methods
    
        partial void OnContextCreated();
    
        #endregion
    
        #region ObjectSet Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Aktivnost> Aktivnosts
        {
            get
            {
                if ((_Aktivnosts == null))
                {
                    _Aktivnosts = base.CreateObjectSet<Aktivnost>("Aktivnosts");
                }
                return _Aktivnosts;
            }
        }
        private ObjectSet<Aktivnost> _Aktivnosts;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Izbrani_predmeti> Izbrani_predmetis
        {
            get
            {
                if ((_Izbrani_predmetis == null))
                {
                    _Izbrani_predmetis = base.CreateObjectSet<Izbrani_predmeti>("Izbrani_predmetis");
                }
                return _Izbrani_predmetis;
            }
        }
        private ObjectSet<Izbrani_predmeti> _Izbrani_predmetis;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Predmet> Predmets
        {
            get
            {
                if ((_Predmets == null))
                {
                    _Predmets = base.CreateObjectSet<Predmet>("Predmets");
                }
                return _Predmets;
            }
        }
        private ObjectSet<Predmet> _Predmets;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Profesor> Profesors
        {
            get
            {
                if ((_Profesors == null))
                {
                    _Profesors = base.CreateObjectSet<Profesor>("Profesors");
                }
                return _Profesors;
            }
        }
        private ObjectSet<Profesor> _Profesors;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Prostorija> Prostorijas
        {
            get
            {
                if ((_Prostorijas == null))
                {
                    _Prostorijas = base.CreateObjectSet<Prostorija>("Prostorijas");
                }
                return _Prostorijas;
            }
        }
        private ObjectSet<Prostorija> _Prostorijas;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Semestar> Semestars
        {
            get
            {
                if ((_Semestars == null))
                {
                    _Semestars = base.CreateObjectSet<Semestar>("Semestars");
                }
                return _Semestars;
            }
        }
        private ObjectSet<Semestar> _Semestars;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Student> Students
        {
            get
            {
                if ((_Students == null))
                {
                    _Students = base.CreateObjectSet<Student>("Students");
                }
                return _Students;
            }
        }
        private ObjectSet<Student> _Students;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<sysdiagram> sysdiagrams
        {
            get
            {
                if ((_sysdiagrams == null))
                {
                    _sysdiagrams = base.CreateObjectSet<sysdiagram>("sysdiagrams");
                }
                return _sysdiagrams;
            }
        }
        private ObjectSet<sysdiagram> _sysdiagrams;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<TipNaAktivnost> TipNaAktivnosts
        {
            get
            {
                if ((_TipNaAktivnosts == null))
                {
                    _TipNaAktivnosts = base.CreateObjectSet<TipNaAktivnost>("TipNaAktivnosts");
                }
                return _TipNaAktivnosts;
            }
        }
        private ObjectSet<TipNaAktivnost> _TipNaAktivnosts;

        #endregion

        #region AddTo Methods
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Aktivnosts EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToAktivnosts(Aktivnost aktivnost)
        {
            base.AddObject("Aktivnosts", aktivnost);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Izbrani_predmetis EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToIzbrani_predmetis(Izbrani_predmeti izbrani_predmeti)
        {
            base.AddObject("Izbrani_predmetis", izbrani_predmeti);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Predmets EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToPredmets(Predmet predmet)
        {
            base.AddObject("Predmets", predmet);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Profesors EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToProfesors(Profesor profesor)
        {
            base.AddObject("Profesors", profesor);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Prostorijas EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToProstorijas(Prostorija prostorija)
        {
            base.AddObject("Prostorijas", prostorija);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Semestars EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToSemestars(Semestar semestar)
        {
            base.AddObject("Semestars", semestar);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Students EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToStudents(Student student)
        {
            base.AddObject("Students", student);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the sysdiagrams EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddTosysdiagrams(sysdiagram sysdiagram)
        {
            base.AddObject("sysdiagrams", sysdiagram);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the TipNaAktivnosts EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToTipNaAktivnosts(TipNaAktivnost tipNaAktivnost)
        {
            base.AddObject("TipNaAktivnosts", tipNaAktivnost);
        }

        #endregion

    }

    #endregion

    #region Entities
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="LightSwitchApplication", Name="Aktivnost")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Aktivnost : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Aktivnost object.
        /// </summary>
        /// <param name="iD_aktivnost">Initial value of the ID_aktivnost property.</param>
        /// <param name="iD_predmet">Initial value of the ID_predmet property.</param>
        /// <param name="iD_profesor">Initial value of the ID_profesor property.</param>
        /// <param name="iD_prostorija">Initial value of the ID_prostorija property.</param>
        /// <param name="iD_TipNaAktivnost">Initial value of the ID_TipNaAktivnost property.</param>
        public static Aktivnost CreateAktivnost(global::System.Int32 iD_aktivnost, global::System.String iD_predmet, global::System.Int32 iD_profesor, global::System.Int32 iD_prostorija, global::System.Int32 iD_TipNaAktivnost)
        {
            Aktivnost aktivnost = new Aktivnost();
            aktivnost.ID_aktivnost = iD_aktivnost;
            aktivnost.ID_predmet = iD_predmet;
            aktivnost.ID_profesor = iD_profesor;
            aktivnost.ID_prostorija = iD_prostorija;
            aktivnost.ID_TipNaAktivnost = iD_TipNaAktivnost;
            return aktivnost;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.TimeSpan> Vreme_pocetok
        {
            get
            {
                return _Vreme_pocetok;
            }
            set
            {
                OnVreme_pocetokChanging(value);
                ReportPropertyChanging("Vreme_pocetok");
                _Vreme_pocetok = value;
                ReportPropertyChanged("Vreme_pocetok");
                OnVreme_pocetokChanged();
            }
        }
        private Nullable<global::System.TimeSpan> _Vreme_pocetok;
        partial void OnVreme_pocetokChanging(Nullable<global::System.TimeSpan> value);
        partial void OnVreme_pocetokChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.TimeSpan> Vreme_kraj
        {
            get
            {
                return _Vreme_kraj;
            }
            set
            {
                OnVreme_krajChanging(value);
                ReportPropertyChanging("Vreme_kraj");
                _Vreme_kraj = value;
                ReportPropertyChanged("Vreme_kraj");
                OnVreme_krajChanged();
            }
        }
        private Nullable<global::System.TimeSpan> _Vreme_kraj;
        partial void OnVreme_krajChanging(Nullable<global::System.TimeSpan> value);
        partial void OnVreme_krajChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Den
        {
            get
            {
                return _Den;
            }
            set
            {
                OnDenChanging(value);
                ReportPropertyChanging("Den");
                _Den = value;
                ReportPropertyChanged("Den");
                OnDenChanged();
            }
        }
        private global::System.String _Den;
        partial void OnDenChanging(global::System.String value);
        partial void OnDenChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 ID_aktivnost
        {
            get
            {
                return _ID_aktivnost;
            }
            set
            {
                if (_ID_aktivnost != value)
                {
                    OnID_aktivnostChanging(value);
                    ReportPropertyChanging("ID_aktivnost");
                    _ID_aktivnost = value;
                    ReportPropertyChanged("ID_aktivnost");
                    OnID_aktivnostChanged();
                }
            }
        }
        private global::System.Int32 _ID_aktivnost;
        partial void OnID_aktivnostChanging(global::System.Int32 value);
        partial void OnID_aktivnostChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String ID_predmet
        {
            get
            {
                return _ID_predmet;
            }
            set
            {
                OnID_predmetChanging(value);
                ReportPropertyChanging("ID_predmet");
                _ID_predmet = value;
                ReportPropertyChanged("ID_predmet");
                OnID_predmetChanged();
            }
        }
        private global::System.String _ID_predmet;
        partial void OnID_predmetChanging(global::System.String value);
        partial void OnID_predmetChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 ID_profesor
        {
            get
            {
                return _ID_profesor;
            }
            set
            {
                OnID_profesorChanging(value);
                ReportPropertyChanging("ID_profesor");
                _ID_profesor = value;
                ReportPropertyChanged("ID_profesor");
                OnID_profesorChanged();
            }
        }
        private global::System.Int32 _ID_profesor;
        partial void OnID_profesorChanging(global::System.Int32 value);
        partial void OnID_profesorChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 ID_prostorija
        {
            get
            {
                return _ID_prostorija;
            }
            set
            {
                OnID_prostorijaChanging(value);
                ReportPropertyChanging("ID_prostorija");
                _ID_prostorija = value;
                ReportPropertyChanged("ID_prostorija");
                OnID_prostorijaChanged();
            }
        }
        private global::System.Int32 _ID_prostorija;
        partial void OnID_prostorijaChanging(global::System.Int32 value);
        partial void OnID_prostorijaChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 ID_TipNaAktivnost
        {
            get
            {
                return _ID_TipNaAktivnost;
            }
            set
            {
                OnID_TipNaAktivnostChanging(value);
                ReportPropertyChanging("ID_TipNaAktivnost");
                _ID_TipNaAktivnost = value;
                ReportPropertyChanged("ID_TipNaAktivnost");
                OnID_TipNaAktivnostChanged();
            }
        }
        private global::System.Int32 _ID_TipNaAktivnost;
        partial void OnID_TipNaAktivnostChanging(global::System.Int32 value);
        partial void OnID_TipNaAktivnostChanged();

        #endregion

    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("LightSwitchApplication", "FK_Aktivnost_Predmet", "Predmet")]
        public Predmet Predmet
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Predmet>("LightSwitchApplication.FK_Aktivnost_Predmet", "Predmet").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Predmet>("LightSwitchApplication.FK_Aktivnost_Predmet", "Predmet").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<Predmet> PredmetReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Predmet>("LightSwitchApplication.FK_Aktivnost_Predmet", "Predmet");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<Predmet>("LightSwitchApplication.FK_Aktivnost_Predmet", "Predmet", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("LightSwitchApplication", "FK_Aktivnost_Profesor", "Profesor")]
        public Profesor Profesor
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Profesor>("LightSwitchApplication.FK_Aktivnost_Profesor", "Profesor").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Profesor>("LightSwitchApplication.FK_Aktivnost_Profesor", "Profesor").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<Profesor> ProfesorReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Profesor>("LightSwitchApplication.FK_Aktivnost_Profesor", "Profesor");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<Profesor>("LightSwitchApplication.FK_Aktivnost_Profesor", "Profesor", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("LightSwitchApplication", "FK_Aktivnost_Prostorija", "Prostorija")]
        public Prostorija Prostorija
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Prostorija>("LightSwitchApplication.FK_Aktivnost_Prostorija", "Prostorija").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Prostorija>("LightSwitchApplication.FK_Aktivnost_Prostorija", "Prostorija").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<Prostorija> ProstorijaReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Prostorija>("LightSwitchApplication.FK_Aktivnost_Prostorija", "Prostorija");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<Prostorija>("LightSwitchApplication.FK_Aktivnost_Prostorija", "Prostorija", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("LightSwitchApplication", "FK_Aktivnost_TipNaAktivnost", "TipNaAktivnost")]
        public TipNaAktivnost TipNaAktivnost
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<TipNaAktivnost>("LightSwitchApplication.FK_Aktivnost_TipNaAktivnost", "TipNaAktivnost").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<TipNaAktivnost>("LightSwitchApplication.FK_Aktivnost_TipNaAktivnost", "TipNaAktivnost").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<TipNaAktivnost> TipNaAktivnostReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<TipNaAktivnost>("LightSwitchApplication.FK_Aktivnost_TipNaAktivnost", "TipNaAktivnost");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<TipNaAktivnost>("LightSwitchApplication.FK_Aktivnost_TipNaAktivnost", "TipNaAktivnost", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="LightSwitchApplication", Name="Izbrani_predmeti")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Izbrani_predmeti : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Izbrani_predmeti object.
        /// </summary>
        /// <param name="iD_izbraniPredmeti">Initial value of the ID_izbraniPredmeti property.</param>
        /// <param name="iD_predmet">Initial value of the ID_predmet property.</param>
        /// <param name="br_indeks">Initial value of the Br_indeks property.</param>
        public static Izbrani_predmeti CreateIzbrani_predmeti(global::System.Int32 iD_izbraniPredmeti, global::System.String iD_predmet, global::System.String br_indeks)
        {
            Izbrani_predmeti izbrani_predmeti = new Izbrani_predmeti();
            izbrani_predmeti.ID_izbraniPredmeti = iD_izbraniPredmeti;
            izbrani_predmeti.ID_predmet = iD_predmet;
            izbrani_predmeti.Br_indeks = br_indeks;
            return izbrani_predmeti;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String tekoven_semestar
        {
            get
            {
                return _tekoven_semestar;
            }
            set
            {
                Ontekoven_semestarChanging(value);
                ReportPropertyChanging("tekoven_semestar");
                _tekoven_semestar = value;
                ReportPropertyChanged("tekoven_semestar");
                Ontekoven_semestarChanged();
            }
        }
        private global::System.String _tekoven_semestar;
        partial void Ontekoven_semestarChanging(global::System.String value);
        partial void Ontekoven_semestarChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 ID_izbraniPredmeti
        {
            get
            {
                return _ID_izbraniPredmeti;
            }
            set
            {
                if (_ID_izbraniPredmeti != value)
                {
                    OnID_izbraniPredmetiChanging(value);
                    ReportPropertyChanging("ID_izbraniPredmeti");
                    _ID_izbraniPredmeti = value;
                    ReportPropertyChanged("ID_izbraniPredmeti");
                    OnID_izbraniPredmetiChanged();
                }
            }
        }
        private global::System.Int32 _ID_izbraniPredmeti;
        partial void OnID_izbraniPredmetiChanging(global::System.Int32 value);
        partial void OnID_izbraniPredmetiChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String ID_predmet
        {
            get
            {
                return _ID_predmet;
            }
            set
            {
                OnID_predmetChanging(value);
                ReportPropertyChanging("ID_predmet");
                _ID_predmet = value;
                ReportPropertyChanged("ID_predmet");
                OnID_predmetChanged();
            }
        }
        private global::System.String _ID_predmet;
        partial void OnID_predmetChanging(global::System.String value);
        partial void OnID_predmetChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Br_indeks
        {
            get
            {
                return _Br_indeks;
            }
            set
            {
                OnBr_indeksChanging(value);
                ReportPropertyChanging("Br_indeks");
                _Br_indeks = value;
                ReportPropertyChanged("Br_indeks");
                OnBr_indeksChanged();
            }
        }
        private global::System.String _Br_indeks;
        partial void OnBr_indeksChanging(global::System.String value);
        partial void OnBr_indeksChanged();

        #endregion

    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("LightSwitchApplication", "FK_Izbrani_predmeti_Predmet", "Predmet")]
        public Predmet Predmet
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Predmet>("LightSwitchApplication.FK_Izbrani_predmeti_Predmet", "Predmet").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Predmet>("LightSwitchApplication.FK_Izbrani_predmeti_Predmet", "Predmet").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<Predmet> PredmetReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Predmet>("LightSwitchApplication.FK_Izbrani_predmeti_Predmet", "Predmet");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<Predmet>("LightSwitchApplication.FK_Izbrani_predmeti_Predmet", "Predmet", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("LightSwitchApplication", "FK_Izbrani_predmeti_Student", "Student")]
        public Student Student
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Student>("LightSwitchApplication.FK_Izbrani_predmeti_Student", "Student").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Student>("LightSwitchApplication.FK_Izbrani_predmeti_Student", "Student").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<Student> StudentReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Student>("LightSwitchApplication.FK_Izbrani_predmeti_Student", "Student");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<Student>("LightSwitchApplication.FK_Izbrani_predmeti_Student", "Student", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="LightSwitchApplication", Name="Predmet")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Predmet : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Predmet object.
        /// </summary>
        /// <param name="iD_predmet">Initial value of the ID_predmet property.</param>
        /// <param name="iD_profesor">Initial value of the ID_profesor property.</param>
        /// <param name="iD_semestar">Initial value of the ID_semestar property.</param>
        public static Predmet CreatePredmet(global::System.String iD_predmet, global::System.Int32 iD_profesor, global::System.Int32 iD_semestar)
        {
            Predmet predmet = new Predmet();
            predmet.ID_predmet = iD_predmet;
            predmet.ID_profesor = iD_profesor;
            predmet.ID_semestar = iD_semestar;
            return predmet;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String ID_predmet
        {
            get
            {
                return _ID_predmet;
            }
            set
            {
                if (_ID_predmet != value)
                {
                    OnID_predmetChanging(value);
                    ReportPropertyChanging("ID_predmet");
                    _ID_predmet = value;
                    ReportPropertyChanged("ID_predmet");
                    OnID_predmetChanged();
                }
            }
        }
        private global::System.String _ID_predmet;
        partial void OnID_predmetChanging(global::System.String value);
        partial void OnID_predmetChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Ime
        {
            get
            {
                return _Ime;
            }
            set
            {
                OnImeChanging(value);
                ReportPropertyChanging("Ime");
                _Ime = value;
                ReportPropertyChanged("Ime");
                OnImeChanged();
            }
        }
        private global::System.String _Ime;
        partial void OnImeChanging(global::System.String value);
        partial void OnImeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Status
        {
            get
            {
                return _Status;
            }
            set
            {
                OnStatusChanging(value);
                ReportPropertyChanging("Status");
                _Status = value;
                ReportPropertyChanged("Status");
                OnStatusChanged();
            }
        }
        private global::System.String _Status;
        partial void OnStatusChanging(global::System.String value);
        partial void OnStatusChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Nasoka
        {
            get
            {
                return _Nasoka;
            }
            set
            {
                OnNasokaChanging(value);
                ReportPropertyChanging("Nasoka");
                _Nasoka = value;
                ReportPropertyChanged("Nasoka");
                OnNasokaChanged();
            }
        }
        private global::System.String _Nasoka;
        partial void OnNasokaChanging(global::System.String value);
        partial void OnNasokaChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 ID_profesor
        {
            get
            {
                return _ID_profesor;
            }
            set
            {
                OnID_profesorChanging(value);
                ReportPropertyChanging("ID_profesor");
                _ID_profesor = value;
                ReportPropertyChanged("ID_profesor");
                OnID_profesorChanged();
            }
        }
        private global::System.Int32 _ID_profesor;
        partial void OnID_profesorChanging(global::System.Int32 value);
        partial void OnID_profesorChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 ID_semestar
        {
            get
            {
                return _ID_semestar;
            }
            set
            {
                OnID_semestarChanging(value);
                ReportPropertyChanging("ID_semestar");
                _ID_semestar = value;
                ReportPropertyChanged("ID_semestar");
                OnID_semestarChanged();
            }
        }
        private global::System.Int32 _ID_semestar;
        partial void OnID_semestarChanging(global::System.Int32 value);
        partial void OnID_semestarChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Boolean> ActivePredmet
        {
            get
            {
                return _ActivePredmet;
            }
            set
            {
                OnActivePredmetChanging(value);
                ReportPropertyChanging("ActivePredmet");
                _ActivePredmet = value;
                ReportPropertyChanged("ActivePredmet");
                OnActivePredmetChanged();
            }
        }
        private Nullable<global::System.Boolean> _ActivePredmet;
        partial void OnActivePredmetChanging(Nullable<global::System.Boolean> value);
        partial void OnActivePredmetChanged();

        #endregion

    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("LightSwitchApplication", "FK_Aktivnost_Predmet", "Aktivnost")]
        public EntityCollection<Aktivnost> Aktivnosts
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<Aktivnost>("LightSwitchApplication.FK_Aktivnost_Predmet", "Aktivnost");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<Aktivnost>("LightSwitchApplication.FK_Aktivnost_Predmet", "Aktivnost", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("LightSwitchApplication", "FK_Izbrani_predmeti_Predmet", "Izbrani_predmeti")]
        public EntityCollection<Izbrani_predmeti> Izbrani_predmetis
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<Izbrani_predmeti>("LightSwitchApplication.FK_Izbrani_predmeti_Predmet", "Izbrani_predmeti");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<Izbrani_predmeti>("LightSwitchApplication.FK_Izbrani_predmeti_Predmet", "Izbrani_predmeti", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("LightSwitchApplication", "FK_Predmet_Profesor", "Profesor")]
        public Profesor Profesor
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Profesor>("LightSwitchApplication.FK_Predmet_Profesor", "Profesor").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Profesor>("LightSwitchApplication.FK_Predmet_Profesor", "Profesor").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<Profesor> ProfesorReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Profesor>("LightSwitchApplication.FK_Predmet_Profesor", "Profesor");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<Profesor>("LightSwitchApplication.FK_Predmet_Profesor", "Profesor", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("LightSwitchApplication", "FK_Predmet_Semestar", "Semestar")]
        public Semestar Semestar
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Semestar>("LightSwitchApplication.FK_Predmet_Semestar", "Semestar").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Semestar>("LightSwitchApplication.FK_Predmet_Semestar", "Semestar").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<Semestar> SemestarReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Semestar>("LightSwitchApplication.FK_Predmet_Semestar", "Semestar");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<Semestar>("LightSwitchApplication.FK_Predmet_Semestar", "Semestar", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="LightSwitchApplication", Name="Profesor")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Profesor : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Profesor object.
        /// </summary>
        /// <param name="iD_profesor">Initial value of the ID_profesor property.</param>
        public static Profesor CreateProfesor(global::System.Int32 iD_profesor)
        {
            Profesor profesor = new Profesor();
            profesor.ID_profesor = iD_profesor;
            return profesor;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> Br_kabinet
        {
            get
            {
                return _Br_kabinet;
            }
            set
            {
                OnBr_kabinetChanging(value);
                ReportPropertyChanging("Br_kabinet");
                _Br_kabinet = value;
                ReportPropertyChanged("Br_kabinet");
                OnBr_kabinetChanged();
            }
        }
        private Nullable<global::System.Int32> _Br_kabinet;
        partial void OnBr_kabinetChanging(Nullable<global::System.Int32> value);
        partial void OnBr_kabinetChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Korisnicko_ime
        {
            get
            {
                return _Korisnicko_ime;
            }
            set
            {
                OnKorisnicko_imeChanging(value);
                ReportPropertyChanging("Korisnicko_ime");
                _Korisnicko_ime = value;
                ReportPropertyChanged("Korisnicko_ime");
                OnKorisnicko_imeChanged();
            }
        }
        private global::System.String _Korisnicko_ime;
        partial void OnKorisnicko_imeChanging(global::System.String value);
        partial void OnKorisnicko_imeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Lozinka
        {
            get
            {
                return _Lozinka;
            }
            set
            {
                OnLozinkaChanging(value);
                ReportPropertyChanging("Lozinka");
                _Lozinka = value;
                ReportPropertyChanged("Lozinka");
                OnLozinkaChanged();
            }
        }
        private global::System.String _Lozinka;
        partial void OnLozinkaChanging(global::System.String value);
        partial void OnLozinkaChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Ime
        {
            get
            {
                return _Ime;
            }
            set
            {
                OnImeChanging(value);
                ReportPropertyChanging("Ime");
                _Ime = value;
                ReportPropertyChanged("Ime");
                OnImeChanged();
            }
        }
        private global::System.String _Ime;
        partial void OnImeChanging(global::System.String value);
        partial void OnImeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Prezime
        {
            get
            {
                return _Prezime;
            }
            set
            {
                OnPrezimeChanging(value);
                ReportPropertyChanging("Prezime");
                _Prezime = value;
                ReportPropertyChanged("Prezime");
                OnPrezimeChanged();
            }
        }
        private global::System.String _Prezime;
        partial void OnPrezimeChanging(global::System.String value);
        partial void OnPrezimeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Titula
        {
            get
            {
                return _Titula;
            }
            set
            {
                OnTitulaChanging(value);
                ReportPropertyChanging("Titula");
                _Titula = value;
                ReportPropertyChanged("Titula");
                OnTitulaChanged();
            }
        }
        private global::System.String _Titula;
        partial void OnTitulaChanging(global::System.String value);
        partial void OnTitulaChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Email
        {
            get
            {
                return _Email;
            }
            set
            {
                OnEmailChanging(value);
                ReportPropertyChanging("Email");
                _Email = value;
                ReportPropertyChanged("Email");
                OnEmailChanged();
            }
        }
        private global::System.String _Email;
        partial void OnEmailChanging(global::System.String value);
        partial void OnEmailChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Telefon
        {
            get
            {
                return _Telefon;
            }
            set
            {
                OnTelefonChanging(value);
                ReportPropertyChanging("Telefon");
                _Telefon = value;
                ReportPropertyChanged("Telefon");
                OnTelefonChanged();
            }
        }
        private global::System.String _Telefon;
        partial void OnTelefonChanging(global::System.String value);
        partial void OnTelefonChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 ID_profesor
        {
            get
            {
                return _ID_profesor;
            }
            set
            {
                if (_ID_profesor != value)
                {
                    OnID_profesorChanging(value);
                    ReportPropertyChanging("ID_profesor");
                    _ID_profesor = value;
                    ReportPropertyChanged("ID_profesor");
                    OnID_profesorChanged();
                }
            }
        }
        private global::System.Int32 _ID_profesor;
        partial void OnID_profesorChanging(global::System.Int32 value);
        partial void OnID_profesorChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Boolean> ActiveProfesor
        {
            get
            {
                return _ActiveProfesor;
            }
            set
            {
                OnActiveProfesorChanging(value);
                ReportPropertyChanging("ActiveProfesor");
                _ActiveProfesor = value;
                ReportPropertyChanged("ActiveProfesor");
                OnActiveProfesorChanged();
            }
        }
        private Nullable<global::System.Boolean> _ActiveProfesor;
        partial void OnActiveProfesorChanging(Nullable<global::System.Boolean> value);
        partial void OnActiveProfesorChanged();

        #endregion

    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("LightSwitchApplication", "FK_Aktivnost_Profesor", "Aktivnost")]
        public EntityCollection<Aktivnost> Aktivnosts
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<Aktivnost>("LightSwitchApplication.FK_Aktivnost_Profesor", "Aktivnost");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<Aktivnost>("LightSwitchApplication.FK_Aktivnost_Profesor", "Aktivnost", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("LightSwitchApplication", "FK_Predmet_Profesor", "Predmet")]
        public EntityCollection<Predmet> Predmets
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<Predmet>("LightSwitchApplication.FK_Predmet_Profesor", "Predmet");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<Predmet>("LightSwitchApplication.FK_Predmet_Profesor", "Predmet", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="LightSwitchApplication", Name="Prostorija")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Prostorija : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Prostorija object.
        /// </summary>
        /// <param name="iD_prostorija">Initial value of the ID_prostorija property.</param>
        public static Prostorija CreateProstorija(global::System.Int32 iD_prostorija)
        {
            Prostorija prostorija = new Prostorija();
            prostorija.ID_prostorija = iD_prostorija;
            return prostorija;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> Br_prostorija
        {
            get
            {
                return _Br_prostorija;
            }
            set
            {
                OnBr_prostorijaChanging(value);
                ReportPropertyChanging("Br_prostorija");
                _Br_prostorija = value;
                ReportPropertyChanged("Br_prostorija");
                OnBr_prostorijaChanged();
            }
        }
        private Nullable<global::System.Int32> _Br_prostorija;
        partial void OnBr_prostorijaChanging(Nullable<global::System.Int32> value);
        partial void OnBr_prostorijaChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Opis
        {
            get
            {
                return _Opis;
            }
            set
            {
                OnOpisChanging(value);
                ReportPropertyChanging("Opis");
                _Opis = value;
                ReportPropertyChanged("Opis");
                OnOpisChanged();
            }
        }
        private global::System.String _Opis;
        partial void OnOpisChanging(global::System.String value);
        partial void OnOpisChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 ID_prostorija
        {
            get
            {
                return _ID_prostorija;
            }
            set
            {
                if (_ID_prostorija != value)
                {
                    OnID_prostorijaChanging(value);
                    ReportPropertyChanging("ID_prostorija");
                    _ID_prostorija = value;
                    ReportPropertyChanged("ID_prostorija");
                    OnID_prostorijaChanged();
                }
            }
        }
        private global::System.Int32 _ID_prostorija;
        partial void OnID_prostorijaChanging(global::System.Int32 value);
        partial void OnID_prostorijaChanged();

        #endregion

    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("LightSwitchApplication", "FK_Aktivnost_Prostorija", "Aktivnost")]
        public EntityCollection<Aktivnost> Aktivnosts
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<Aktivnost>("LightSwitchApplication.FK_Aktivnost_Prostorija", "Aktivnost");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<Aktivnost>("LightSwitchApplication.FK_Aktivnost_Prostorija", "Aktivnost", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="LightSwitchApplication", Name="Semestar")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Semestar : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Semestar object.
        /// </summary>
        /// <param name="iD_semestar">Initial value of the ID_semestar property.</param>
        public static Semestar CreateSemestar(global::System.Int32 iD_semestar)
        {
            Semestar semestar = new Semestar();
            semestar.ID_semestar = iD_semestar;
            return semestar;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 ID_semestar
        {
            get
            {
                return _ID_semestar;
            }
            set
            {
                if (_ID_semestar != value)
                {
                    OnID_semestarChanging(value);
                    ReportPropertyChanging("ID_semestar");
                    _ID_semestar = value;
                    ReportPropertyChanged("ID_semestar");
                    OnID_semestarChanged();
                }
            }
        }
        private global::System.Int32 _ID_semestar;
        partial void OnID_semestarChanging(global::System.Int32 value);
        partial void OnID_semestarChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> Br_semestar
        {
            get
            {
                return _Br_semestar;
            }
            set
            {
                OnBr_semestarChanging(value);
                ReportPropertyChanging("Br_semestar");
                _Br_semestar = value;
                ReportPropertyChanged("Br_semestar");
                OnBr_semestarChanged();
            }
        }
        private Nullable<global::System.Int32> _Br_semestar;
        partial void OnBr_semestarChanging(Nullable<global::System.Int32> value);
        partial void OnBr_semestarChanged();

        #endregion

    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("LightSwitchApplication", "FK_Predmet_Semestar", "Predmet")]
        public EntityCollection<Predmet> Predmets
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<Predmet>("LightSwitchApplication.FK_Predmet_Semestar", "Predmet");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<Predmet>("LightSwitchApplication.FK_Predmet_Semestar", "Predmet", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("LightSwitchApplication", "FK_Student_Semestar", "Student")]
        public EntityCollection<Student> Students
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<Student>("LightSwitchApplication.FK_Student_Semestar", "Student");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<Student>("LightSwitchApplication.FK_Student_Semestar", "Student", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="LightSwitchApplication", Name="Student")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Student : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Student object.
        /// </summary>
        /// <param name="br_indeks">Initial value of the Br_indeks property.</param>
        /// <param name="iD_semestar">Initial value of the ID_semestar property.</param>
        public static Student CreateStudent(global::System.String br_indeks, global::System.Int32 iD_semestar)
        {
            Student student = new Student();
            student.Br_indeks = br_indeks;
            student.ID_semestar = iD_semestar;
            return student;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Br_indeks
        {
            get
            {
                return _Br_indeks;
            }
            set
            {
                if (_Br_indeks != value)
                {
                    OnBr_indeksChanging(value);
                    ReportPropertyChanging("Br_indeks");
                    _Br_indeks = value;
                    ReportPropertyChanged("Br_indeks");
                    OnBr_indeksChanged();
                }
            }
        }
        private global::System.String _Br_indeks;
        partial void OnBr_indeksChanging(global::System.String value);
        partial void OnBr_indeksChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Ime
        {
            get
            {
                return _Ime;
            }
            set
            {
                OnImeChanging(value);
                ReportPropertyChanging("Ime");
                _Ime = value;
                ReportPropertyChanged("Ime");
                OnImeChanged();
            }
        }
        private global::System.String _Ime;
        partial void OnImeChanging(global::System.String value);
        partial void OnImeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Prezime
        {
            get
            {
                return _Prezime;
            }
            set
            {
                OnPrezimeChanging(value);
                ReportPropertyChanging("Prezime");
                _Prezime = value;
                ReportPropertyChanged("Prezime");
                OnPrezimeChanged();
            }
        }
        private global::System.String _Prezime;
        partial void OnPrezimeChanging(global::System.String value);
        partial void OnPrezimeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Nasoka
        {
            get
            {
                return _Nasoka;
            }
            set
            {
                OnNasokaChanging(value);
                ReportPropertyChanging("Nasoka");
                _Nasoka = value;
                ReportPropertyChanged("Nasoka");
                OnNasokaChanged();
            }
        }
        private global::System.String _Nasoka;
        partial void OnNasokaChanging(global::System.String value);
        partial void OnNasokaChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Email
        {
            get
            {
                return _Email;
            }
            set
            {
                OnEmailChanging(value);
                ReportPropertyChanging("Email");
                _Email = value;
                ReportPropertyChanged("Email");
                OnEmailChanged();
            }
        }
        private global::System.String _Email;
        partial void OnEmailChanging(global::System.String value);
        partial void OnEmailChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Lozinka
        {
            get
            {
                return _Lozinka;
            }
            set
            {
                OnLozinkaChanging(value);
                ReportPropertyChanging("Lozinka");
                _Lozinka = value;
                ReportPropertyChanged("Lozinka");
                OnLozinkaChanged();
            }
        }
        private global::System.String _Lozinka;
        partial void OnLozinkaChanging(global::System.String value);
        partial void OnLozinkaChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Boolean> ActiveStudent
        {
            get
            {
                return _ActiveStudent;
            }
            set
            {
                OnActiveStudentChanging(value);
                ReportPropertyChanging("ActiveStudent");
                _ActiveStudent = value;
                ReportPropertyChanged("ActiveStudent");
                OnActiveStudentChanged();
            }
        }
        private Nullable<global::System.Boolean> _ActiveStudent;
        partial void OnActiveStudentChanging(Nullable<global::System.Boolean> value);
        partial void OnActiveStudentChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 ID_semestar
        {
            get
            {
                return _ID_semestar;
            }
            set
            {
                OnID_semestarChanging(value);
                ReportPropertyChanging("ID_semestar");
                _ID_semestar = value;
                ReportPropertyChanged("ID_semestar");
                OnID_semestarChanged();
            }
        }
        private global::System.Int32 _ID_semestar;
        partial void OnID_semestarChanging(global::System.Int32 value);
        partial void OnID_semestarChanged();

        #endregion

    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("LightSwitchApplication", "FK_Izbrani_predmeti_Student", "Izbrani_predmeti")]
        public EntityCollection<Izbrani_predmeti> Izbrani_predmetis
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<Izbrani_predmeti>("LightSwitchApplication.FK_Izbrani_predmeti_Student", "Izbrani_predmeti");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<Izbrani_predmeti>("LightSwitchApplication.FK_Izbrani_predmeti_Student", "Izbrani_predmeti", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("LightSwitchApplication", "FK_Student_Semestar", "Semestar")]
        public Semestar Semestar
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Semestar>("LightSwitchApplication.FK_Student_Semestar", "Semestar").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Semestar>("LightSwitchApplication.FK_Student_Semestar", "Semestar").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<Semestar> SemestarReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Semestar>("LightSwitchApplication.FK_Student_Semestar", "Semestar");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<Semestar>("LightSwitchApplication.FK_Student_Semestar", "Semestar", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="LightSwitchApplication", Name="sysdiagram")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class sysdiagram : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new sysdiagram object.
        /// </summary>
        /// <param name="name">Initial value of the name property.</param>
        /// <param name="principal_id">Initial value of the principal_id property.</param>
        /// <param name="diagram_id">Initial value of the diagram_id property.</param>
        public static sysdiagram Createsysdiagram(global::System.String name, global::System.Int32 principal_id, global::System.Int32 diagram_id)
        {
            sysdiagram sysdiagram = new sysdiagram();
            sysdiagram.name = name;
            sysdiagram.principal_id = principal_id;
            sysdiagram.diagram_id = diagram_id;
            return sysdiagram;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String name
        {
            get
            {
                return _name;
            }
            set
            {
                OnnameChanging(value);
                ReportPropertyChanging("name");
                _name = value;
                ReportPropertyChanged("name");
                OnnameChanged();
            }
        }
        private global::System.String _name;
        partial void OnnameChanging(global::System.String value);
        partial void OnnameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 principal_id
        {
            get
            {
                return _principal_id;
            }
            set
            {
                Onprincipal_idChanging(value);
                ReportPropertyChanging("principal_id");
                _principal_id = value;
                ReportPropertyChanged("principal_id");
                Onprincipal_idChanged();
            }
        }
        private global::System.Int32 _principal_id;
        partial void Onprincipal_idChanging(global::System.Int32 value);
        partial void Onprincipal_idChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 diagram_id
        {
            get
            {
                return _diagram_id;
            }
            set
            {
                if (_diagram_id != value)
                {
                    Ondiagram_idChanging(value);
                    ReportPropertyChanging("diagram_id");
                    _diagram_id = value;
                    ReportPropertyChanged("diagram_id");
                    Ondiagram_idChanged();
                }
            }
        }
        private global::System.Int32 _diagram_id;
        partial void Ondiagram_idChanging(global::System.Int32 value);
        partial void Ondiagram_idChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> version
        {
            get
            {
                return _version;
            }
            set
            {
                OnversionChanging(value);
                ReportPropertyChanging("version");
                _version = value;
                ReportPropertyChanged("version");
                OnversionChanged();
            }
        }
        private Nullable<global::System.Int32> _version;
        partial void OnversionChanging(Nullable<global::System.Int32> value);
        partial void OnversionChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.Byte[] definition
        {
            get
            {
                return StructuralObject.GetValidValue(_definition);
            }
            set
            {
                OndefinitionChanging(value);
                ReportPropertyChanging("definition");
                _definition = value;
                ReportPropertyChanged("definition");
                OndefinitionChanged();
            }
        }
        private global::System.Byte[] _definition;
        partial void OndefinitionChanging(global::System.Byte[] value);
        partial void OndefinitionChanged();

        #endregion

    
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="LightSwitchApplication", Name="TipNaAktivnost")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class TipNaAktivnost : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new TipNaAktivnost object.
        /// </summary>
        /// <param name="iD_tipNaAktivnost">Initial value of the ID_tipNaAktivnost property.</param>
        public static TipNaAktivnost CreateTipNaAktivnost(global::System.Int32 iD_tipNaAktivnost)
        {
            TipNaAktivnost tipNaAktivnost = new TipNaAktivnost();
            tipNaAktivnost.ID_tipNaAktivnost = iD_tipNaAktivnost;
            return tipNaAktivnost;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Ime
        {
            get
            {
                return _Ime;
            }
            set
            {
                OnImeChanging(value);
                ReportPropertyChanging("Ime");
                _Ime = value;
                ReportPropertyChanged("Ime");
                OnImeChanged();
            }
        }
        private global::System.String _Ime;
        partial void OnImeChanging(global::System.String value);
        partial void OnImeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 ID_tipNaAktivnost
        {
            get
            {
                return _ID_tipNaAktivnost;
            }
            set
            {
                if (_ID_tipNaAktivnost != value)
                {
                    OnID_tipNaAktivnostChanging(value);
                    ReportPropertyChanging("ID_tipNaAktivnost");
                    _ID_tipNaAktivnost = value;
                    ReportPropertyChanged("ID_tipNaAktivnost");
                    OnID_tipNaAktivnostChanged();
                }
            }
        }
        private global::System.Int32 _ID_tipNaAktivnost;
        partial void OnID_tipNaAktivnostChanging(global::System.Int32 value);
        partial void OnID_tipNaAktivnostChanged();

        #endregion

    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("LightSwitchApplication", "FK_Aktivnost_TipNaAktivnost", "Aktivnost")]
        public EntityCollection<Aktivnost> Aktivnosts
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<Aktivnost>("LightSwitchApplication.FK_Aktivnost_TipNaAktivnost", "Aktivnost");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<Aktivnost>("LightSwitchApplication.FK_Aktivnost_TipNaAktivnost", "Aktivnost", value);
                }
            }
        }

        #endregion

    }

    #endregion

    
}
